### ISSUE TITLE
Need data for MIT analysis

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1382]
If App Inventor, need to know app name and gmail account used.

This is somewhat tentative, the prompts might be confusing to people, but we do want to make this mandatory.

(This is tied to a grant.)

QA:

- Login as a student on a team
- Start your team submission
- Choose the Development Platform piece for editing
- Select "App Inventor 2"
- Verify that you are required to fill in the 2 fields about your project name and gmail address
- Verify that the input you enter for the gmail address must actually look like a gmail address
- Verify that you do not have to fill in those 2 fields with other choices

**Comment by monicagragg** [comment]
Hi @joemsak 

I logged into my student account and was able to:
- start a team submission
-  Select App Inventor 2
- Add the email attached to app inventor and project name (which is a Gmail account)
- Once added, I was redirected back to the dashboard and it said, "your project has been saved". 
- I did not have to fill in those two fields with other choices. But with other, there was a blank field.

Additional comment
- I don't understand what "ve
- I entered the same email for the student and parent and it would not allow me. I think this is a great tool, unless a parent will not allow their child to have an email.

**Comment by kmorton2017** [comment]
@monicagragg looks like one of your comments was cut short

**Comment by joemsak** [comment]
Thanks @monicagragg I have gone ahead and added a label to the blank "other" field to help clarify why it appears.

As for your additional comments, I'm not sure what you wanted to type in your first note, and your second note is unrelated to this card. It brings up a broader program question about student signups, and as far as I know, hasn't been a problem since last season which had the same requirement.
