### ISSUE TITLE
Each submission item could have its own url

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#1392]
QA:

- Login as a student on a team
- Start your team's submission
- Verify that each editable piece has its own unique URL that opens to that form in a new browser window

- you DO NOT need to report anything (besides unique URLs) that is missing or doesn't work very nicely, this card is ONLY about each piece having its own unique URL

**Comment by Allicolyer** [comment]
Hey Joe! This is looking good. 

Question: How would we embed these in the curriculum?

**Comment by kmorton2017** [comment]
Looks good. Only one minor suggestion-since we are all used to the hyperlinked blue text (or teal) maybe for the screenshot, source code, and business plan sections we can underline/color the "click here to select a file" text 

also not sure if this is just me, but on Google chrome when I click the back button the boxes get jumbled (see screenshot)

![uploads/33d4c1e8-7312-4950-83fc-82626f2d624e/Screen Shot 2017-12-11 at 2.15.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F33d4c1e8-7312-4950-83fc-82626f2d624e%2FScreen+Shot+2017-12-11+at+2.15.08+PM.png)

**Comment by joemsak** [comment]
Thanks @kmorton2017 we have also noticed the funky layout bug and are in the process of fixing it. As for the dropzones for file uploads, we will also work to make sure they are obvious. However, did you have a problem figuring it out at all? Last year we had dropzones with a similar style and they didn't seem to confuse or trip people up (never came up in support questions)
