### ISSUE TITLE
Improve screenshots UX - mainly allow re-sorting and deleting

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1395]

**Comment by Allicolyer** [comment]
Hey Joe! This is pretty nice. Here are some notes about using it:

1. After uploading screenshots the maximum number of screenshots, I get the message that I can't upload anymore. After deleting some, it still says I can't upload anymore. I have to refresh the page in order for it to allow me to upload more.

![uploads/1f9c2c77-2dff-4706-8336-131167906605/Screen Shot 2018-01-10 at 1.05.22 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1f9c2c77-2dff-4706-8336-131167906605%2FScreen+Shot+2018-01-10+at+1.05.22+PM.png)

2. Clicking "save this upload" takes me back to the submission page instead giving me a chance to re-arrange them. 

3. Could the thumbnails be a bit bigger? Since may screenshots will look alike it may be hard to tell what is uploaded. I know the page could quickly get really long if we do make them bigger so maybe this is a trade-off.

4. It is not obvious why I would rearrange them. I know that the judges will see them in that order, but participants may not.

**Comment by joemsak** [comment]
Hey @Allicolyer! 

1. Yep, I agree, I need to make that UX better
2. I think if I address point 1, it will fix this, too
3. Sure, let's make them bigger, I think vertical will still be okay at a limit of 6
4. I think this will be more obvious to the students when they use the "Submit for judging" button, but yeah .... I don't have a great answer for that right now

**Comment by joemsak** [comment]
@Allicolyer I am resubmitting this card for QA, MINUS fixing the part where you have to refresh the page or revisit it to see the uploaded screenshots for sorting

That is a larger, harder task, and I will make another card for it

Thanks!

**Comment by Allicolyer** [comment]
Thanks Joe!
