### ISSUE TITLE
RAs with and RPE of 15+ teams: assign judges to teams & vice versa

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1440]
QA:

- I currently have this code set to be enabled, regardless of number of teams on the event, to help with testing
---- I will change it to 15+ before going live
---- the difference is that RAs will not see the option to add judges to teams (or vice versa), when they hover them, until they have 15 teams on their event

- Login as RA
- Ensure you have an event with teams and judges added to it
- Verify that you can assign judges to teams and vice-versa
- Verify that you can easily unassign the judges and teams
- Verify you can filter the list of judges or teams by name, email, or submission name
- Verify this all works in the teams and judges lists

**Comment by kmorton2017** [comment]
i tried to add a team (paper products) to my event. there are only 3 teams in my region. it says that

"There are no more teams available to add to your event. Teams must not be attending other events, and must have started their submission.You can try searching for teams that are not in your region, but are close enough to travel to your event."

I logged in as this team to double check, and I can't see if I'm attending an event.

How does a team attending an event see this on their dashboard?

**Comment by joemsak** [comment]
@kmorton2017 we are working on the teams and judges seeing their selected event in another card

paper products is a senior team and your event is a junior division only event

**Comment by joemsak** [comment]
@kmorton2017 @ophelieh can I get final QA on this? Thanks!

**Comment by ophelieh** [comment]
Hi @joemsak It works great for me! I just have a few questions. 

* I noticed that judges who still need to complete their onboarding can be assigned a team. Is that something we want? 

* I completed all the info for my judge (ophelie+judge2@iridescentlearning.org) but on the RA event's page, it shows me as still needing to complete my onboarding. Is that because I didn't do the training? 


![uploads/db1c0ffb-1552-4f36-aa70-cb0120f61b3a/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdb1c0ffb-1552-4f36-aa70-cb0120f61b3a%2Fimage.png)

![uploads/bc7ead55-1460-4517-87a5-f1e264d56476/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbc7ead55-1460-4517-87a5-f1e264d56476%2Fimage.png)


* I noticed that when the RA is in judge mode, you can only see "Switch to mentor mode". Once you click on that then you select "judge mode" or "RA mode". Not sure if that's important but just wanted to point it out. 

Thank you!

**Comment by joemsak** [comment]
Thanks @ophelieh 

To answer your questions in order

1. The judge's status is there so the RA can make sure they are ready for the event. We trust our RAs will communicate with the judges to be ready. The RA should be able to plan and organize their event regardless of the judge's status, but they also need to know about it

2. Yes, you cannot complete your onboarding on QA because the training link is not ready, but it should be soon

3. Yes I noticed that too and it's out of scope of this particular card anyway but I will get to it

**Comment by ophelieh** [comment]
It all makes sense. Thank you!
