### ISSUE TITLE
Mentors view scores UI (without certificates)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1473]
You can check out the scores UI for mentors on QA now

- As admin, set scores / certs enabled
- Use this account for a mentor who is on two teams.

username: alli+m1@iridescentlearning.org
password: alli+m1@iridescentlearning.org

- Verify you can read all your QF scores

- Do NOT expect certificates to work for this card

**Comment by joemsak** [comment]
@Allicolyer Can I get you to outline in the card for me, how staff wants each certificate to work? Who should get which certificates? Thanks!

**Comment by Allicolyer** [comment]
@joemsak I will answer this on the other card.

**Comment by Allicolyer** [comment]
@ophelieh and @monicagragg can you both QA this either today or Monday :)?

**Comment by ophelieh** [comment]
Looks great! :) Could we have the team submission page open in a new tab, like we do for judges? 

Looks like the team below did not receive any scores. Is that correct?
And is that how teams who did not submit will look as well? If so, we should remove the text about pitch event and maybe replace "completing" by "participating". 

![uploads/81c404e6-242c-47d1-9f72-8768681c733d/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F81c404e6-242c-47d1-9f72-8768681c733d%2Fimage.png)

Also, on the dashboard, should we make the team name clickable? Right now the only way to see the team submission is by going in "view details" in the scoring/judging section. 

Thank you!

**Comment by monicagragg** [comment]
Sorry, was OOO on Friday and was catching up on Monday.

The alli+m1 login is not working for me. Can I use my faux mentor account to QA?

**Comment by joemsak** [comment]
@Allicolyer your login worked fine for me @monicagragg are you sure you're entering the credentials correctly? I just now logged in on QA with the information she provided

**Comment by Allicolyer** [comment]
@joemsak I noticed that all official scores all say "Official Scores - these scores counted". We only need it to say this if the team has unofficial scores. 
<ol>
<li> We don't it to say this for any semi finals scores </li>
<li> We don't need it to say this if teams do not have an "unofficial scores" </li>
</ol>

**Comment by joemsak** [comment]
Aha okay no problem I will fix it today

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by joemsak** [comment]
Should be fixed now!

**Comment by ophelieh** [comment]
Looks and works great!

**Comment by kmorton2017** [comment]
A couple notes for the  alli+m1@iridescentlearning.org dashboard:

- I noticed that it says "average first round scores" and "average semifinals score". Can we switch to be "quarterfinals" and semifinals? 
- I like the text that accompanies the mentor page. It is a bit more thorough in explaining the different cases. Can we use this for the students? See below the different use case text

No Scores: Unfortunately, no scores are available for Potato Smashers because the submission was incomplete. Give your team some feedback on how to improve for next year!
RPE No Scores: Congratulations on completing the 2018 season of Technovation! Your team can use the feedback they received at their pitch event to help learn more and to participate in Technovation next year. Your team should be proud of their work and share it with friends and mentors!
Unofficial Scores: These scores are from a celebration event

**Comment by joemsak** [comment]
@kmorton2017 done, please check again today thank you!

**Comment by Allicolyer** [comment]
Thank you at @kmorton2017 !

**Comment by kmorton2017** [comment]
Thanks for making the text adjustment! Just two very minor text suggestions (take it or leave it!) :

Official Scores - These scores are counted towards average
Unofficial Scores - These scores are from a Celebration Event

**Comment by joemsak** [comment]
@kmorton2017 I am thinking of using the label of "Celebration" instead of unofficial in the first place, what do you think?

**Comment by Allicolyer** [comment]
@joemsak I think you should go for it. The teams likely don't know the word "unofficial".

**Comment by joemsak** [comment]
The small changes have been made for the mentor view

**Comment by Allicolyer** [comment]
Awesome. I think this looks good now.
