### ISSUE TITLE
Separate "complete" scores from "unofficial complete" scores 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1506]
Separate "complete" scores from "unofficial complete" scores in the admin score view.

**Comment by stenington** [comment]
Here are some related notes about the codebase, and I think @kmorton2017 is going to work on confirming some things from the admin side.

Submission scores have a field to record whether they're considered official or unofficial. In the admin in the Scores section, the **Complete scores** are **Incomplete scores** columns are showing official scores only. The score detail page shows the official and unofficial averages separately, although I'm not sure the rest of the pages handles the official/unofficial distinction correctly.

Maybe one way to approach this @kmorton2017 is to take screenshots of each page and label where you'd want additional filters or options to show official vs. unofficial, or to label which type of score you would expect to show up where. Then we can both verify that what we have is correct, and begin adding the extra information where you want it.

**Comment by hellafitz** [comment]
@stenington can you clarify this sentence: "In the admin in the Scores section, the Complete scores are Incomplete scores columns are showing official scores only."?
@rsgonzal to add screenshots.

Big picture options:
- remove unofficial scores from the platform and stop judges from submitting unofficial scores (unknown implications and effort)
- continue supporting both official and unofficial scores, but improve how they are displaying so that users aren't (as) confused

**Comment by stenington** [comment]
Oh, I think "are" should be "and". I corrected that in my original comment. 

What it means is this. Let's say a team has 4 scores: 2 official, 2 unofficial. And in each group, 1 is complete and 1 is incomplete. If you logged in as an admin, clicked **Scores** in the menu, and found that team, you would see a 1 under **Complete scores** and a 1 under **Incomplete scores**, because those columns are filtering out the unofficial scores.
