### ISSUE TITLE
Students: Scores UI (without Certificates)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1509]
You can check out the scores UI for students on QA now

- As admin, ensure you have teams with completed QF scores
- As admin, set scores / certs enabled
- Login as a student on the team with the QF scores

--- READ IF YOU LOGIN AS STUDENT FROM ADMIN
------- be aware the total shown that sticks to the top of the page is impacted by the extra "logged in as ..." admin bar
------- logging in directly as the actual student is preferred for QA, thank you!

- Verify you can read all your QF scores

- Do NOT expect certificates to work for this card

**Comment by ophelieh** [comment]
Hi Joe! It looks great, I love how it looks and how easy it is to use! :) 

Now that I turned judging off though, I can see the "pitch presentation upload" on the student dashboard. Is there a way for us to remove it, or do you have to do it? 


![uploads/251002a9-3a2e-4389-b0cd-dc2e66c133b6/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F251002a9-3a2e-4389-b0cd-dc2e66c133b6%2Fimage.png)

Thank you!

**Comment by Allicolyer** [comment]
Great point. Thank you @ophelieh.

**Comment by joemsak** [comment]
Thanks @ophelieh take another look in about 20 minutes if you can!

**Comment by Allicolyer** [comment]
@joemsak @RRios00 this is looking fantastic. However, there is no place that shows the average score for the round

**Comment by ophelieh** [comment]
Looks great! Love that they can see their scores AND submission. :) 

I agree with Alli that it would be nice for the teams to see their average score. 

And for the submission part, could we change the title from "Submission Progress" to "Your Submission" or just "Submission"? 

Thank you! And enjoy the long weekend!

**Comment by joemsak** [comment]
@ophelieh @Allicolyer thanks and please check again today

**Comment by ophelieh** [comment]
Looks and works great!

**Comment by Allicolyer** [comment]
@monicagragg can you take a look at this today or Monday?

As admin, set scores / certs enabled. Then please log out and use this log in:

username: alli+s3@iridescentlearning.org
password: alli+s3@iridescentlearning.org

**Comment by Allicolyer** [comment]
Here are few different scenarios in which teams get their scores.  

@kmorton2017 can you take a look at this?

<b>Team with completed submissions</b> 
<ul>
<li>Official quarterfinals scores: Great Team </li>
<ul>
<li> username: alli+s10@iridescentlearning.org </li>
<li> password: alli+s10@iridescentlearning.org </li>
</ul>
<li>Both official and unofficial quarterfinals scores: California Coders </li>
<ul>
<li> username: alli+s1@iridescentlearning.org </li>
<li> password: alli+s1@iridescentlearning.org </li>
</ul>
<li>Both quarterfinals and semifinals scores: Super Equipo </li>
<ul>
<li> username: alli+s3@iridescentlearning.org </li>
<li> password: alli+s3@iridescentlearning.org </li>
</ul>
<li>no scores (RPE judges did not put any in): Skittles and M&Ms</li>
<ul>
<li> username: student@student.com </li>
<li> password: student@student.com </li>
</ul>
</ul>

<b>Team without completed submission:</b> Potato Smashers
<ul>
<li> username: alli+s4@iridescentlearning.org </li>
<li> password: alli+s4@iridescentlearning.org </li>
</ul>
</ul>

**Comment by ophelieh** [comment]
Pretty cool that you can see the judge's location! 

For scenario #4 - teams with no scores. We might want to write a similar note to what mentors see, otherwise, they might be confused about why they don't see their scores. Could be in the "quarterfinal score" tab in the "View scores and certificates" or some text on the student's dashboard. Not sure where it would make the most sense. 
Mentor text: " Congratulations on completing the 2018 season of Technovation! Your team can use the feedback they received at their pitch event to help learn more and to participate in Technovation next year. Your team should be proud of their work and share it with friends and mentors!"

For the team without a completed submission: do they receive a certificate? If so, where will that appear? and should we mention something about their submission not being complete? 

Thank you. :)

**Comment by kmorton2017** [comment]
Hi, 

A few thoughts:

1) What is official vs. unofficial score? I think that means Celebration Events right? For many students they may not understand what that means. I think it could be confusing. It may just be better to lump all scores under QF and not distinguish between them for a student/mentor.
2) Is the average that they see, a combination of the official and unofficial scores? 
3) What about teams who had a Celebration Event for the first round (unofficial) but then advanced to the SF? Are their unofficial scores all lumped under the QF scores?

**Comment by joemsak** [comment]
@ophelieh & @kmorton2017 yes there are participation certificates, please hold your QA on that feature for when the cards are ready for testing - you can see they are still in progress

@ophelieh I put in the extra text states as you requested, for students who didn't finish their submission, or who did not receive scores online

@kmorton2017 I have now lumped all the unofficial and official scores into the quarterfinals tab.

Only the official scores count toward the average.

I don't understand your question about unofficial scores being lumped with official ones. You saw that they are (were) in separate tabs so I don't know why you're wondering if they're lumped together if you saw that they are not (were not). Can you clarify your question?

Mentor views have to be built differently in consideration that a mentor can have multiple teams, so we use a different layout to help them glance over what could be a lot more scores than a student would see.

**Comment by Allicolyer** [comment]
Thank you @kmorton2017 and @ophelieh!

@kmorton2017 
What if we call "unofficial scores" "celebration event scores"? I strongly disagree with lumping them all together because the averages are calculated based on official events only. People will email us and tell us their average score is wrong. I also think girls who attended a "celebration event" will understand why they have two sets of scores. To be clear, all teams who attended a "celebration event" have official scores. They only have "unofficial scores" if the judges put the scores into the platform at the event.

@joemsak I do not see the text for a student who did not finish their submission.

**Comment by kmorton2017** [comment]
Thanks for thinking that through @Allicolyer I think you are right we may get questions about the average score if both the unofficial and official scores are lumped together.  I think we have 2 options then:

1) Tabs for Quarterfinals and "Celebration Event" 
OR
2)  Keep Quarterfinals tab and Unofficial Scores tabs but explain that Unofficial Scores are from Celebration Events and don't count towards their average.

You asked me to clarify on one of my questions. It was: what happens if a team attended a Celebration Event and advanced to the semifinals? What would their screen look like ? 

+1 to alli--I don't see the text up yet for a student who did not finish their submission.

**Comment by ophelieh** [comment]
team with no scores (RPE judges did not put any in): Skittles and M&Ms --- Looks good! 

Team without completed submission: Potato Smashers -- this is what I see: 


![uploads/13768666-1d90-45ad-8af4-52f1e1e319bf/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F13768666-1d90-45ad-8af4-52f1e1e319bf%2Fimage.png)

Could we add something like: "Thank you for your participation. Unfortunately, no scores are available for your team because your submission was incomplete. We hope you will continue working on your app and join again next season!" 

Thanks!

**Comment by Allicolyer** [comment]
@kmorton2017 Which method would you prefer? I've updated alli+s1@iridescentlearning.org to be a semifinalist so you can check out what a semifinalists with both unofficial and official scores looks like.

**Comment by Allicolyer** [comment]
Okay so @joemsak here's the feedback:

1. Add this text for teams who are not getting scores b/c they did not finish their submission: 

"Thank you for your participation. Unfortunately, no scores are available for your team because your submission was incomplete. We hope you will continue working on your app and join again next season!"

2. Separate unofficial and official quarterfinals score, either through separate tabs or by labeling them accordingly. @kmorton2017 is going to get back to us about which method she prefers. Here are the labels suggested by Katie:

Official Scores - These scores are counted towards average
Unofficial Scores - These scores are from a Celebration Event

**Comment by joemsak** [comment]
FWIW @kmorton2017 and @Allicolyer I like the idea of separating them and using the word "Celebration" over 'unofficial'

**Comment by Allicolyer** [comment]
@joemsak thanks!

**Comment by joemsak** [comment]
@Allicolyer this is going back to QA today - I am not sure how to fit the explanation sentence into the design but I think that having them in separate tabs and showing the different score in each tab should work pretty well. Also there are only 40 unofficial scores so it's not as common of a use-case for students to even see a 2nd tab

and "unofficial" is now "Celebration"

The text is there now for students who did not complete enough of a submission for a participation certificate. Or would you prefer that the text is there for the participation students as well?

**Comment by Allicolyer** [comment]
Hey @ophelieh could you QA this? Here are the last two few things to do:

Make sure we are happy with how a team with both official and unofficial quarterfinals scores looks: 
<ul>
<li>California Coders</
<li>username: alli+s1@iridescentlearning.org</li>
<li>password: alli+s1@iridescentlearning.org</li>
</ul>
As Joe mentioned, there are only 40 celebration event scores so this not a very common scenario.

Teams with a very incomplete submission will get a text blurb explaining why they have no scores:
<ul>
<li>California Coders</
<li>username: alli+s15@iridescentlearning.org</li>
<li>password: alli+s15@iridescentlearning.org</li>
</ul>

Team who has more than 50% of their submission complete will get a participation certificate. Would we like a text blurb to accompany this?
<ul>
<li>California Coders</
<li>username: alli+s4@iridescentlearning.org</li>
<li>password: alli+s4@iridescentlearning.org</li>
</ul>

Thank you!

**Comment by ophelieh** [comment]
@Allicolyer @joemsak Everything looks great! :) 

Just a quick note/question, for the teams receiving a participation certificate, shouldn't we remove "Challenge" from the text? 


![uploads/ad22ad99-6a52-4624-af0d-22ba553b82b7/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fad22ad99-6a52-4624-af0d-22ba553b82b7%2Fimage.png)

Thank you!

**Comment by kmorton2017** [comment]
looks good with the celebration event scores!

**Comment by Allicolyer** [comment]
sure @ophelieh we can remove "challenge". So you would just like it to say "Thank you for participating in Technovation 2018".

**Comment by joemsak** [comment]
@ophelieh @Allicolyer I have removed 'challenge' from the blurb

**Comment by ophelieh** [comment]
Looks great @joemsak ! Thank you :)

**Comment by Allicolyer** [comment]
Thank you @ophelieh @kmorton2017 for all the QA :) Closing this card.
