### ISSUE TITLE
Investigate why comments are being cut off

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1533]
Comments left by judges are being cut off:

Technical: https://my.technovationchallenge.org/admin/scores/16269#/

Technical and Entrepreneurship: https://my.technovationchallenge.org/admin/scores/15639#/

Ideation, Pitch, and Overall Impression: https://my.technovationchallenge.org/admin/scores/16243#/

Entrepreneurship: https://my.technovationchallenge.org/admin/scores/15288#/

Pitch: https://my.technovationchallenge.org/admin/scores/16321#/

All sections: https://my.technovationchallenge.org/admin/scores/16280#/

Ideation and Overall Impression: https://my.technovationchallenge.org/admin/scores/16266#/

Pitch: https://my.technovationchallenge.org/admin/scores/15656#/

**Comment by joemsak** [comment]
How to test this is fixed:

Ensure judging is enabled and there is a submission to judge
Login as a judge who can judge the submission

Start a new score
type 'hello'
wait a moment
refresh
verify 'hello' is still there
add ' wo' after hello
wait a moment
refresh
verify ' wo' is still there

The explanation is this: Comments are analyzed and saved to our server while the judge types. However, we left a bad bug where the comment is not sent back to the server if the code logic does not trigger the analysis to run. One way to verify this is to test the profanity analysis, since it requires at least one word, OR, an even number of words before it triggers. Since `wo` doesn't count as a word, it should not run analysis, but it now should still save (it wasn't before)

**Comment by Allicolyer** [comment]
@joemsak decision by program team is to leave the comments as they are. If tickets come through on zendesk we will deal with it then
