### ISSUE TITLE
“Need to opt-in to emails” on newsletters Distinction between: Marketing email vs. Account update email

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1551]
What is the distinction we want to make between marketing email vs. account update email

**Comment by Allicolyer** [comment]
@amyiridescent can you schedule time with Joe and Alan so we can reach a decision about this?

**Comment by joemsak** [comment]
Based on my reading of the GDPR source documents, consent is one of several conditions that an organization can use to process personal data such as email addresses. And the law states only one condition has to be met.

Two other conditions that should be applicable to us are:

```
(b) processing is necessary for the performance of a contract to which the data subject is party or in order to take steps at the request of the data subject prior to entering into a contract; 
```

and

```
(f) processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data, in particular where the data subject is a child. 
```

It seems to me, we are processing their email for legitimate purposes both on campaign monitor and in our system emails, because we use these emails solely to assist students in their progression in the program. @amyiridescent is hesitant only on the campaign monitor front because sometimes we recommend external programs and competitions for students to try, so she would prefer we demonstrate "a best attempt" by requiring the opt-in consent condition for the campaign monitor emails

Maggie will want to be aware of this decision as the registration numbers and the list numbers most certainly will not align.

We will probably want to encourage participants who did not check the box while signing up (or signing in to the new season) to consider subscribing, with a call to action at the bottom of their dashboard explaining the benefits and that we're really mostly not marketing anything to them. I'm not sure that sometimes recommending other programs even counts in this regard as marketing. I assume we're not being paid to make those recommendations, and again we're legitimately trying to help students succeed in their personal goals, even if that's not with our program.

**Comment by joemsak** [comment]
Honestly, my personal and professional opinion here is that adding the opt-in checkbox would be an overly cautious step, and it seems that the greater risk here is a net negative impact on our program and the success of the students, if they're not receiving helpful emails. I certainly would not expect them to even notice the checkbox let alone enthusiastically check it. All the "benefits" copy in the world will most likely go unread or ignored by most.

**Comment by amyiridescent** [comment]
Thanks Joe for looking into this. I agree that we are really not the main target of this law so I am not terrible worried. Ok lets do this. 

1. No need to build an additional "opt in" check box during registration steps. (I think all platform sent emails are necessary for program operations.) 
2. We should note somewhere in the sign up steps that they will be receiving emails from the platform from time to time. 
3. On email newsletter, make the "opt out" very clear and easy to do. **Alli** can you make sure **Maggie** is aware of this? 
4. Create steps on how a user can delete it's account if needed. 
5. (Off platform) Develop good practices on how to keep personal identifiable information safe when using csvs and other off platform tools. (Safety & prevention task force is already working on this.) 

Let me know if I missed anything.

**Comment by joemsak** [comment]
Thanks @amyiridescent - items 4 & 5 are very involved and would require their own cards and discussion in sprint planning. Thanks again

**Comment by joemsak** [comment]
I have an idea about informing our participants about how we use their data during sign up (and a new dashboard item for returning participants)

Instead of a check box about the newsletter, we can require a checkbox to sign up, for clear consent of data processing with a simple, clear, and very short explanation about how we keep their data private and secure, we don't sell it or share it, and we use it only to improve their participation in our program. We will never do something with their data that they would not reasonably expect us to be doing... something like that to put a point on it.

Right now, signing up is an "implied" consent to our terms, we can make it explicit. I'm thinking that may be a good compromise so we can still be cautious, but not overly so, and not create a negative impact on our program where people miss signing up for our helpful email guidance.

**Comment by amyiridescent** [comment]
@joemsak I love this idea. I love that we won't be burying this into a 3 page consent form. Lets make sure the language is easy to understand for english learners. :)

**Comment by joemsak** [comment]
@amyiridescent here is my first draft on the language of our data use terms

i already feel it's quite long and this is still only a first draft, I'm sure it can be edited down and improved. also, the UI/UX design will need some thought, but that will probably take more effort than crafting the language which we can go back and forth on now...

https://docs.google.com/document/d/1ekB535hAjdMJA0e62Y_oTxijECHoAccniOoPxbS_zK4/edit#heading=h.fq95owk03k2l

**Comment by joemsak** [comment]
@Allicolyer  This has been discussed and is merging into the wizard registration card #1596.  Should be closable

**Comment by Allicolyer** [comment]
thanks @joemsak makes sense.
