### ISSUE TITLE
XLook into using hellosign for parental consent forms

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1553]
In particular, an SMS interaction would really help students complete their parental consents

**Comment by joemsak** [comment]
Definitely seeing this as a great solution for normal electronic signature usage as we're already used to having, and tracking status with their API, but I have not found any leads on if it's possible for someone to sign via SMS yet. Will continue digging

**Comment by joemsak** [comment]
maybe it might be enough to provide the printable PDF and allow a photo upload of the signed form. smartphones are pretty cheap and common even in developing countries, or we can hopefully count on a teacher or mentor having the ability to take the photo at least

**Comment by joemsak** [comment]
@Allicolyer @amyiridescent at this time I wouldn't highly prioritize integrating HelloSign only because it doesn't seem that we would get the ability to sign with SMS out of it, and essentially we would have the same feature but on another site

HOWEVER

Perhaps we can consider use of HelloSign as being more ... proper? I guess would be the word to use, and if we are able to show the english and translated documents side by side that would also be a plus

Integrating HelloSign to replace our current parental permission workflow would certainly be a bit involved in terms of development and user experience effort, so just let me know if the trade off is worth it to you to prioritize the change. I am open to whatever staff decides is best. Thanks!

I would definitely recommend updating our parent workflow at least to introduce ourselves in a more friendly way to parents before asking for the permission. That would of course be a separate card to be discussed in the next sprint planning.

**Comment by joemsak** [comment]
@Allicolyer @amyiridescent @madhavitechnovation this card has just been waiting for discussion / questions / etc

**Comment by kmorton2017** [comment]
i have a couple thoughts! 

1) @joemsak do you remember from the Oracle Hackathon, one of the winning teams developed a way to use Twilios SMS feature to get parental consent. Would this help in regards to this card? I don't think they incorporated Hello Sign at all. 
2) I definitely think having the translated documents side by side would be helpful for parents to view. 
2) Could we include a feature for RA's to upload the pics of student consent? That way we cut out the middle man (us) in uploading them to the platform. Not sure what @amyiridescent and @madhavitechnovation 's thoughts are though

**Comment by joemsak** [comment]
@kmorton2017 

1. yes, however I am not currently up to date on twilio support for international SMS

2. agree, though hello sign integration is not necessarily required for such a feature

3. yes, I think we should improve our parental consent workflow even for the student to upload it, maybe with an admin / RA review step, but RAs could upload as well, bypassing the review step

**Comment by Allicolyer** [comment]
During the spring the team decided that the use of hellosign is not a priority right due to the reasons outline by Joe.
