### ISSUE TITLE
Look into Wordpress cookies for curriculum

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1555]
We want to know how far students are getting in the curriculum.

**Comment by joemsak** [comment]
It looks as though the cookies can be shared due to the root domain being the same

So I think @adrichey and I should discuss a small JS script to embed on the wordpress curriculum pages to report progress back to our database, connecting the currently logged in user.

Perhaps then, we can also prompt people to login if they're not, when they visit these pages

**Comment by adrichey** [comment]
I think that sounds like a good approach @joemsak. I think I need to talk to someone about getting admin access to the WordPress site and/or host so that I can upload this script once it is complete. Are we requiring that people log in to the curriculum via a TC WordPress account? If not, we will want to talk about what information we should be collecting and adding to the DB in order to figure out how to track a user between sessions if that is possible.

**Comment by joemsak** [comment]
no, we don't require wordpress accounts, we just don't publish the URL except through the sidebar on the participant's dashboard, a kind of logging in. we don't want to require a second account.

as for your access to our wordpress, yeah I think you have to be invited by another admin. let me see if I can do it

**Comment by adrichey** [comment]
Thanks @joemsak. I just changed my password and was able to log in.

**Comment by joemsak** [comment]
I have successfully been able to change our cookies to set the domain so that we can enable reading them on the wordpress side

@Allicolyer please note I'm not sure how this will be verifiable with QA because the domains don't match. Will try to think more on that and let you know if I come up with something.

**Comment by Allicolyer** [comment]
Thank you @joemsak !
