### ISSUE TITLE
Research location best practices (i.e. How does Google and Facebook solve this issue?)

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1569]
Including digging deep on Google API

**Comment by joemsak** [comment]
@Allicolyer @adrichey @madhavitechnovation @amyiridescent 

I've taken a look at what Facebook is doing for brand new users (using incognito browsing which will not use existing cookies or allow geolocation features) and realized that they are using IP Geocoding on the server side, so I've updated our codebase to do this as well

Takeaways:

* Allowing browser-based geolocation is not necessary - we don't have to rely on the user permitting it

* The IP address is information the server gets from every single visitor to our site, even people (or bots) not logged in, so we are allowed to use it for our purposes

* IP location is not specific to the user, it is specific to their internet connection company (better known as their ISP, or Internet Service Provider), meaning we get location at the city level
  * this is great because it's not personal, private user data, it's public information about their ISP, and we don't need a more accurate location than city

* We can process the user's location in the backend and add a quick onboarding UI element to have them confirm it

**Comment by joemsak** [comment]
@Allicolyer the 'next step' for this card would be any response or questions to what I wrote above. Thanks!

**Comment by Allicolyer** [comment]
@joemsak I think we confirmed to move forwards with trying this.

**Comment by joemsak** [comment]
yep you can close this i have a new card for improving the form
