### ISSUE TITLE
Wizard Style Registration UI

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1596]
Create UI for wizard style registration that will include the following steps

Students:
1.General information (name, school, password) 
2. Location
3. Parental Consent

Mentors:
1.General information (name, school, password) 
2. Location
3. Background Check (if applicable)
4. Consent form

**Comment by Allicolyer** [comment]
@kmorton2017 could you QA this? Sign up for both a student and mentor account. An

**Comment by joemsak** [comment]
@Allicolyer I would also ask that we have staff in various locations QA this, and maybe even @kmorton2017 is comfortable asking some RAs, once we have the intro page and other assets from Ruby to smooth this experience out. 

I know Katie has some location form concerns from RAs she wants us to know about and prioritize

Also, the signing in at the end to the dashboard is being ironed out to match the new layout and experience while reusing the existing code and behavior. I would wait to invite outsiders until after that is on QA and staff is mostly happy

Thanks!

**Comment by joemsak** [comment]
@Allicolyer @kmorton2017 @ophelieh and other QA'ers please bear in mind a few notes

it seems we all agree that we want to have a nicer intro splash page. @RRios00 and I are working on that off of QA right now. We will continue to work on the assumption that most people have come from the marketing site because even people with an account typically use the marketing site to get to the platform. In other words, access to signing up and logging in will be prioritized with an emphasis on a more concise introduction with a link to the full marketing site.

if you find the dashboard jarring upon completion of signing up, we couldn't agree more. we are arranging the existing boxes on the dashboard, and the code that makes them work, in a small VueJS app that just handles navigation between them and then hopefully our app will be guiding the user smartly as the season and their profile/activity progress. @adrichey and I will have QA prototype-readiness on the student dashboard version of this idea soon

we hope to use the next month polishing the finer details with top navigation, how we communicate the completion of each main part and sub-section, and importing the existing code of the submission process into this lightweight navigation app, if doing so for student and mentor onboarding goes well. those features will creep into the next sprint.

i hope this information helps you to contextualize your QA work on this card better, and to share in the design/dev team's vision. if so, I will try to make these write-ups more often. if not, no harm done. thank you to all mentioned here very much for your time and effort in helping us make our platform's experiences better

**Comment by kmorton2017** [comment]
Here is my feedback after creating a student Lucy Liu (katie+s3@iridescentlearning.org) and the steps I took:

1) Created Jerusalem location in Arabic. When I go to location confirmation page it is still in Arabic. BUT it is located in Palestine which is great.
2) Created Jerusalem location in English, confirmed in Palestine which is great. 
3) Created Hong Kong location in Chinese. When I go to the confirmation page it is in English but the state/province field is missing. :) 
4) Created Hong Kong location in English. When I go to to the confirmation page it is in English  but the state/province field is missing. 
5) Chose to be a student that is 14. Selected"student" option
6) Filled out email address. Received error message on white page. Refreshed and got "Sorry page"
7) Navigated using back button, and it said my account was a "mentor" account which was incorrect and asked me to fill out the job title, company, etc.. 
8) Somehow it transformed back into a student page once I clicked on one of the fields in the side bar and the mentor information fields disappeared. (sorry I can't be more specific!) 

Summary of feedback:
-Arabic text is still in Arabic on confirmation page (but Chinese is translated into English on confirmation page) 
- State/province field is missing for Hong Kong. Will this influence their submission? Last year we had issues with HK students submitting because they had a missing state/province field I think. 
-Error message when I tried to complete final step and input email. Navigated using back button, incorrectly assumed that I was a mentor account.

**Comment by kmorton2017** [comment]
Here is my feedback for mentor Matthew Han and the steps I took. 
1) Set location to Taipei, Taiwan, Taiwan for city, state/province, and country/territory. 
2) Confirmed location 
3) Proceeded through mentor registration. Was not permitted to continue to mentor sign up. Was not prompted with any reason why.  (it would be helpful to have a message saying you need to fill out all fields or something like that). 
4) Saw that the "set region" bubble was not filled in, attempted to fill in location fields and confirm location again. Would not permit me to set my location.  See gif below

![uploads/0ed4205c-9ab5-4312-856c-7885b14cb390/mentor sign up issue.gif](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0ed4205c-9ab5-4312-856c-7885b14cb390%2Fmentor+sign+up+issue.gif)

**Comment by joemsak** [comment]
@kmorton2017 Thank you so much for your findings. I think I was able to address them. Please try again. I'm still trying different layouts so yes I know about the navigation shifts, left me know if you have comments about the change though

@Allicolyer just wanna double check that we'll have other staff in other areas / regions help us test this one. thanks!

**Comment by Allicolyer** [comment]
Hey @joemsak I am going to close this card since any issues with the wizard have been split up into a lot of different cards

**Comment by kmorton2017** [comment]
it looks like the character limit was not counting for the mentor personal summary. It never changed from zero. 

looks like the bug with the location and team location was fixed and they are both displaying as my confirmed location. 

i invited a student to join a team. when i opened the invitation as the student, it says "you are on the team: Null Team" is it supposed to say that? 

![uploads/39046c0c-dd85-46cf-b2c5-c5646db20b45/Screen Shot 2018-09-07 at 4.07.57 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F39046c0c-dd85-46cf-b2c5-c5646db20b45%2FScreen+Shot+2018-09-07+at+4.07.57+PM.png)
