### ISSUE TITLE
Update the language for international mentors

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1611]
Update the language for international mentors that they might be selected for random background checks. @amyiridescent will give us the new text.

**Comment by amyiridescent** [comment]
So this should be a check box they click on. (The goal here is to deter any mentors who would not want to be background checked from signing up.) Only for non-US mentors. 

Maybe a language like this will work? 
"By checking this box, you are agreeing to comply to international criminal background check. We will be randomly select mentors to be background checked. If you are selected, we will contact you to share steps required to complete the background check. Failure to comply will result in disabling of your account.  Thank you for helping us keep our students safe."

**Comment by joemsak** [comment]
Why don't we just merge this into the main terms agreement checkbox we're already adding?

**Comment by Allicolyer** [comment]
@amyiridescent we are blocked here too

**Comment by joemsak** [comment]
Confirmed in sprint meeting to put it in the agreement copy

**Comment by joemsak** [comment]
I saw Amy had feedback that the current QA language is challenging to understand. I did some tweaks and here is the language I have as of this morning:

**Mentors outside US: Background checks**

Background checks are reports of your work and legal history. In countries where these checks are universally easy or required, we will submit all mentors to this process. You may be required to complete and pass a background check in order to be allowed and verified on our site.

In other countries and territories, we will randomly select mentors to provide references and legal certifications, and to submit to background checks where possible. If you are selected, we will contact you to complete this process. You must do this to be allowed and verified on our site.

Thank you for helping us keep our students safe.

**Comment by amyiridescent** [comment]
@joemsak 
I think the second paragraph is fine. Maybe just change the last sentence to say "You must consent to this to be allowed and verified on our site." (Mostly because we won't be selecting or running background checks until way into the season.) 

Regarding first paragraph, I am not sure what we are trying to say here. Is this for cases like Spain where RAs need to run background checks on mentors? It might be confusing for mentors since we don't list which are countries we will do this for and also in reality, this will run AFTER they create a mentor account right?

**Comment by joemsak** [comment]
@amyiridescent 

1. Okay, I will update it

2. Yes, you are correct on all counts, and I don't think we necessarily have to list where we will do it for sure, just that we might ask you to submit to one, and you agree to that

**Comment by Allicolyer** [comment]
@joemsak has this been updated?

**Comment by joemsak** [comment]
@Allicolyer yes, sorry, I should have notified about that!

**Comment by kmorton2017** [comment]
Amy and I talked. It should be the following: 

Background Checks:

Background checks are reports of your work and legal history. In the United States all mentors are required to complete and pass a background check in order to be  allowed and verified on our site.

In other countries and territories, we will randomly select mentors to provide references and legal certifications, and to submit to background checks where possible. If you are selected, we will contact you to complete this process. You must consent to this to be allowed and verified on our site.

Thank you for helping us keep our students safe.

**Comment by joemsak** [comment]
Okay thank you @kmorton2017 and @Allicolyer! This is on QA now!

**Comment by kmorton2017** [comment]
I see it live on QA. looks good.
