### ISSUE TITLE
A mentor enters their reference for an RA during sign up 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1615]
Mentors can enter a reference for an RA to use (if they choose) during sign up.

**Comment by adrichey** [comment]
We need to flesh out the acceptance criteria on this a bit. What information do we need to collect? Name/Email/Phone? Because we will be storing new data models and building a new UI, we will need this information up front.

Thanks in advance for looking into this and getting the developers that information! :)

**Comment by Allicolyer** [comment]
@kmorton2017 can you help answer Alan's question?

**Comment by adrichey** [comment]
I am going to mark this as blocked until we get more information on what data needs to be collected.

**Comment by Allicolyer** [comment]
Thanks Alan!

**Comment by ophelieh** [comment]
Hi @adrichey @Allicolyer ! Does that mean it's when mentors have been referenced by an RA? If so, could we extend that to people being able to choose the RA they see in their area (when we have multiple close to each other)? For example in Ireland, we have two RAs that are only 30 mins apart and they are planning on working together, but all the mentors and students only see one of the RAs although they were referenced by the other RA. Does that make sense?
