### ISSUE TITLE
RAs can mark mentors and students as inactive [20,13,1.54]

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1619]
Mentors marked as inactive will not show up in CSV reports for RAs and will not show up when students search for mentors on the platform. 

We are envisioning a manually checkbox to mark people as inactive, not an automatic system. Once you are marked as inactive...

1. You will not show up in CSV reports for participants
2. You can be marked active again at any point

Some other things that need to be discussed:

1. Do we want an active versus inactive filter for RAs and admins?

**Comment by Allicolyer** [comment]
We would ideally like to have this ready by January

**Comment by Allicolyer** [comment]
Conclusion: Still a future feature request. This would still help a few different RAs.

**Comment by stenington** [comment]
Ah, @kmorton2017 @ophelieh I didn't realize this ticket already starts to specify the behavior about what happens when you're marked inactive. 

A few comments on the initial description:

> You will not show up in CSV reports for participants
I would rather make a filter that defaults to active, but lets admins and RAs choose active, inactive, or either, and then have the CSV pay attention to that filter. I don't like the idea of the CSV export exporting something different than what you see on the screen.

> Do we want an active versus inactive filter for RAs and admins?
So then yes, this is the way I would do it. There would be a filter, and CSV exports would contain active users, inactive users, or both depending on how you had the filter set.

**Comment by hellafitz** [comment]
My version of this:

As an Admin or RA, I want to mark that a particular student or mentor is inactive when viewing their account, so that when I export data I can easily separate them out of my active participant in the resulting spreadsheet.

Inactive status should be visible to the Admin or RA when viewing the inactive user's account.
Inactive user accounts should be able to be toggled back to active (or at least not marked as inactive) by any Admin/RA user.
"Inactive" doesn't need to be the specific status visible, nor do words necessarily need to be used on the frontend.
A solution to this ticket should be prototyped and run by Admin / RA users for feedback.

**Comment by ophelieh** [comment]
That sounds perfect!

**Comment by hellafitz** [comment]
@rsgonzal will prototype what this looks like during it-07

**Comment by hellafitz** [comment]
@rsgonzal any update? We could also give this back to Alli and go full circle, depending on what you want to do.

**Comment by rsgonzal** [comment]
I'll work on a prototype this week.

**Comment by rsgonzal** [comment]
Started prototyping for students here: https://projects.invisionapp.com/freehand/document/5if8JR7Rk

Sent to program team for feedback and to see if this makes sense.

**Comment by rsgonzal** [comment]
Sent to 6 RAs for feedback.

**Comment by rsgonzal** [comment]
- Users are 'active' by default
- Add 'User Status' to more columns section

**Comment by hellafitz** [comment]
@rsgonzal to update

**Comment by rsgonzal** [comment]
- I think it should also apply to Judges (see below) and Teams (see below)
-  am wondering how it would work if we change a mentor who did not participate as a mentor (would be inactive) to a Judge. Would you automatically make them active or would the RA need to do this themselves. It would make it easiest if the system did this so there would be no need to have the RA remember. Making this field available for judges would be appreciated. And it would be great is only the Active judges be available to choose from for matching Judges to teams.
- And as far as teams, it would be great if we could mark them as inactive too. We have teams that register, but drop at some point. Usually within the first month, but some later. Or if all the team's girls are inactive, then the team should be inactive. This could be something the systems does!
- I think for this feature to be useful it is necessary that the RAs could also edit the status from a list view that we see in the "participants"
