### ISSUE TITLE
Home page for mentor dashboard is the find a team page

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1673]
After signing up i get brougt to the find a team page. 

![uploads/3104aae2-72a6-49a0-83ff-cb44cc88782a/Screen Shot 2018-09-07 at 3.10.00 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3104aae2-72a6-49a0-83ff-cb44cc88782a%2FScreen+Shot+2018-09-07+at+3.10.00+PM.png)

It seems that the home page for the mentor dashboard is this:
https://technovation-qa.herokuapp.com/mentor/dashboard#/find-team

**Comment by Allicolyer** [comment]
Also I found it odd that the student dashboard takes me to my parental consent form when I log in: https://technovation-qa.herokuapp.com/student/dashboard#/parental-consent

**Comment by kmorton2017** [comment]
Alli, I think that may be a good thing if it takes the student to that page with parental consent so that they dont' forget that they need to get it signed. 

As for the mentors, I'm wondering if it may be possible to list the teams that they have requested to join? As a user I may forget which teams I have requested to join.
