### ISSUE TITLE
Checkmark when you successfully upload business plan and it is red --- make it green

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1719]
As a student--

When I try to upload a business plan
I get a green check mark once it is uploaded

As a mentor --

When I try to upload a business plan
I get a green check mark once it is uploaded

**Comment by amyiridescent** [comment]
It works. For student & mentor. 

![uploads/65301326-63e7-4e0c-8c84-c5516215fd46/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F65301326-63e7-4e0c-8c84-c5516215fd46%2Fimage.png)

So when I am on a team as a mentor with no students, it doesn't let me upload a business plan. (Like it should since it doesn't know if you are in junior or senior division.) That message doesn't come until you try to upload the business plan. It had no problem submitting code check etc. I assume that is fine but I just wanted to note that here since in the past we have had teams submit with no students on a team.  

![uploads/30b2fba1-4105-4857-b27a-1a0d519bc509/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F30b2fba1-4105-4857-b27a-1a0d519bc509%2Fimage.png)

**Comment by joemsak** [comment]
@amyiridescent it is true, a mentor can submit without students on the team, but without students we can't know the division, so it's the same as not being required to upload the business plan. they also cannot actually publish for judging until they have students with parental permission on the team. at this point, the submission would check if it needs the business plan or not, based on the student's age

**Comment by joemsak** [comment]
the only scope of this card is the check mark when you uploaded the file: was it green?

**Comment by amyiridescent** [comment]
Yes Sir! Closing the ticket now.
