### ISSUE TITLE
Code checklist counter updates when I enter text for description 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1720]
As a student

When I check a box on the code checklist
The counter should not update until I've entered a description

As a mentor 

When I check a box on the code checklist
The counter should not update until I've entered a description

**Comment by ophelieh** [comment]
As a mentor - works great. It won't let me save the page until I have entered a description for each. 

As a student - I entered an extra mobile feature and got some extra points. I saved it and went back, it still shows the extra points even though it doesn't count them - I still have 7/10. 


![uploads/229afa29-29d4-4d36-96b6-a72fe038cc9a/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F229afa29-29d4-4d36-96b6-a72fe038cc9a%2Fimage.png)

**Comment by kmorton2017** [comment]
As a student, it did not allow me to save my checklist until i entered a description. It did not count my points until i entered a description.

**Comment by adrichey** [comment]
@ophelieh and @kmorton2017 I will be working on those issues now.

**Comment by adrichey** [comment]
@ophelieh and @kmorton2017 this is once again ready for retesting. Please note that the fix is on the front-end, so if you use the same accounts you tested with last time, you will need to do the following:

1. Delete the description from each input box, and then uncheck the box.
2. Save the form.
3. Test the form as you would normally.

Thanks!

**Comment by joemsak** [comment]
I was able to confirm that the points add up correctly - I signed up as a new student on a new team with a new submission

**Comment by ophelieh** [comment]
Hi! I noticed that if I select one of the databases options (local or external), I then cannot change my choice - the other choice becomes unclickable unless I save the checklist and come back to it. This one makes sense. 

It does the same for mobile features, but it's possible that some team have more than one feature (even if they only get points for one) or am I wrong? 

Otherwise, the points add up correctly and everything seems to work fine.

**Comment by joemsak** [comment]
@ophelieh if you mean that the other checkboxes are disabled, but you could still uncheck your choice and choose a new one, yes that is by design: there is a maximum amount of points they can earn, there is no need for them to select everything that they used, only enough to get maximum points

**Comment by ophelieh** [comment]
Noted. However, if I select an option then unselect it, I am unable to select anything else. The other checkboxes are still disabled for both 'Database Features' and 'Mobile Features'. Basically, even after unselecting an option, that is the only one I can reselect. 



![uploads/7ef79d6a-7184-43f5-9835-6de957ccaa74/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7ef79d6a-7184-43f5-9835-6de957ccaa74%2Fimage.png)

**Comment by joemsak** [comment]
@ophelieh okay thank you for clarifying. you are right, that is a defect preventing the acceptance of this card. I will work on it today. Thanks again!
