### ISSUE TITLE
Code Checklist Point Counter for Pictures of Process

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1721]
As a student
With a submission
That already has two uploaded screenshots
When I go to edit my code checklist
And I attach the two pictures of my process (before pressing save)
Then I should see the counter award 3 out of 3 points

As a mentor
With a submission
That already has two uploaded screenshots
When I go to edit my code checklist
And I attach the two pictures of my process (before pressing save)
Then I should see the counter award 3 out of 3 points

**Comment by amyiridescent** [comment]
I am not sure if I am following instructions well here. So I am awarded the 3 out of 3 points (from the total of 10 points available under "code check section", when I add two picture to the "pictures of your process" category. I do see that. As long as two screen shoots were already uploaded. 

![uploads/b55bac11-6a89-494d-ae13-e5edb4bbf654/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb55bac11-6a89-494d-ae13-e5edb4bbf654%2Fimage.png)

If I upload the screenshoots AFTER I started the "code checklist", the score does not get updated on the dashboard. I need to click back into "code checklist" before it gets updated.  


![uploads/ff1ba4a2-b33b-48bb-a081-d51cacb3d730/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fff1ba4a2-b33b-48bb-a081-d51cacb3d730%2Fimage.png)

(For both mentor and student)

**Comment by joemsak** [comment]
good looking out @amyiridescent you were right to approach the test from another angle, and we can fix this too.

**Comment by amyiridescent** [comment]
Well I didn't do it on purpose. I didn't read Alli's instructions careful and ended up having to do it from both angles. And that is how I found the difference. hehe :)

**Comment by joemsak** [comment]
@amyiridescent I checked into this and it seems like your issue is that the points do not update dynamically on the left-side menu when you upload screenshots. We didn't design the code to ever do that, updating it dynamically has not been a requirement as of yet, and it does update the 3 points when you load any page that has that menu on it. We'll have to consider this card passing the original acceptance criteria, and I wouldn't recommend prioritizing making the left-side submission menu update dynamically at any time soon

**Comment by amyiridescent** [comment]
Sounds perfectly reasonable to me. We can think about dynamic update (?) features next year. Closing the ticket now.
