### ISSUE TITLE
Submission - Development Platform - Data is not saving except for App inventor

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#1776]
**Describe the bug**
When choosing a development platform, except for App Inventor, you cannot save the data. 

**To Reproduce**
1. Go to 'Submission page
2. Click on 'Development Platform'
3. Scroll down to either selection other than App Inventor
4. Click on 'Save this development platform selection'
5. See error

**Expected behavior**
When clicking the save button, it saves my selection. 

**Screenshots**
Link to video showing error - https://drive.google.com/file/d/1eUat4-owdqDYxhP5HH-TyolP_L6TpS12/view 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version 69.0.3497.100 

**Additional context**
The rest of the page is acting up as well. See other bug about text on the banner.

**Comment by joemsak** [comment]
hi @ophelieh I currently have this bug marked as a priority 1 (1 is the highest) because it is a potentially "Confusing UX" that potentially affects "more than 10% of users" - however I may down grade the priority because I think the issue is that you used to have App Inventor (or thunkable?) selected with the extra fields filled out. Now that you're trying to change it, it's failing due to trying to validate those fields.  Is that right? Did you once have it filled out for App Inventor?

If so, obviously that's still a bad bug in that case, however I'm not sure it would be a very likely thing that will happen, which means it's harder to know how many users it could affect, but if we give a generous guess of 1-5% of users, that puts as bug priority 3.

If I am not right about you having it filled out originally as App Inventor (or thunkable?) with the extra fields and then trying to change it (without erasing those fields) then that is definitely a priority 1, but I wasn't able to reproduce the bug with the steps given, so my guess is that it's the case I outlined above.

If I'm correct about the edge-case here being that you changed from App Inventor (or thunkable?) originally, is my explanation and downgrading of the priority acceptable to you? Thank you for your time!

**Comment by ophelieh** [comment]
I believe you are correct, it is possible that I had previously filled it out. I am fine downgrading it to a priority 3. 

Thank you! :)

**Comment by joemsak** [comment]
Thank you for your understanding on the nature of the issue, @ophelieh! I am sure we will still get to this bug, as we are on schedule and don't have many bugs :)

**Comment by ophelieh** [comment]
Awesome! :)

**Comment by adrichey** [comment]
@Allicolyer I am going to go ahead and pull this ticket into the sprint since I am done with my current workload until we have the location form discussion this afternoon.

**Comment by adrichey** [comment]
@ophelieh I cannot replicate this issue anymore. Can you please take a look again and let me know if it is still an issue? If you can replicate this problem, can you list the steps you took in a comment? Thanks!

**Comment by Allicolyer** [comment]
@ophelieh can you replicate this error? If not, I think we can close this card.

**Comment by ophelieh** [comment]
Seems to be working now. :)
