### ISSUE TITLE
Returning (and already logged in) users are not marked for the current season [13,8,1.6]

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1780]
**Describe the bug**
If a user is still logged in before the new season starts (Oct 1, 2019 for example), then their account is not marked for the new season, as that happens during the SignIn procedure

**To Reproduce**
1. As a developer, set the season switch date to a future date
2. Log in as an existing user
3. Change the season date to today or the past
4. Revisit the user's dashboard, or whatever
5. Verify the account is still not marked for the current season

**Expected behavior**
The user should get marked for the season - either the cookies should reset each year, or a procedure should check on their season registration every initial page visit to the site

**Screenshots**
nah

**Desktop (please complete the following information):**
all environments affected

**Smartphone (please complete the following information):**
all environments affected

**Additional context**
N/A

**Comment by Allicolyer** [comment]
Hey @adrichey so I wonder how many people are still logged in and haven't had to re-sign in. Here are some options. 

1. Would it make sense to reset the cookies for everyone at some point? Right now many people are registering and it be frustrating to log them out. We could do something like this once registration is closed.
2. Could we set an expiration date for the cookies so that in 2 weeks people will be forced to log out?

If this is affecting a lot of users, it might be urgent. RAs and admins need accurate numbers.

**Comment by joemsak** [comment]
@adrichey on production you configure a new random token for the ENV var of the cookie you want to invalidate

https://github.com/Iridescent-CM/technovation-app/blob/qa/app/constants/cookie_names.rb#L3

`heroku config:set COOKIES_AUTH_TOKEN=random-string-here`

Easy way to get a random string:

`rails runner "puts SecureRandom.hex(12)"` - or whatever the current length of the ENV vars are

On development, the .env file has friendly names for development purposes - the choice to obfuscate the cookie names in production was maybe overly paranoid, but that level of security was the reason there.

**Comment by adrichey** [comment]
@joemsak Thank you for saving me some time digging! You rock.

**Comment by hellafitz** [comment]
- When does the platform consider the season to have started? Oct 1st?
- Reset of cookies needs to happen just before season starts. 
- Part of this ticket is to spec out options

**Comment by hellafitz** [comment]
Updated scope: Loosely spec out options and make a rec.

**Comment by stenington** [comment]
I checked on the expiration of the auth cookie locally, and it was set to approximately 20 years from now, so I guess we allow people to stay logged in for a really long time. 

I feel like the "Content & Settings" portion of the admin gives our admins the feeling that they control the season, but hidden details like this still exist that can cause problems if admin activity in the settings isn't coordinated with additional behind-the-scenes work. 

So this ticket might need a little more framing. Are we trying to figure out how to give admins more power to start the season whenever they want to? Or are we automating the behind-the-scenes work but leaving it behind the scenes?

Some options we can consider:
* expose the invisible dates the platform uses and make them configurable by admins, giving admins both the power to e.g. start a season, but also to potentially shoot themselves in the foot if they don't understand the ramifications of using these controls
* give them something like a "require log in" button to click that rotates auth cookies, although admins will still need to remember to click that when they want the season to change
* or a "change seasons" button, possibly with the option to name it as well, that rotates auth cookies and uses the new season name (instead of date-based rollover)
* assign cookies an expiration date of "the start of the next season" although that means we need to know that a year in advance
* have the platform append the current season name to the cookie token so when the season automatically rolls over, everyone has to log back in

**Comment by stenington** [comment]
@rsgonzal votes for the last option, and I agree it's the easiest to take forward without addressing a slightly thornier UX question.

**Comment by stenington** [comment]
@hellafitz: Roxana and I discussed this one, her gut feeling was that I could do the last option (have everyone log back in when the season changes, but not mess with the season change mechanism for now) but that trying to open a discussion about how much power belongs in the admin vs. in the hands of developers probably wouldn't be welcomed right now, and the program team will likely lean on us for managing the season controls anyway.

**Comment by rsgonzal** [comment]
I changed the month date to 9. the platform logged me out. I think it's doing what it's supposed to.

**Comment by stenington** [comment]
Cool! I can confirm you're marked in staging as participating in the 2020 season: 
![Screen Shot 2019-09-13 at 12 24 26 PM](https://user-images.githubusercontent.com/55319/64878417-795e5180-d621-11e9-99b3-4be09b7db871.png)

**Comment by rsgonzal** [comment]
oh perfect! I asked devin to log in and i see she is marked as well.
