### ISSUE TITLE
Admins can filter mentors who have not completed the mentor training

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1793]
Acceptance Criteria:

As an admin
I can go to the participants page
I can filter the search results for mentors based on who has completed the mentor training

As an RA
I can go to the participants page
I can filter mentors based on who has completed the mentor training

**Comment by joemsak** [comment]
@Allicolyer would you like this functionality to exist for RAs as well?

Should mentors who are not required to take the training be included as being "complete" or should there be a separate option to filter mentors not required to take the training?

I'm noticing that we are starting to have a bit more back and forth over the AC now, concerning common use cases that might be captured in these cards if we take a bit more time to think more holistically through the requests. 

Maybe it's because we are writing new cards outside of a formal planning meeting. What do you think? Would it be better if we hold off on new cards until we can work out more use cases for the AC in a planning meeting, or could I ask you to take a bit more time to think through the various use cases for each card? Thank you!

**Comment by joemsak** [comment]
Oh sorry, I got the original version of your comment that ended with "I think" and I completely misinterpreted you. Sorry about that

So, I am sure it's okay with you to work on these cards now, and it's okay with me too, but what I'm asking is: if we can take some time together to write the AC out to consider some of the more common use cases? I'd like to avoid us going back and forth in comments over some of the basic points. Does that work for you, or do you have another preference? Please let me know what you'd like to do. Thank you!

**Comment by Allicolyer** [comment]
Sure that works for me. Thanks for catching that these cards should also apply for RAs.

Do you want to discuss this card further or just write out AC together for new features? I don't think we will be adding any other new cards before the sprint.

**Comment by joemsak** [comment]
Ah, okay, I think I understand you better now. Thanks for providing some clarification into your process.

For these cards, it's no trouble, and I would like to offer my recommendation that if we have a future period of adding cards outside of a regular sprint planning meeting, that we consider an AC writing meeting for such cards. Let me know if you like that idea, or if you have another preference. Thanks Alli!

**Comment by adrichey** [comment]
This is ready for testing!

**Comment by Allicolyer** [comment]
this works!
