### ISSUE TITLE
Deleting Participant

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1797]
**Describe the bug**

A student was having trouble resetting their password and obtaining parental consent. She created a new account because she was having difficulties. She requested that I delete her old account.

As an admin, I saw that there were 2 accounts with her email. One did not have parental consent, and the other did, but did not have any parent information. I was able to successfully delete one student account. I was not able to delete the other student account (has parental consent but no parent information).

More detail and specifics on the account can be found here: https://docs.google.com/document/d/1O3gT9NdZm8pn8966ruHmAGJvqOLJqu5msXQOGM09JPM/edit?usp=sharing

**To Reproduce**
Steps to reproduce the behavior: See the above Google Doc for more details.

**Desktop (please complete the following information):**
 - OS X El Capitan, Version 10.11.6
 - Chrome

**Comment by Allicolyer** [comment]
I think this has signs of being corrupt account. @adrichey I don't think we necessarily need to investigate this right now, but does anything quick come to mind?

**Comment by adrichey** [comment]
I looked into this and it looks like bad data. She definitely has two accounts. They both were created mere milliseconds from one another, so my guess is some server issue caused two accounts to be created, with only one of them having a student profile. I think it might be good to delete the account without the student profile. I will have to do that manually since it is a corrupted account. Let me know how to proceed and I can assist on this.

**Comment by kmorton2017** [comment]
i responded to this over slack
