### ISSUE TITLE
RAs cannot select teams & judges for their event

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1804]
**Describe the bug**
When I create an event as an RA, and I go to manage teams or judges, trying to pull up the list of teams / judges to choose just spins. It appears that the server is having a 404 error.

**To Reproduce**
1. Login as an RA
2. Create a new event
3. Go to Manage Teams or Judges
4. Click to add teams
5. See that it spins / web developer console says 404 not found error

**Expected behavior**
I expected a list of teams or judges to appear

**Additional context**
This needs to be fixed immediately to enable exploratory QA

**Comment by joemsak** [comment]
@adrichey just a quick update for you, this is not a 500 server error, the javascript is not executing properly. Do you want to screenshare and look at it together? Let me know what you prefer. Thanks!

**Comment by adrichey** [comment]
I will take another look at this as time allows today then. Can you please put the details of the error and what you think the issue is in this thread for tracking? Thanks!

**Comment by joemsak** [comment]
Sure! Thank you, I really appreciate that. I'd hate to leave you on your own, mostly due to how poorly I wrote this code, so if you do feel like a screensharing session would be more productive please don't hesitate to ask.

Anyway, the main starting point of the bug seems to be with this bit:

https://github.com/Iridescent-CM/technovation-app/blob/qa/app/javascript/ra/events/EventsTable.vue#L219

It apparently isn't triggering when it should, so the event object doesn't get that fetchTeams/fetchJudgesUrlRoot property, and so when you go to manage teams/judges you'll see the rails server is being asked for a GET on /regional_ambassadors/undefined

I haven't been able to figure out more beyond that yet, hence why I was hoping to get your help.

Thanks again and please let me know if i can do more to be helpful to you.

**Comment by adrichey** [comment]
@joemsak I have fixed the front-end issue of this ticket in branch `1804-error-when-managing-events`. I have created the following pull request for it: https://github.com/Iridescent-CM/technovation-app/pull/1827

The 500 error remains, even with the correct JSON endpoints in there due to the `AttendeesSerializer` not getting an ID attribute needed for the fastJSON API. Can you please take another crack at it in that `1804-error-when-managing-events` branch and then let me know once you have made progress? Thanks!

Attaching screenshots so you can see the results of the errors.
![screen shot 2018-11-07 at 12 32 48 pm 2](https://user-images.githubusercontent.com/1534554/48152641-07dba700-e28a-11e8-91e1-2cc0e8c5696f.png)
![screen shot 2018-11-07 at 12 32 52 pm 2](https://user-images.githubusercontent.com/1534554/48152642-08743d80-e28a-11e8-9d30-2f1f05cedc2a.png)

**Comment by adrichey** [comment]
@Allicolyer The 500 errors we were receiving when attempting to manage teams and judges for an event should now be alleviated. This is ready for testing on QA. Once this is tested and closed, we should be able to go through the events section again for exploratory QA. Thanks!

**Comment by Allicolyer** [comment]
Great thanks Alan and Joe!
