### ISSUE TITLE
Judging a submission made with thunkable

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1811]
As a judge
When I am scoring a submission
Which has its Development Platform set to "Thunkable"
When I view the 'Source Code' portion
Then I should see a link to the Thunkable project
And it should open in a new window

**Comment by adrichey** [comment]
This is now ready for QA testing! :slightly_smiling_face:

**Comment by Allicolyer** [comment]
@nickiredescent could you test this card?

Here is how to do it:

Go to https://technovation-qa.herokuapp.com/
Log in as a student who has a team: student@student.com
For their submission, choose Thunkable as their submission platform
Put this link for source code: https://x.thunkable.com/copy/1662094357d248e0c5c5bba5bc5d64b4

Now log in as an admin: admin@admin.com
Go to the "Content & Settings" menu 
Turn quarterfinals judging on

Log in as a virtual judge: judge@judge.com
Start judging submission and when you get to the team Student Union, confirm that you are able to click on the source code. 
It should bring you to a new window with Thunkable's website. Thunkable should ask you to log in.
Once you have logged in, you should see a screen with some buttons 


Troubleshooting Tips:

If you cannot edit your submission as a student, you will need to log in as an admin, and change the settings so that submissions are editable. You can find this option in the content & settings menu.

Thank you! Please let me know if you have any questions.

**Comment by nickiredescent** [comment]
Tested and works!

**Comment by Allicolyer** [comment]
Great! Thanks @nickiredescent!
