### ISSUE TITLE
School or company name filter for the participants page

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1833]
**Is your feature request related to a problem? Please describe.**
Very often admins need to report numbers based on how many mentors or judges signed up from a certain company.

**Describe the solution you'd like**
Create a filter on the participant pages that allows admins to filter search results based what participants have in their "School or company name"  field. This filter should be a dropdown that allows admins to select one of company options that is available at sign up or type in their own. 

**Acceptance Criteria:**

As an admin
I can go to the participants page
I can filter mentors and judges based on their "company or school name"
I can select an option from a dropdown menu or type in my own
The search results will be filtered based on I entered

**Comment by Allicolyer** [comment]
@joemsak I talked to Katie and Ophelie yesterday and this is one of the needs they outlined for an admin feature.

**Comment by adrichey** [comment]
Work for this is currently in the following pull request: #1881. Once approved I will merge that in and move this ticket to QA.

**Comment by adrichey** [comment]
This is now ready for testing. :raised_hands:

**Comment by kmorton2017** [comment]
This is performing as expected. I confirm that i'm able to search for a company. To clarify, I see two different versions of Iridescent. One with a capital and one with a lowercase. 

When we want to search for a specific company, we will need to select each variation (Ie Adobe Systems Ltd., Adobe India) etc to make sure all results come up.

**Comment by adrichey** [comment]
That is correct @kmorton2017. The filter pulls every school/company that exists in the database. Unfortunately, we cannot control what people type into that field, so we may have to select multiple schools and companies in order to get a full picture of the data.

**Comment by kmorton2017** [comment]
got it! that's what i thought. also you may hate me but i have a few more questions!

1) can we make sure that the mentor company search feature is available for RA's as well? 

2)  is it possible to have this feature so that you can search for a student's school? I am just envisioning the RA's who may use the "school" feature for students more often than we need it as HQ admin. They may ask why you can't search for a student's school but you can search for a mentor's company. (just thought of this). let me know if this is an appropriate place to have this question^.

**Comment by adrichey** [comment]
@kmorton2017 No hate on this end haha. The feature is already available for RA's, so you are good to go there! I think if we want to implement this feature for student schools we can, but I would rather us put that into a new issue ticket since it is outside of the acceptance criteria for this issue.

**Comment by kmorton2017** [comment]
@alan this card is good to go. I wiil make a new card for students and schools.

**Comment by Allicolyer** [comment]
Thank you @kmorton2017 and @adrichey !
