### ISSUE TITLE
Add CSV Column options to participants page

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1834]
**Is your feature request related to a problem? Please describe.**
Admins would like these CSV column options added to the participants search page

**CSV Columns to add**
- Date that on-boarding was fully completed (signed consent form, completed training, and background check cleared)
- Returning participant (yes or no field)

**Acceptance Criteria:**

As an admin
I can go to the participants page
I can add a column to the CSV report called "returning?"
I can download a CSV report that has a "yes" or "no" value for each participant in the "returning?" column 

As an admin
I can go to the participants page
I can add a column to the CSV report called "Onboarded date"
I can download a CSV report that has a a date value for each participant in the "Onboarded date" column

**Comment by adrichey** [comment]
@Allicolyer I have a couple of questions on this. For the onboarding date, are we only covering mentors, or would you want the logic to cover students as well? If so, what pieces of data dictate when a student is onboarded (i.e. parental consent signed and email validated)?

**Comment by adrichey** [comment]
@Allicolyer because we don't store the date users were onboarded in the database, this date will only be populated for newly onboarded mentors when this functionality is completed. Is that going to be useful? It seems like we won't have an accurate view of onboarding dates since we will be starting from whenever this work goes to production. Tagging @joemsak in case I am missing something here.

In any case, I have completed the "Returning?" CSV column functionality, so that was doable. Thanks!

**Comment by adrichey** [comment]
Developer note: I have started work for this in the branch `add-csv-columns-for-participants`. I will continue work on this once we get feedback and this becomes unblocked.

**Comment by adrichey** [comment]
Thank you @Allicolyer!

**Comment by adrichey** [comment]
**Update:** After discussing this ticket with @Allicolyer, @kmorton2017, and @ophelieh this morning, we have decided that the second "Onboarded date" CSV column is not needed since we can already filter using the following filters in the admin UI:
- Consent waiver (mentors only)
- Background check (mentors only)
- Mentor training (mentors only)
So we only need to test returning participant filter for the acceptance criteria of this ticket to be met. Please reach out for any questions while testing.

**Comment by KaiLokken** [comment]
Tested it. The CSV column for "Returning?" with "yes" or "no" was included in csv.

**Comment by Allicolyer** [comment]
Thank you @KaiLokken !
