### ISSUE TITLE
Downloading parental consent form

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#1882]
**Describe the bug**
Students are having issues downloading the parental consent form on their dashboard. When you go to "Download the permission form" you get this screen (attached)

**To Reproduce**
1. Login as daniela.bodiu.06@gmail.com
2. Click on download the permission form
3. See "this page cannot be found"

**Expected behavior**
I would expect to be able to download the permission form. 
![screen shot 2018-12-05 at 5 20 21 pm](https://user-images.githubusercontent.com/32206427/49554677-fbab2f80-f8b1-11e8-8fdd-2d313fc9011c.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: El Capitan 10.11.6
 - Chrome 
 - Version 70.0.3538.110 

**Label**
You MUST use the label menu to add 'bug' and '0 - To discuss' as a label
(do *not* choose a bug priority label, devs will do that according to the Defect Priority matrix)

**Comment by adrichey** [comment]
The issue was that the Parental Consent Form on Zendesk was updated to a new version and the dev team was not notified of the change (See https://iridescentsupport.zendesk.com/hc/en-us/articles/115002731034-How-do-I-submit-the-consent-forms-). Therefore the link broke when the old form was removed. I have since updated it to a newer version and we should be good to go! This is ready for testing! Thanks for finding this so quickly @kmorton2017.

**Comment by kmorton2017** [comment]
Works as expected!

**Comment by adrichey** [comment]
Awesome! Since this wasn't a code change, but an environment variable change, I have rolled the solution out to production as well now that the fix was tested. @Allicolyer this ticket can be closed whenever convenient. Thanks for jumping on that QA so quickly @kmorton2017, you rock!
