### ISSUE TITLE
Unable to add student

### ISSUE THREAD

**Issue by nickiredescent** [Iridescent-CM/technovation-app#1893]
Hi guys,

Got a zendesk support ticket. I've cc'ed Alli through Zendesk.
Sakshi Bhatnagar (sakshibhtngr1989@gmail.com) is a mentor trying to add Sneha Sharma (sanjay.tandi10@gmail.com) onto team"Raghav Global School,Noida". 
As far as I can tell, Sneha has completed all necessary steps to complete her profile and has even accepted the team invitation. However, she is still listed as pending when I view the team page as an admin and as her mentor. When logged in as Sneha, her submission page says she needs to do some more steps, but does not say what those steps are. I've attached screenshots. 

Thanks!
![sneha bug](https://user-images.githubusercontent.com/45576078/49977148-0b51f600-fefa-11e8-8db0-8e03f6d9f4d7.png)
![sneha profile](https://user-images.githubusercontent.com/45576078/49977149-0b51f600-fefa-11e8-8a62-4fdc1265307d.png)
![sneha pending](https://user-images.githubusercontent.com/45576078/49977169-2290e380-fefa-11e8-966a-568281ca12b0.png)

**Comment by adrichey** [comment]
I am looking into this right now. I will update this ticket as soon as I know more. Thanks @nickiredescent!

**Comment by adrichey** [comment]
@nickiredescent and @Allicolyer, I dug into this this morning and came across the following account: http://localhost:3000/admin/participants/63600#/

This account has the same email address as the parent who signed the parental consent for sanjay.tandi10@gmail.com. The accounts are _very_ similar so I think we may have a student who signed their own parental consent. This is not a platform problem as I looked into the code and there is a safeguard that reacts this way in this particular case.

One thing I can do in order to make it more apparent is to display the error on their dashboard. I can word it like, "Your parental consent form was signed by another student account already in use" or something. But I will want the program team to chime in here. Ultimately, this case shouldn't come up that much, so I think we just need to get to the bottom of why there are two accounts created with the same name and why one signed the parental consent for the other.

Let me know if there is anything else that I can do for this. I am going to move on to other tickets in the mean time. 🙂

**Comment by Allicolyer** [comment]
@adrichey ... Interesting. I wonder if this is due to the parent trying to create an account for the student. Instead, could we prevent people from entering an email that is already in use for another account?

**Comment by adrichey** [comment]
Sure. So when the student attempts to send the consent form to their parent via email, we should check to see that the email address isn't currently in the system for another account, and return an error message if does. Is that correct? If so, I can work on that solution for this ticket.

**Comment by KaiLokken** [comment]
@kmorton2017 @ophelieh 
What are your thoughts??

**Comment by ophelieh** [comment]
It has happened multiple times that parents create an account for their daughter and then the daughter also creates an account. 

And @adrichey I do like that idea! Checking that the parent email entered is not currently in use in the system. 

Thank you all!

**Comment by Allicolyer** [comment]
Great glad for the progress here! 

In the meantime, @ophelieh what should we do for this student? Should we delete her consent form on file and ask her to sign a new one?

**Comment by adrichey** [comment]
@Allicolyer I have created ticket #1917 to address this issue going forward, so whatever we do for this ticket can be done for this individual account.

**Comment by ophelieh** [comment]
@Allicolyer I think that might be the best way to proceed. @nickiredescent could you reach out to the student and let them know we are going to delete the consent form and need them to redo the process. 

Thank you!

**Comment by adrichey** [comment]
@Allicolyer and @nickiredescent I have removed the parental consent for Sneha Sharma. They will need to fill out their parental information again and send the form to their parent so they can sign it again. Here is the information they probably want to use as these values were found in the parental consent in the database:

Name: Anurag Sharma
Email: Anurag.sharma4306@gmail.com

Once Nick has reached out to them, I believe we can close this ticket since no code changes have taken place. Thanks!
