### ISSUE TITLE
Selecting events is hidden for both students and mentors on their dashboards

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1897]
This card might get split into multiple cards

**Describe the bug**
When admins turn on events, there is no change in the student or mentors' dashboard to show that they can now select events. However, they can click on judging and they will be able to see the event they are attending or see the option to select an event.

**To Reproduce**
1. Turn on Events as an Admin
2. Log in as a team who has an event in their area to attend
3. Click on "Judging" on the sidebar even though it is grayed out
4. You can now select an event 

**Expected behavior**
I would expect this menu to be much easier to find and pop up on my dashboard. It is hidden and not user friendly.

![screen shot 2018-12-17 at 11 49 31 am](https://user-images.githubusercontent.com/11083917/50111539-d7284f00-01f1-11e9-8390-bf633c6a5b53.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 70

**Comment by adrichey** [comment]
@Allicolyer I have been digging into this issue, and I think we should talk about the fix in more detail. So right now, Judging and Regional Live Events are the the same interface in the code, despite having two menu items. So my solution would be to rename "Judging" to "Regional Pitch Events" and consolidating the menu items into one. From here, I would make "Regional Pitch Events" selectable if events are turned on in the Admin so that it doesn't appear to be greyed out. Thoughts?

**Comment by adrichey** [comment]
**Update:** I spoke to @Allicolyer about this earlier this week and we decided that my solution above in the comments makes sense with a couple of tweaks. So here is what the final solution should look like:
- Rename "Judging" to "Pitching Events" and consolidating the menu items into one.
- Make "Pitching Events" enabled only if events are turned on in the Admin UI using the "Selecting regional pitch events allowed" checkbox so that it doesn't appear to be greyed out. Otherwise, display some helper text stating that this will be available at a later date, similar to what we have now.

**Comment by adrichey** [comment]
This is now ready for testing! :slightly_smiling_face:

**Comment by nickiredescent** [comment]
Tested:
As a student on a team attending an event, I can click "Pitching Events" when it is enabled by an admin. "Pitching Events" is grayed out and a pop up that says "This feature will open later in the Season" shows when events are disabled by an admin.

![1897 - 1](https://user-images.githubusercontent.com/45576078/50717966-469a9d00-1040-11e9-87cc-6ddc1c679878.png)
![1897 - 2](https://user-images.githubusercontent.com/45576078/50717963-469a9d00-1040-11e9-8bfa-a24abc426b6e.png)
![1897 - 3](https://user-images.githubusercontent.com/45576078/50718067-f839ce00-1040-11e9-8666-419bbc6d40e1.png)
