### ISSUE TITLE
Judges have the same bug when being assigned to events as teams did with card #1853

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1899]
**Describe the bug**
Judges have the same bug when being assigned to events as teams did with card #1853. The same behavior happens.

**Comment by adrichey** [comment]
**For full context**

**Describe the bug**
The menu for selecting teams is a bit confusing, it does not update after clicking "save selected teams". 

**To Reproduce**
Steps to reproduce the behavior:
1. Log in as an RA
2. Create an event
3. Add some judges to your event (judges should be in the same region as the event)
4. Click "Save changes"
5. Click "Add Judges"
6. Observe that this menu has not changed since you clicked "Save changes"

**Expected behavior**
I would expect that clicking "Save changes" would update the menu so that those teams no longer appear on the list and can't be deselected. If you refresh the page the attendees no longer appear in the list, so this would bring the functionality in line with that.

**Screenshots (Note, this is for teams, but it still applies here)**
![selecting teams](https://user-images.githubusercontent.com/11083917/48725704-d2b44a80-ebe1-11e8-9bde-f1a07fcf381e.gif)

**Comment by adrichey** [comment]
This is now ready for testing!

**Comment by ophelieh** [comment]
@nickiredescent @KaiLokken Could you test this today?

**Comment by nickiredescent** [comment]
Card has been tested.
The add judges menu saves and updates upon clicking "Save Changes".

**Comment by KaiLokken** [comment]
I just tested, too. It saved the updates
