### ISSUE TITLE
Remove Virtual Judge Committee Checkbox from Judge Onboarding Survey

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1909]
Remove the option to join the virtual judge committee from the required judge on-boarding survey

**Comment by adrichey** [comment]
@kmorton2017 @ophelieh @Allicolyer Just to confirm, we aren't using this data in any way, correct? I know we had talked about that in the past, but I want to double check before committing to this change. If we aren't using the information in any way, I am going to remove the column from the database. This means we won't know who signed up as a virtual judge previously. Is that okay? We won't be able to query on that information, or view it after I make that change.

**Comment by adrichey** [comment]
Marking as blocked until I get a response on this.

**Comment by Allicolyer** [comment]
Yes I believe we discussed that we are not using this data for anything and are comfortable removing it. @kmorton2017 can you double confirm?

**Comment by adrichey** [comment]
@kmorton2017 Can you take a look at this and provide your final yay or nay on this today or tomorrow so that I can finish this ticket up this week? Thanks!

**Comment by Allicolyer** [comment]
@kmorton2017 said it's cool to delete!

**Comment by adrichey** [comment]
This is now ready for testing.

**Comment by adrichey** [comment]
@Allicolyer can we go ahead and close this ticket since we saw this work while doing exploratory QA earlier?

**Comment by nickiredescent** [comment]
Tested, I think it works? My uncertainty is more due to my lack of understanding than anything else.
There is no option to join a virtual judging committee during the required on-boarding survey. Upon completing the on-boarding survey as a new judge and the rest of the on-boarding process, I was immediately able to start virtually judging. 

Questions:
From the wording on this card, I was under the impression I would have to opt-in in order to start virtually judging. Is the act of being able to virtually judge the same as being on a "virtual judging committee"?

**Comment by adrichey** [comment]
@nickiredescent the checkbox being removed is the main thing. Essentially, this functionality wasn't being used. I had Katie and Ophelie confirm this in a meeting with Alli last week, and the decision was made to just remove it as it wasn't fully realized. So there really isn't much more to test. Thanks!

**Comment by adrichey** [comment]
Closing the ticket as there is nothing else to check on this.
