### ISSUE TITLE
Barcelona, Spain users are being saved at Barcelona, Connecticut, USA

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1924]
**Created from research done on #1922**

**Describe the bug**
Right now various accounts that enter their location as Barcelona, Catalonia, Spain are being saved to the database as Barcelona, Connecticut, USA.

**To Reproduce**
1. Log in as an Admin
2. In the Admin dashboard, click Participants
3. Pull up any student or mentor account
4. Click Edit Location
5. Fill out the fields as `City: Barcelona`, `State: Catalonia`, `Country: Barcelona`
6. Click Next
7. Notice that state has changed incorrectly to Connecticut
8. Click Confirm
9. Observe that location is now set as Barcelona, Connecticut, United States

**Expected behavior**
In step 7 above, the address still represents the state of Catalonia/Catalunya in Spain.
In step 9 above, the address correctly saves as Barcelona, Catalonia/Catalunya, Spain.

**Additional context**
You will want to test with the following addresses in order to cover our bases and confirm things still work:

City: Tel Aviv-Yafo
State: Tel Aviv
Country: Israel

City: Bethlehem
Country: Palestine

City: Paterna
State: Valencia
Country: Spain

City: Barcelona
State: Catalonia
Country: Spain

City: Castello (that's how it's been entered by students. Full name is Castellón de la Plana)
State: Valencia
Country: Spain

Any other US addresses you find useful.

**Comment by adrichey** [comment]
Said pull request: #1925.

**Comment by ophelieh** [comment]
Sounds great! :) 

Another city would be: Castello (that's how it's been entered by students. Full name is Castellón de la Plana)
State: Valencia
Country: Spain

**Comment by adrichey** [comment]
@ophelieh I added that as a test case in the above description. Thanks!

**Comment by adrichey** [comment]
@ophelieh and @kmorton2017 this is ready for testing. It has pretty specific test cases, so Kai or Nick could probably jump on testing this as well. As soon as this is tested I will cut another production release since this is preventing Barcelona users from populating their addresses.

**Comment by nickiredescent** [comment]
### I've separated each "context" into cases and took notes on steps that caught my eye. If no note is made, expected behavior occurred.
 
**Case 1 - Tel Aviv-Yafo**
During step 5: Typing Israel in the Country field yields a prompt asking to clarify between Israel or Palestine.
![image](https://user-images.githubusercontent.com/45576078/50994145-572f9500-14d0-11e9-8513-bdac7d89357a.png)

Step 7: Exact results not matched, screenshot included.
![image](https://user-images.githubusercontent.com/45576078/50992908-30bc2a80-14cd-11e9-9079-a5218113abc4.png)

Step 9: Location is displayed as "Tel Aviv-Yafo, Tel Aviv District, Israel"

**Case 1.5 - "Tel Aviv, [No State/Province used], Palestine"**
Step 5: Typing in Palestine into the Country field does not result in a prompt.
Step 7: There is no "results not matched" screen. Screen confirms this person's region will be saved as _City: Tel Aviv, State/Province: (no state/province), Country/Territory: Palestine, State of_.
Step 9: Location is displayed as "Tel Aviv, Israel".
Step 9.5: Clicking "Edit Location", the following screen once again shows the prompt to clarify which territory; Israel is ticked.
Unsure if this is useful, but I wanted to test it to see what would happen.

**Case 2 - Bethlehem**
Step 7: Palestine changed to Palestine, State of

**Case 3 - Paterna**
Step 7: Valencia changed to Valencian Community

**Case 4 - Barcelona**
Step 7: Catalonia changed to Catalunya

**Case 4.5 - "Barcelona, Connecticut, USA"**
Step 5: Typed in _City: Barcelona, State/Province: Connecticut, Country/Territory:USA_
Step 7: City has changed to West Hartford
Step 9: Location is displayed as "West Hartford, Connecticut, United States."

**Case 5 - Castello**
Step 7: Castello changed to Castellón de la Plana. Valencia changed to Valencian Community

**Comment by adrichey** [comment]
@nickiredescent Here are some notes:

**Case 1/1.5**
When it comes to Israel/Palestine, that is intended. There is some specific logic going on for those, so if we want to improve the functionality piece where Israel is checked even though Palestine is what was saved, we might want to create a follow-up ticket in the future.

**Case 4.5**
This also makes sense. The Barcelona Connecticut address is never the same place because Barcelona brings up a series of bars in that area and our Google API likes to get wild and pulls up a city for that bar. New England is wild.

Things are working as intended in my opinion. Thank you for being so thorough!

**Comment by ophelieh** [comment]
Seems to be working great! I even created new profiles with some of the challenging regions and it worked like a charm. :)

**Comment by adrichey** [comment]
@ophelieh I have rolled this hotfix out to production, so our users in Barcelona should now be able to update their locations without encountering this bug. Thanks!

**Comment by adrichey** [comment]
Reopening after a discussion with @ophelieh about Barcelona once again not saving properly.

**Comment by adrichey** [comment]
@ophelieh that was related to this ticket. This work should cover that. :)

**Comment by adrichey** [comment]
This is once again ready for testing. Thanks!

**Comment by ophelieh** [comment]
@adrichey I tried a few different tricky locations (Palestine and Spain) and it seems to be working fine.

**Comment by adrichey** [comment]
Thanks for testing this @ophelieh! I am going to close this ticket again in that case. I will deploy this to production as soon as #1909 and #1914 get through QA. I don't want to roll out any hotfixes as we have a lot of code ready for deployment.
