### ISSUE TITLE
Create a new sign up link for judges

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1943]
**Description**
Alan will generate a new sign up token for judges for 2019.  When he does this all the links from 2018 will become invalid. Both admins and RAs have access to this link on their dashboards. The purpose is for them to invite judges to our platform. 

**Next steps**
@kmorton2017 Please give us the exact date that we would create this link. Once created, RAs will be able to see and use it. This card cannot be tested on QA. This functionality has to exist on production.

**Comment by Allicolyer** [comment]
@adrichey I believe this will be February 1st.

**Comment by adrichey** [comment]
The work for this has been completed. I have regenerated the judge signup link and it is now active. The link can be found in the Invite Users section of the admin dashboard. That link can be provided to your RAs so that they can share that link with judges. Please let me know if you have any questions.

**Comment by Allicolyer** [comment]
This looks great. @KaiLokken would you be able to test this?

**Comment by KaiLokken** [comment]
Logged in as admin on the actual TC platform, clicked on "invite users" and the judge invitation URL popped up. And, the URL brought up the judge sign up page. So, I think it worked!
