### ISSUE TITLE
Virtual Judging will end before RPEs this year

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1946]
**Is your feature request related to a problem? Please describe.**
Program staff wants the RPE timeline to be longer than the virtual judging timeline this year. the season toggles only allow quarterfinals judging to be on or off. Additionally program staff wants virtual judging to happen in the beginning of quarterfinals, not the end. 

Virtual judges will need to stop judging after 3 weeks, but nothing on the platform will stop them from continuing to judge anyway. This will cause major headaches because semifinalists will already be selected ect.

**Some solutions**

1. Having a separate season toggle for virtual judging versus RPEs (very high technical lift)
2. Putting messaging on the platform telling people that judging is over
3. Doing "database surgery" to remove scores that were submitted after virtual judging cut off. 
4. Make both judging periods 4 weeks long - April 27-May 27th 

Right now we are thinking of options 2 and 3 together. 

**Info we need*
@kmorton2017 and @ophelieh can you follow up with us and answer these two questions.

1. What will the messaging say. Please give us exactly what you want it to say and where to display it. 
2. What is the date for the cut off.

**Comment by ophelieh** [comment]
Hi @Allicolyer @adrichey We actually discussed changing the dates so both open and close at the same time. I need to double check with RAs to make sure they haven't scheduled events after the 27th but otherwise we would have virtual and live judging open on April 27th and close on May 27th. 

I will keep you posted!

**Comment by ophelieh** [comment]
Hi all! Based on my conversation with RAs, we will have to go with option 3 & 4. 

Draft Text: "Virtual judging is now closed! **Any score submitted after today (May 27th) will be removed.** Thank you for your help." --- this should be on the landing page when they log in and on the page for calling new submissions. 

What do you think @kmorton2017? Do we want to keep the virtual judging to May 27th, or bring it back to the 20th?

**Comment by Allicolyer** [comment]
@ophelieh Monitoring the virtual judging is a lot of work -- My recommendation is to go with option 2 and keeping the original dates.

**Comment by adrichey** [comment]
@kmorton2017 It sounds like we are ready to move forward with this. Can you take a look at the draft text @ophelieh put together and put your stamp on this so I can get started soon?

**Comment by Allicolyer** [comment]
Since we're doing the database surgery option, it might make sense to make another card for that to remind ourselves when the time comes.

**Comment by kmorton2017** [comment]
sorry guys! if you have reached a consensus feel free to go ahead. i  don't want to be a bottleneck. 

confirming dates and text for virtual judging:

April 27th-May 20th
Virtual judging is now closed! Any virtual score submitted after today (May 20th) will be removed. Thank you for your help.

**Comment by stenington** [comment]
@ophelieh Can you confirm if these are the two spots you're thinking of where the messaging should go?

Judge dashboard:
<img width="1276" alt="screen shot 2019-02-07 at 11 27 30 am" src="https://user-images.githubusercontent.com/55319/52427136-5ee15a00-2acd-11e9-9bce-fc35ed211d48.png">

Screen after you finish judging a submission:
<img width="1276" alt="screen shot 2019-02-07 at 11 39 42 am" src="https://user-images.githubusercontent.com/55319/52427131-5d179680-2acd-11e9-8e47-dc4b6ed397c3.png">

**Comment by stenington** [comment]
@adrichey Can you check my thinking on the following? 

I think there may actually be a way to disable the `Start a new score` and `Start another score` buttons rather than just putting some text next to them. Both use the `CanStartNewScore` module as a check, which I think is specifically checking that the user can start a new **virtual** score. 

I think the hardest part of doing a full fix here is actually working out the logic of the `SeasonToggles`, but I think we need a larger conversation about whether the `SeasonToggles` are the right approach. I think they have too much logic in them. To me, they should literally be a set of toggles that we can toggle on/off all independently, and it would be **on us** (meaning Iridescent employees, not necessarily the dev team) to flip the right switches at the right time to run the season. And if the switches are designed with enough granularity, that let's us do things like experiment year to year with RPE judging and virtual quarterfinal judging ending at different times *without difficult code changes*. But anyway, that's a separate convo.

My real point is that I propose adding an environment variable that can be checked in `CanStartNewScore` that acts as an override to turn of virtual scoring, regardless of what the `SeasonToggles` are saying. That way come May 20 we just have to set a piece of config in production and those buttons no longer appear, but live judging should still work as normal. Then when quarterfinals end and we change the `SeasonToggle`, we remove the env override as well.

I know there will still be a messaging component to work out to make sure we're telling virtual and live judges the correct dates respectively, but I think that should be doable.

@adrichey What do you think? Worth a try, or do you already see problems with this idea?

**Comment by adrichey** [comment]
@stenington I think the first part about `CanStartNewScore` seems correct. I think the approach sounds good. Honestly, I cannot think of a cleaner solution and really like that. I think that override check that comes from the `.env` is the way to go, and it makes toggling it much simpler. I am not seeing any issues with it after looking around a bit.

To your second point, I think we should start having some greater conversations about the system as a whole. I think that `SeasonToggles` is one good spot to have discussions. Another that is on my radar is how to code our Vue apps so that they function better with less side effects (they are all over the place right now). I think we have a lot of room for improvement, but we need to talk about approach on this stuff.

**Comment by stenington** [comment]
Looking into the messaging piece, I found [this](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/technovation/season_toggles/judging_round_toggles.rb#L10) which is a little worrying. It seems like some parts of the app will look to `SeasonToggles` to see if we're in the quarterfinals or semifinals or whatever, while other parts will compare the current date to these hardcoded dates instead. 

So I want to wave a red flag here. I don't think the exploratory testing already performed will accurately predict the season because it wasn't performed during the actual season dates.

**Comment by adrichey** [comment]
Mike has raised some really important concerns. I think we need to think of a way to test this logic and do more exploratory QA. My recommendation would be to move these variables to `ImportantDates` so that we can set these variables at the environment level and test before those dates come. @stenington what do you think of this approach? Should we create another ticket to get that put into place so that we can do more exploratory QA?

**Comment by stenington** [comment]
@adrichey Yeah I think that's probably a pretty good idea.

It also appears with the hardcoded dates that the system can already handle RPE quarterfinals ending later than virtual quarterfinals. It looks like last year RPEs ended 2 days later than virtual judging?

**Comment by stenington** [comment]
@adrichey I opened #1971, and propose we do that ticket and then do another round of exploratory QA before coming back to this ticket. Sound okay?

**Comment by adrichey** [comment]
Sure. I think that is a good way to go. I will move #1971into To Do, and move this one behind it in To Do and mark it as blocked until that work is complete.

**Comment by stenington** [comment]
Another point of clarification will be needed on this one. When we say "virtual judging stops before live" does that mean creating new scores, finishing in progress scores, and editing old scores? Or is it just creating new ones, but finishing or editing can happen for a while longer?

**Comment by Allicolyer** [comment]
Hey @stenington 

All virtual judging will stop. So no more creating new ones, editing, or finishing any virtual scores after that date. We will be selecting the semifinalists right after that date, so we do not want an "unfinished" score to be finished and submitted.

**Comment by stenington** [comment]
Okay, so that reduces the effectiveness of the database surgery option. We can remove scores created after the deadline but we can’t un-edit edited scores.

**Comment by adrichey** [comment]
It is starting to sound like we are going to have to just lock this down somehow based on dates so people cannot edit scores after that date. 😬 Mike, I will bring this up during our prioritization meeting today.

**Comment by amyiridescent** [comment]
Just fyi data from last year. We had 685 teams be judged virtually in quarter finals last year. Only 15 of those teams had more than 8 scores. Average was 3.6 scores per team.

**Comment by stenington** [comment]
I think I have a PR that will allow us to have virtual judging and live judging end at different times for the quarterfinals without worrying about database surgery or relying on users to follow instructions. The way it would work is that we would set two dates in the environment: a virtual QF end date and a live QF end date. Then, even if quarterfinals are turned on in the settings, the platform will also check the appropriate date before deciding whether to show a judge the judging controls, or to show them this screen that I think was shown last year between QFs and SFs:

![localhost_3000_judge_dashboard 15](https://user-images.githubusercontent.com/55319/52596243-d7be1a00-2e1d-11e9-94c9-bfe889618aed.png)

I don't believe that screen would have come up during exploratory QA, because it relied on the current time being between some hardcoded dates to show it, and exploratory QA was not done during those dates. 

Long-term, I don't believe this is a great overall solution because the interaction between the quarterfinals setting in the admin and these dates set in the environment is a little confusing. I think the dates should probably be made available as admin settings, and maybe the quarterfinals setting should actually be split so that virtual and live can be toggled individually from the settings, but that's not work I'm willing to take on right now. But for this season, if turning off virtual qfs before live qfs is something we need to do, I think we can manage it with my PR.

@kmorton2017 can you confirm that this feature is needed? There was some discussion in the dev prioritization call today about why we would need to lock down virtual scores while live scores were still coming in, and it caused some doubt about whether this feature is actually necessary.

If it is necessary, I can put my PR on staging for testing, and I'll open another ticket for later talking about the dates that for this year we would just set in the environment.

**Comment by kmorton2017** [comment]
can we clarify 2 questions? These will inform our decision. 

1) Is it possible to test these dates this year during exploratory QA? or no? 
2) At what point does a judge receive the message that there are no more submissions left to score (ie when 100% of virtual teams have received X# of scores)

**Comment by stenington** [comment]
Sure, answers below:

1. Yes, I could have explained that better. I've already made a change so the dates that were hardcoded can now be changed by a developer in the environment. That means that during exploratory QA, with a developer's help you'll be able to see what the platform will look like before and after those deadlines by having us change the deadline dates for you.

2. I'm not sure I understand this question. The above screen isn't saying there are no more submissions left to score, it's saying that whether there are submissions or not, quarterfinals are over and further scoring is not allowed. 

Running out of submissions to score seems like a separate issue to me. This feature is asking that there be a way to prevent virtual judges from continuing to score submissions, while allowing live judges to continue scoring. [This comment](https://github.com/Iridescent-CM/technovation-app/issues/1946#issuecomment-461991036) suggests that this feature is needed because semifinalists will be selected before RPEs finish.

**Comment by amyiridescent** [comment]
Alan, checked this for me earlier. Each submission can only get 9 scores at the max. That is how it is written in the platform which means if every team received 9 scores, there will be no more to be judged. 

One thing to note is that any judging that started (i.e. not completed) counts towards these 9. I remember this because some of the judges didn't finish the scoring and it was an issue last year.

**Comment by kmorton2017** [comment]
If everyone is comfortable, let's proceed with exploratory QA to determine if there are bugs/complications with two separate dates.

**Comment by stenington** [comment]
Acceptance criteria:

Using [this document](https://docs.google.com/document/d/1bFN0yf2M0RrpdxBaq4tudNfhcvGetifY3v1gnHvkV20/edit#) as a guide, confirm that the "Configuration expectations" table on page 2 is accurate. 

Advanced QA:

Check that transitions are enforced. E.g. put the app into quarterfinals, start judging and leave the page open just before submitting. Put the app into between rounds mode and try to finish the score. It shouldn't let you at that point.

Open question:

If I configure QFs to end on May 20, does that mean they're closed on that day, or open until 11:59pm on May 20? Do they close worldwide at the same time? Which timezone do we use to configure the site then?

**Comment by kmorton2017** [comment]
quick clarification point (you may have just used may 20th as an example) but the following dates are:

Quarterfinals (both live and virtual): April 27th-June 2nd
Semifinals --June 8th-June 17th 

I'm not sure the technical answer to your question @stenington but we were thinking of manually switching off judging the morning of Monday June 3rd since we know that several events are happening that weekend in Spain (#1 country for registered girls) and judges may want extra time to submit their scores. 

all of our messaging will remain the same with a sense of urgency to submit scores on time. however, an admin like myself would likely switch off judging at 9:00am PST on June 3rd.  All times should be configured in PST. our program team communicates the deadlines to our stakeholders and we tell them to use a time converter.

does this complicate things for you? We are happy to stick to a strict date/time if you need us to.

**Comment by stenington** [comment]
Thanks @kmorton2017, that's good clarification. I don't think what you describe is possible with the current code or the changes I made for this ticket, so that may be something to revisit.

**Comment by amyiridescent** [comment]
If we need to have a hard date coded into the platform, I suggest that be June 3rd and we still tell everyone judging ends on June 2nd. We know from past experiences we are going to have late scores coming in from RPEs.... my two cents.

**Comment by stenington** [comment]
That’s not currently possible either, @amyiridescent. If we put in June 3rd the site will say June 3rd. 

What I want to do at this point is add an option to the judging round admin setting for “Between rounds” so that all date configuration is for display only, and all actual changes in judging rounds happens from the admin settings. It’s easier to understand, it’s easier to use on staging, and it gives us flexibility between what we tell people and what we actually do.

**Comment by stenington** [comment]
Digging in a little bit it looks like what we'd actually need to completely free judging phase logic from dates would be 5 judging round options, something like:
* off
* quarterfinals
* between rounds
* semifinals
* finished

**Comment by stenington** [comment]
I'm actually going to close this ticket and write up a new one with the above proposal.

**Comment by ophelieh** [comment]
Hi @stenington! For the date, we could keep June 2nd and just push it to 11:59 PM PST. Would that work? 

For your last point, do you need dates from us?

**Comment by stenington** [comment]
@ophelieh Take a look at #2025 and let me know what you think.
