### ISSUE TITLE
Add help text for submission page for videos

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1947]
**Description*
Add help text for videos telling users to make sure they are not private. 

**What we need**
@kmorton2017 and @ophelieh pleas give us the exactly help text you would like. We will put it on the confirmation page for the videos.

**Comment by ophelieh** [comment]
We were thinking: 

Please make sure your video's sharing settings are public!  If it is private, others will not be able to view it.

**Comment by Allicolyer** [comment]
Thank you @ophelieh sounds great :)

Maybe add:

"Please make sure your video's sharing settings are public! If it is private, judges will not be able to view it, and you may lose points or not be judged at all."

**Comment by ophelieh** [comment]
Perfect!

**Comment by Allicolyer** [comment]
awesome!

**Comment by adrichey** [comment]
@Allicolyer I just noticed that on the demo video uploader, we are linking to the following page: https://technovationchallenge.org/curriculum/pitch-2/

On this curriculum page, we say that a video can be "private or unlisted" which could be confusing to users. I think we should change that to just "unlisted" so that way they aren't setting their videos to private. Can you make that change on the curriculum? I am working on getting the text into the app in the mean time.

**Comment by nickiredescent** [comment]
Tested, both demo and pitch videos lead to a screen that asks to review my video submissions along with helper text. Screenshots attached.
![image](https://user-images.githubusercontent.com/45576078/52233575-4de9dc00-2874-11e9-899f-950ab06ba978.png)
![image](https://user-images.githubusercontent.com/45576078/52233606-622dd900-2874-11e9-9e46-67f18d787456.png)

**Comment by adrichey** [comment]
@nickiredescent Thanks for testing!
