### ISSUE TITLE
Include incomplete scores on printable PDF for events

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1949]
**Description**
RAs should be able to download a PDF of scores for RPEs, including incomplete scores. Right now only complete scores show up. RAs use this printable PDF to print out before their event starts and hand to the judges there. The judges should in theory be able to finish a half complete score. 

**Acceptance Criteria**

1. Turn on events as an admin
2. Log in as a RA (ra@ra.com)
3. Create an event
4. Invite judges and two teams to the event
5. Turn on judging as an admin
6. Log in as the judge. Complete a score for the first team.
7. Start, but don't finish a score for the second team.
8. Log back in as an RA. Confirm that both the complete and incomplete scores appear on the printable PDF. You can find this printable PDF under the events menu.

**Comment by kmorton2017** [comment]
update from meeting on 02/08 do not prioritize this

**Comment by stenington** [comment]
Grabbing this one because it was at the top of the backlog (despite the do not prioritize note)

**Comment by stenington** [comment]
Use the Acceptance Criteria in the initial description as QA steps (although feel free to find an existing event where there are both complete and incomplete scores).

**Comment by ophelieh** [comment]
Hi @kmorton2017 could you test this today or tomorrow? 

Thank you!

**Comment by kmorton2017** [comment]
This is a scenario that will likely not happen often in the real world but thought I would share. 

As an RA (katie+ra7@iridescentlearning.org) I created an event in China and added 2 judges. I logged in as Alicia Keys and completed score for the first team and left incomplete scores for the other team. 

I logged in as the other judge (Dolores Umbridge) who unbeknownst to the RA was already judging at another event.  I logged in as the judge Dolores and saw only the RPE in LA not the 2nd event in China I was also scheduled for.

When I logged in as the RA to see the PDF, i saw both Alicia Keys scores for the Chinese teams, and oddly enough was able to see Dolores' scores for the RPE in LA with those teams listed on the PDF.

I don't think this is a usual case (since I unknowingly added a judge who was scheduled at another event, and also one in another country). 

Let me know if my feedback needs any more explaining!
Katie

**Comment by stenington** [comment]
Thanks @kmorton2017, that sounds to me like another bug with judges in multiple events. 😢 

Let me see if I can address it easily for these printable PDFs though.

**Comment by stenington** [comment]
Ok @kmorton2017 I was actually able to account for this scenario, thanks for finding it! These printable pages should only show scores for submissions in the event now.

**Comment by ophelieh** [comment]
@kmorton2017 Could you retest?

**Comment by ophelieh** [comment]
@nickiredescent Could you test this? 

Thank you!

**Comment by nickiredescent** [comment]
Tested. Looks good to me.

I ran through Katie's initial testing again. I can still see both the complete and incomplete scores done by Judge Alicia Keys. While Judge Dolores Umbridge is still listed as a judge for this event on the platform, she is not listed as a judge on the pdf. An important note: Umbridge has also not started or completed any scoring for the China event in question.

I also tested on different accounts and as far as I can tell, "print pdf" is working as intended. It is printing a list of participants, judges, scores and feedback for all and only those attending the event I chose.

**Comment by kmorton2017** [comment]
i retested this. i expect we'll be talking about judges at different events today @stenington so won't address that in depth here. 

I created scores for teams using Umbridge's account. She is appearing on the pdf with scores. 

this appears to be working now.
