### ISSUE TITLE
Change events so that it can only be one division 

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1950]
**Is your feature request related to a problem? Please describe.**
Problem: You can't make only one division unofficial for an event. This means that an RA must create two events if they do not get at least 10 teams for each division. This leads to staff time asking to RAs to delete and remake events, the re-inviting the team to the events, ect.

**Describe the solution you'd like**
Change the checkboxes for divisions to radio buttons

**Acceptance Criteria**
1. Make sure events are turned on as an admin
2. Log in as an ra
3. Create an event
4. Confirm that the event can only be junior or senior, not both.

**Comment by adrichey** [comment]
This is now ready for testing. Please note that this change does not convert RPEs already in the system to one division. The reason why this was done is so that live events already created in the system are still able to function as before. If you edit an event that has both junior and senior divisions it will show them as neither being selected when the edit form loads because of this compromise. The plus side to this bit of weirdness is that it prevents people from hitting save on that form so they don't accidentally convert the event to a single division if they are on auto-pilot. We may want to convert all RPEs over to being a single division on the back-end at a later date. Comments were left in the code to this effect.

**Comment by ophelieh** [comment]
@nickiredescent Could you test this today?

**Comment by ophelieh** [comment]
Question - what happens for events that have already been created and have both divisions? (I just checked on the platform and we currently have 2 with 2 divisions)

**Comment by ophelieh** [comment]
Otherwise, it works as expected - I can only select one division. 

_Side note - I was able to create an event that starts at 14:00 (2pm) and ends at 7:00. Not really important but wanted to bring it up just in case_

**Comment by adrichey** [comment]
@ophelieh they will still be set for two divisions. This only affects new events.

As for the other issue, we have noticed that and talked about validating the inputs of the start and end time in the past, but it has never been a high priority. We may want to make a note of that somewhere and maybe address it later if we have some quiet time.

**Comment by ophelieh** [comment]
Ok. Good to know! 

And should I add it to the icebox maybe?

**Comment by adrichey** [comment]
It might be a good one for the icebox. Sure!

**Comment by nickiredescent** [comment]
Also confirming that RA event creation can only be done with a single division selected.
