### ISSUE TITLE
Admin Participant Search by Onboarding Students Produces Error

### ISSUE THREAD

**Issue by nickiredescent** [Iridescent-CM/technovation-app#1978]
**Describe the bug**
As an admin, filtering participant search by still onboarding students results in an error.

**To Reproduce**
1. Log in as an admin
2. Go to "Participants"
3. Under the "Onboarded Students" search filter, choose either option.
4. Click Search
5. Error Appears

**Expected behavior**
I expect the participants to be filtered to whatever onboarded status I've chosen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by adrichey** [comment]
@nickiredescent I don't believe this is a bug. You need to select "Students" from the Profile Type selector in order for that filter to work. You have to select "Mentors" when using the "Onboarding Mentors" filter as well. Maybe an improvement could be made to this UI so that the onboarding filters don't show up until a profile type has been selected? One future improvement I have had on my mind would be to split up the Participants panel into Students/Mentors/RAs/Judges so that way we can eliminate the profile types filter altogether, but that is a future improvements discussion we don't really have the bandwidth for right now. :/

**Comment by nickiredescent** [comment]
Ah I see that it works that way now. Thanks for clarifying that with me @adrichey. Throw it into the future box it is then!

**Comment by adrichey** [comment]
Welcome. It is a little odd in any case. Hopefully we can prioritize some improvements in that section one day soon. 🙂

**Comment by hellafitz** [comment]
closing since we made #2167 to encompass this larger issue
