### ISSUE TITLE
Scores section on dashboard needs styling work

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#1994]
**Describe the bug**
Right now, when a mentor or student views their Scores & Feedback section within their dasboard the scores are scrunched up to 50% of the view width when they should be extended the full 100%. See screenshot below.

**To Reproduce**
1. Log in a mentor with scores
2. Click on Scores & Feedback in the dashboard
3. Observe that the scores only take up half of the available space

Repeat these steps for a student.

**Expected behavior**
The scores take up the full view.

**Screenshots**
![screen shot 2019-02-25 at 12 03 50 pm 2](https://user-images.githubusercontent.com/1534554/53358416-e1ec1800-38f5-11e9-884f-b32256d54604.png)

**Comment by adrichey** [comment]
Pull request opened and assigned to @RRios00 for review: #2024.

**Comment by nickiredescent** [comment]
Tested.
For mentors, the scores take up 100% of the page width. Screenshot below:
![image](https://user-images.githubusercontent.com/45576078/54934774-49d55480-4edc-11e9-9c76-a737a9606697.png)

For students, I suppose this also fulfills the criteria? A part of the score is still only 50% of the page width but it makes sense for me that this is not stretched out. If it's possible, perhaps center the score instead of having it aligned left. Screenshot attached.
![image](https://user-images.githubusercontent.com/45576078/54934717-375b1b00-4edc-11e9-9f8b-2bf0557fc448.png)

**Comment by adrichey** [comment]
@nickiredescent, that second issue for students on #1994 isn’t actually an issue, you will see additional scores pop up in that summary page that will fill up the right hand column, so this all seems to be working appropriately from my perspective.
