### ISSUE TITLE
Mentor getting wrong certificate

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2010]
**Describe the bug**
As a mentor for multiple teams, I am getting different certificates for teams that submitted. I should only get a certificate of mentoring. See video (log in as King Arthur or Professor Oak) - https://drive.google.com/file/d/1sN8Y3f76IEveFEvTY-mFnG0JH9k7LbsH/view

**Expected behavior**
I should only see mentoring certificate for each team.

**Comment by stenington** [comment]
So there's really two things going on here. Somehow, the wrong certificate got generated for Professor Oak in relation to DancingintheDark. That certificate is now gumming up the works when the system is trying to find the right certificate Professor Oak should have gotten. So there are two parts: 
1. How did the wrong certificate get generated in the first place?
2. Now that the wrong certificate has been generated, how do we deal with it?

I feel that the admin should actually have two separate sections relating to certificates: a section describing what the system thinks the user **should** have, and a section showing the actual certificates that have been generated for that user so far. Probably it should also have a third section that lets admins generate whatever certificate they see fit for any user, instead of the more complicated override setting. 

That feels out of scope for this single ticket, but I think we may actually be able to solve several problems at once by regarding certificates more like a new feature than a collection of bug fixes. (Documenting that here because I'm not sure where else to put it right now.)

**Comment by ophelieh** [comment]
HI @stenington! That makes a lot of sense. I like the idea of having 3 sections. Based on our conversation last week, do you think that will be doable? 

Thanks!

**Comment by adrichey** [comment]
Stale ticket to be addressed when #2057, #2059, #2060 and #2061 complete. Closing the ticket.
