### ISSUE TITLE
Data access for score monitoring

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2032]
**Is your feature request related to a problem? Please describe.**
In past years, during judging we've had people who want to monitor scoring progress in a very detailed way off the platform. [This is an example](https://docs.google.com/spreadsheets/d/1-CYXJEJwwIEW6WwYC-VrL_e78WMVKGFhagLPKXrnibw/edit#gid=1649385589) of what that kind of monitoring can look like.

**Describe the solution you'd like**
I would like to put together documentation about the kind of monitoring desired, and make sure we have a way to satisfy that request (whether it's through the admin, dataclips, behind-the-scenes exporting of data, whatever).

**Comment by stenington** [comment]
@amyiridescent I think you can help with the documentation piece. If you can describe the types of questions you're trying to answer and maybe the pieces of data necessary to do so, @adrichey and I can start making sure all of that stuff is accessible in some relatively convenient way.

**Comment by stenington** [comment]
Chatted with @amyiridescent, who raised two concerns we've heard raised before, so I'm commenting here.

In the past we've seen the algorithm that finds a valid submission make two mistakes:
1. assigning the same submission to lots of judges before moving on to assign a new submission
2. letting a submission get "stuck" with 10 pending scores, none of which are ever completed

Looking at the code, I'm reasonably confident these scenarios have been accounted for. As it pulls potential submissions to assign to a judge, it sorts submissions by a weighted combo of their complete and incomplete scores, and it only filters out submissions with 9+ completed scores. So I think these two specific issues are unlikely to reoccur, although we could consider writing additional tests to convince ourselves.

**Comment by stenington** [comment]
Actually, I'm going to open two tickets for those tests.

**Comment by amyiridescent** [comment]
I think this is the ticket where I should document what raw data we need in order to monitor scoring. (I plan on training @KaiLokken this week using old spreadsheets.)

Here is the raw data Alli pulled directly from the server last year for Quarter Finals (https://docs.google.com/spreadsheets/d/1-CYXJEJwwIEW6WwYC-VrL_e78WMVKGFhagLPKXrnibw/edit#gid=1649385589 ) and Semi Finals (https://docs.google.com/spreadsheets/d/1lVj9axqwTP6EDq_NL7iFTH15CsZJGtruoAMTlD2yShE/edit#gid=1399797775 ). It will be great if we can get a data clip to pull the same information. And if it is in the same column order, even better. (Mostly because the spreadsheet is pre-written with functions BUT if it is too difficult, it is not that hard for me to restructure it.) 

In general, this is what we did last year. 
1. Once a day, Alli will pull the raw data. 
2. Update all the tabs on the spreadsheet. (meaning run all the pre-written functions)
3. For quarter finals, we will only focus on the virtual judging. 
4. We will mostly focus on submission with wide range of score differences. (https://docs.google.com/spreadsheets/d/1-CYXJEJwwIEW6WwYC-VrL_e78WMVKGFhagLPKXrnibw/edit#gid=824758563) 
5. An Iridescent staff member will be assigned to look at the submission to check if there is anything suspicious going on with judging. 
6. If it is decided that a judge should be warned, score be deleted, or judge be blocked. It was tracked here. (https://docs.google.com/spreadsheets/d/1svTNbtvaGzAhRdX-e_TNY6gmoOIShnl9dqNVtwcYRvo/edit#gid=0)
7. I believe the score deletion happened on the server not on the admin page. 

Note: This is in addition to the suspicious activity that gets directly flagged by platform which requires an admin to clear each day. (Or the score will be in limbo.) In the past few years, quarterfinal score monitoring is more intense. By the time Semifinals roll around, judges are either good at it or we have gotten rid of weird ones... I don't remember semi-finals monitoring being too intense. 

Hope this helps!

**Comment by stenington** [comment]
@amyiridescent Back in January we did ticket #1951 which did two things:
* it added columns showing the min/max score range for QFs and SFs, **but**
* it also took away the ability to export each individual score

It looks like the raw data export you need is exactly the thing we took away in January, so we will find a way to bring that back. My question is whether you also want me to add the pre-calculated score range columns to that export? Or would you prefer to do that calculation in your spreadsheet?

**Comment by amyiridescent** [comment]
Sorry I didn't know about that ticket. :( 

As for calculation, I run it with only the "completed" scores by using a filter. I think I will just use my spreadsheet for this year. Thanks!

**Comment by stenington** [comment]
@KaiLokken @amyiridescent There's now a menu option in the admin for **Score exports** underneath Scores that should let you export the data you need for your spreadsheets. Can you QA that it plugs in to your spreadsheets ok?

**Comment by stenington** [comment]
@KaiLokken says it's working as expected

**Comment by amyiridescent** [comment]
This looks good to me also! thx
