### ISSUE TITLE
Implement better logging and error handling for Jobs

### ISSUE THREAD

**Issue by adrichey** [Iridescent-CM/technovation-app#2063]
**Is your feature request related to a problem? Please describe.**
Right now we don't have adequate logging or status updates when jobs fail. For example, if an export Job fails, we are not able to set its status to "failed." This has UI implications as failed jobs just stay in progress forever and to the end user it looks like the export is still running, even though it has failed. Another place where this is particularly useful is when Certificate jobs generate multiple certificates for an account/profile/team combo when it shouldn't.

**Describe the solution you'd like**
We should look into Sidekiq and our Job model and see if we can store an error status on the Job if the Sidekiq job fails in any way. We should also add better logging at this point if failures occur.

**Additional context**
See this documentation for more details: https://github.com/mperham/sidekiq/wiki/Error-Handling

** This is a developer only ticket which can be closed upon pull request approval and deployment to QA/staging. **

**Comment by stenington** [comment]
@adrichey Can you give me more details on the export job failures you saw recently? I want to replicate that failure locally as a starting point for acquainting myself with job error handling options.

**Comment by adrichey** [comment]
Sure. First I log in as an admin user and browse to "Background Jobs" in the dashboard. From here, under Dead Jobs, I basically look up an "ExportJob" in the job column for another user in the system. This will give me feedback similar to the following, where __ACCOUNT_ID__ is the actual account id of the person who ran the export:
```
__ACCOUNT_ID__, "AdminProfile", "AccountsGrid", {"season"=>"2018", "season_and_or"=>"match_any", "scope_names"=>"mentor", "column_names"=>["", "returning", "city", "state_province", "country"], "name_email"=>" ", "admin"=>true, "country"=>[], "state_province"=>[], "_aj_hash_with_indifferent_access"=>true}, "Admin::ParticipantsController", "->(scope, user, params) { scope }", "technovation-accounts-2019-03-27 13:51:30 -0700", "csv"
```
This basically shows me that I need to run a Participants export with the following settings:
- Columns: Returning?, City, State/Province, Country
- Profile Type: Mentors
- Season: 2018 (match any)
Then I pull up my server tail logs in my terminal and run the export locally using the production server data that caused the failure. From here, I wait until it bombs out and then I look into the failure. Hopefully that is thorough and helpful.

**Comment by stenington** [comment]
Ok, I've learned a few things about Sidekiq, jobs, and our admin export notifications.

Sidekiq has retries built in to the system. If a job fails, it will retry a configurable number of times with a longer wait before each subsequent retry. Once all retries fail, the job is moved to the dead jobs list.

Our admin export notifications work by first looking for a `Job` in queued status. If it finds one, the in progress notification is shown. If not, it looks for an `Export` owned by the user not marked as downloaded. If it finds one, it shows the "your file is ready" notification, and both downloading it and clicking the "I no longer need this file" link hit an endpoint that mark it as downloaded.

Getting "stuck" notifications to go away should be easy enough. Sidekiq lets you configure a handler for when a job has exhausted all retries and gets moved to the dead list. We can use that hook to look up the `Job` and mark it as dead as well, taking it out of queued status. The downside here is that the user doesn't really get notification that the job failed other than the lack of a notification with a link to download it.

Building out the notifications system to allow things like reporting errors is more work. I think we'd need to back up a step and design out what that would look like, e.g. are notifications shown for a set period of time? does the user dismiss them? etc. Then we'd work out how to make that happen, which is not something to be done in a rush.

So that brings us back to the question of how we figure out what's going on if jobs are failing behind the scenes. It does seem like exceptions inside jobs end up in Airbrake, so part of this might be putting together some sort of monitoring or triage plan for Airbrake errors. There's also the dead jobs list, which we can look at and clear out. I think Sidekiq makes the assumption that that list is more actively monitored and managed, so again some process around that may help. And lastly, in some cases coding more defensively may help. The problems with certificates were particularly hard to pinpoint because they were totally valid from the platform's point of view so no errors were thrown. More careful testing may have helped catch some of those logical problems when that code was being developed. 

So that was all a long-winded way of saying the only work I really see to do here is to put that handler in place that can move `Job`s from queued to dead when they die. Otherwise I think it's more about tools and processes and setting aside time to do things more carefully.

**Comment by adrichey** [comment]
I think that is reasonable Mike. I think that at least storing the dead state will help us troubleshoot faster and keep the end-users from asking us to clear out that download generation spinner all the time. That tends to be a decent amount of my one-off issue calls. And I believe Airbrake monitoring can help, but I don't know how much work we need to put into that up front. I feel like that can be patched in as problem areas crop up. But this dead status fix will cover a big one in my opinion.

**Comment by stenington** [comment]
Ok cool, I'll put up a PR for that then!

**Comment by adrichey** [comment]
This has been tested by me during the pull request review stage. You can see my testing steps on pull request #2084. I am going to mark this ticket as closed now that the code has gone through CI and is deployed to QA.
