### ISSUE TITLE
Rework drop lowest scores task

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2076]
During semifinals we plan to drop the lowest score for each team, but the dropped score should not count against that judges judged submission total when it comes to certificate levels. Previously we would try to detect that scenario in the rake task and set a certificate override. I think we should move to a solution where we add a `dropped` field or something to that effect that the rake task can set (while also soft deleting the score), and then the judge certificate level can query for scores including deleted and dropped scores.

**Comment by adrichey** [comment]
I think this sounds like a sound approach. Tracking dropped scores will be really useful for data collection, so I like this approach.

**Comment by adrichey** [comment]
@stenington What should the QA steps look like for this? I think it is a little hard to test this one until we are ready to actually drop the scores on QA. Unless we want to backup the database, run this and test, and then revert back. But that takes a good amount of coordination. I did thorough testing on my end and things seemed to look okay. Do you maybe want to test this and assert that lowest scores for semifinals get marked appropriately, but still appear in the certificate calculations? I think it might be easier for you to confirm this one, but I don't know how biased that makes the testing since you have seen the code as well.

**Comment by stenington** [comment]
Yeah, I'll test locally and approve.

**Comment by adrichey** [comment]
This is now ready for testing. Please note that this will be tested by Mike as we need a developer to run the task and approve/deny it works since it runs in the background.

**Comment by stenington** [comment]
This passes QA. Before using in production, I'll do a trial run with a copy of the db and do some manual sanity checking with the program team to be safe.
