### ISSUE TITLE
Investigate RPE Judge Moving Into Virtual Pool

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#2121]
We would like to know the following information about RPE judges:

- Is it possible for an RPE judge (once their event is over) to move into the virtual pool? 
- IF they move into the virtual round, will their scores be saved? 
- Is it possible to do move from RPE to virtual pool within the QF round? Or only once SF has started?

Thanks Mike! I know that we have discussed this before in previous seasons and am not sure if this IS currently possible OR was possible. I will also look back through sprint notes.

**Comment by stenington** [comment]
I would suggest exploratory QA for this. I wouldn't trust my reading of the code to give you the answer, we should arrange a test on QA and see what happens. I'll take a first stab at it and write up what I do and what I see. Based on that I can selectively dig into code to confirm suspicions or flesh out details if needed.

**Comment by stenington** [comment]
What I'm seeing based on a quick test is that RPE judges in QFs can judge their RPE submissions but have no way of seeing virtual pool submissions during QFs. If the RA deletes the judge from the event, their scores from that event are deleted as well, so that's not a viable way of letting them see virtual submissions during QFs.

During SFs, all judges judge from the same pool of semifinalists. Nothing special has to happen to allow live event QF judges to participate in the SFs.

**Comment by kmorton2017** [comment]
ok good to know. @ophelieh @amyiridescent as a program team, we will need to let RA's and RPE judges know that they can only judge in the semifinals as a virtual judge.
