### ISSUE TITLE
Missing Demo video Link

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#2129]
**Describe the bug**
It seems that for some teams, the demo link has been overridden somehow. An example team is 
The Tough Tuttles (this team submitted a demo video and completed their submission). See the screenshots below. It seems that 12 teams might have been affected by this. 

As an RA this is what you see 
![image](https://user-images.githubusercontent.com/32206421/56984693-3d33c400-6b4c-11e9-976e-0c74682b8f65.png)

As an admin this is what you see
![image](https://user-images.githubusercontent.com/32206421/56984748-5c325600-6b4c-11e9-9539-cf1d130b9d17.png)

**Expected behavior**
Those teams should have a demo video link and show as complete submission.

**Comment by stenington** [comment]
@ophelieh When I look up this team in the database, they have no demo link. I do see a bug on the RA screen where it's not properly checking for a link before displaying, which accounts for the strange link in the RA view, but I would need more details before I can reproduce how the link might be getting lost. Are you certain these teams are submitting demo videos?

**Comment by amyiridescent** [comment]
Hey Mike, so this team has gotten a confirmation that their submission was complete but then somehow their demo video link went blank. Is there a way you can check on the log and see if it was recorded before?

**Comment by stenington** [comment]
The activity log in the database doesn't have any record of a demo video link being saved.

**Comment by amyiridescent** [comment]
@ophelieh can you check on this team? It sounds like no demo link was saved before. 

@stenington can you investigate the error in RA link on the RA page without this confirmation?

**Comment by stenington** [comment]
Yep, that error is easy enough to fix.

**Comment by amyiridescent** [comment]
Mike following up from the QA channel discussion from tonight. It sounds like we have a bug that when a team is inputting either the pitch or demo video as the last step in the submission process, the platform was not saving the link they submitted. Although the team is able to get confirmation that their submission is complete. Since the log does not save anything regarding the links they inputted, we were going to check the email log and see which teams were sent confirmation that their submission is complete but is now missing a link on their submission. 

Here is the spreadsheet of submissions that are at 71 or 75% that is either missing a demo or pitch video. 
https://docs.google.com/spreadsheets/d/17l010kWeu_clouZ2Cu-p8SLxL_EDFlvC5VQcHAlNAno/edit#gid=0
I just have the team and app name and their progress. Let us know which teams are impacted by this bug when you cross reference the email log. Thanks.

**Comment by stenington** [comment]
> It sounds like we have a bug that when a team is inputting either the pitch or demo video as the last step in the submission process, the platform was not saving the link they submitted. 

To be very specific, if the last thing they needed to submit was the demo link, I was able to click the publish button **without** clicking the save button, thereby publishing my submission without first saving the link I was trying to enter. The platform didn't save my link because I never clicked "Save", the bug is really that the publish button was made available too soon (and it didn't double-check the completeness). The log does not save anything in this case because again, the link was never actually saved.

I'll work through that list and see if any of them come up.

**Comment by stenington** [comment]
The fix for the RA screen is in staging.

QA:
1. log in as Admin
2. find a submission without a demo video
3. look at that submission as RA
4. you should NOT see the strange `/regional_ambassador/...` link

**Comment by ophelieh** [comment]
Hi @nickiredescent & @KaiLokken Could you test this? Thank you!

**Comment by KaiLokken** [comment]
Tested it. Worked as expected. Logged in as Neil and viewed apps with no demo videos: Ready App and Whatever App. It was just blank, no strange link:  /regional_ambassador/...
