### ISSUE TITLE
Double emails being sent when mentor requests to join team [8,8,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2224]
Two emails are being sent out when a mentor requests to join a team.

Both emails are from the mandrill app

**Comment by stenington** [comment]
Email title: "You're invited to be a mentor for a Technovation team!"

**Comment by stenington** [comment]
The problem is in `JoinRequest` which calls `notify_requested_team` on create and on `#pending!`, which for join requests from mentors is called immediately after creating the request, hence double emails.

[This commit](https://github.com/Iridescent-CM/technovation-app/commit/b6f260575e4e86c9e69795634d133d683558bdcf) introduced the `#pending!` call, saying it fixes a bug with reinstating deleted invitations, but creating the double-email bug. Some care will have to be taken to understand what the initial bug was, and to fix them both.

**Comment by stenington** [comment]
One option would be to break the `find_or_create_by!` into separate pieces and call `pending!` only if the find succeeds. That would be a band-aid on the problem at least. The code for student join requests doesn't make the same call to `#pending!` so I'm not sure if that's a latent bug or if students and mentors need it to work slightly differently.

**Comment by stenington** [comment]
QA:

1. as a student with an email address you can check, start a team
2. log in as a mentor
3. request to join the team
4. confirm you only receive 1 email to the student

@rsgonzal Do the above steps seem right? Is that essentially what you did when you got 2 emails previously?

**Comment by rsgonzal** [comment]
Yes this seems right. 

Went through the steps and all looks good. Waiting for program team to do a run through

**Comment by ophelieh** [comment]
Note - You will need to have the mentor onboarding steps complete in order to be able to join a team. To mark the training as complete, you will need to use this link once you are signed in as a mentor - https://technovation-qa.herokuapp.com/mentor/training_completion. 
You can also use an existing mentor account that has completed all the onboarding steps. 

Tested and worked as expected - I only received one email for each of my students on the team.

**Comment by rsgonzal** [comment]
Thanks, @ophelieh for listing the link :)

**Comment by devincdillon** [comment]
Reviewed, only received one email as a student.
