### ISSUE TITLE
Spike: Implication of reducing points in judging rubric [13,8,1.63]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2225]
Judging criteria need to be communicated to external partners, so before we decide on a go/no-go Program team has asked for dev to investigate the implications of reducing and re-distributing points earned during judging

Tasks:
- Investigate the platform ramifications of this change
- scope the work required to implement
- communicate to Product Team the findings, so Devin can be informed asap

See mockups with suggested changes here: https://projects.invisionapp.com/freehand/document/lNAEBLlKJ

![uploads/93f4d35d-3807-48a1-a0fb-6aa69a34843c/Screen Shot 2019-09-26 at 2.52.43 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F93f4d35d-3807-48a1-a0fb-6aa69a34843c%2FScreen+Shot+2019-09-26+at+2.52.43+AM.png)

Would need to make changes on all of the screens:
- changes to the category text
- removal of help text
- add/remove categories depending on theme

Context:
- Technical theme would be weak without code checklist
- Want to put more emphasis on Ideation
- Want less emphasis on Pitch

*Brainstorming*
Are there any other places these changes would cause issues?
- Do girls see anything while creating their submissions?
- Score results?
-  Certificates?

**Comment by hellafitz** [comment]
This can be done by 10/15, not required by 10/10

**Comment by stenington** [comment]
So it looks like the work here is something like the following:

(Note, what is called a "category" or "sub-category" above, I'm calling a **question** here to reflect the language used in the codebase.)

* Remove the `refer-to` paragraph in the `QuestionSection` app and the `referTo` data in each `judge/scores/sections/*.vue` app
* **Ideation**
    * add 1 question
    * change text on existing  3 questions
* **Technical**
    * add 2 questions
    * change text on existing 2 questions
    * (checklist removal handled by #2192)
* **Pitch**
    * remove 2 questions
    * change text on remaining 2 questions
* **Entrepreneurship**
    * change text on existing 4 questions
* **Overall**
    * remove 3 questions
    * change text on remaining 2 questions
* Update score calculation logic
* Identify and remove unreachable templates referencing old rubric fields
* Update/add specs

I believe that the rubric questions are defined in `app/models/questions.rb`, so the basic process for working with questions would be something like:
* update `questions.rb` appropriately
* update the `SubmissionScore` model, including migrations to add/remove fields as needed
* update the `ScoresController` to add/remove parameters as needed
* update RA printable scores
* update RA score details? (not sure if this is actually unreachable)

Because the score total is changing, we might consider checking the low score thresholds for junior and senior divisions as well (currently 19 and 23 respectively).

**Comment by stenington** [comment]
#2245 is the implementation epic
