### ISSUE TITLE
Change the judging rubric and score calculation [20,8,2.5]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2264]
From #2245, change the judging rubric and score calculation: 

* **Ideation**
    * add 1 question
    * change text on existing  3 questions
* **Technical**
    * add 2 questions
    * change text on existing 2 questions
* **Pitch**
    * remove 2 questions
    * change text on remaining 2 questions
* **Entrepreneurship**
    * change text on existing 4 questions
* **Overall**
    * remove 3 questions
    * change text on remaining 2 questions

I believe that the rubric questions are defined in `app/models/questions.rb`, so the basic process for working with questions would be something like:
* update `questions.rb` appropriately
* update the `SubmissionScore` model, including migrations to add/remove fields as needed
* update the `ScoresController` to add/remove parameters as needed
* update RA printable scores
* update RA score details? (not sure if this is actually unreachable)

![uploads/93f4d35d-3807-48a1-a0fb-6aa69a34843c/Screen Shot 2019-09-26 at 2.52.43 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F93f4d35d-3807-48a1-a0fb-6aa69a34843c%2FScreen+Shot+2019-09-26+at+2.52.43+AM.png)

@rsgonzal Do we have finalized copy for the new rubric already?

**Comment by rsgonzal** [comment]
copy is here: https://docs.google.com/document/d/1OxmYxzSD7bBUnkWBevzuVtynAjUG2mS65FjefPFzXfg/edit

**Comment by stenington** [comment]
This ticket **will** include help text changes, we're closing #2263 which would have removed that text.

**Comment by stenington** [comment]
Things we will want to develop QA plans for in this ticket:
* rubric changes
    * confirm all questions are correct
    * confirm all section summaries are correct
    * confirm all section rubric links are correct
* scoring
    * confirm max scores are correct for junior and senior divisions
    * confirm you can do scoring as a judge, and your score is saved correctly
* RA/admin
    * confirm that scores in the admin display correctly when viewing score details
    * confirm the printable scores sheets for an event still display correctly

Another consideration is that this change will almost certainly break dataclips. Do we want to try to deal with that now, or fix it later?

**Comment by stenington** [comment]
So maybe QA looks something like this:

### Setup
1. log in as an RA
2. create 2 events, 1 junior division, 1 senior division
3. add teams to each event and save
3b. if no teams come up, you may have to create teams that the RA would be able to see and submit
4. add judges to both events and save
4b. if no judges come up, you may need to create a judge account

### Printable scores
1. still logged in as RA, view your events
2. on at least 1 event, use the "Print for live event" button to see the printable rubric
3. confirm the printable rubric is correct

### Scoring
1. as admin, turn on quarterfinals
2. log out and log in as the judge assigned to the events
3. for each score, junior and senior...
4. judge the submission, giving max score
5. confirm the rubric changes as you do so: new page text, new question text, rubric links (on senior score you only need to focus on the extra section)
6. finish your score
6. view your finished score, and make sure the max score was saved correctly

### Admin
1. as admin, go to **Scores**
2. for each of the two scores you just created...
3. view details
4. confirm the "x/y" score displays are correct
5. click "View score" next to the score you created
6. confirm the details are correct: question text and score totals

**Comment by stenington** [comment]
@rsgonzal What do you think about dataclips as well? Should we just wait until the program team asks, or create a ticket now?

**Comment by rsgonzal** [comment]
QA steps look good, shared with Rebecca and Devin.

For dataclips, do you mean ones like this? https://data.heroku.com/dataclips/bjbpcmaurdxgdscmxtrkqwjyudkw

Noticed it's broken anyways because of the demo scores, we should probably make a new ticket but not sure if there are other ones you had in mind?

**Comment by stenington** [comment]
Yeah, that dataclip references database columns that no longer exist. I don't have other specific ones in mind, I don't have a lot of insight into all the spreadsheet processing that happens on scores. I just know when I'm changing database columns that dataclips will generally break.

**Comment by stenington** [comment]
I opened #2360

**Comment by hellafitz** [comment]
@devincdillon with Rox out today, can you update here? Thanks!

**Comment by devincdillon** [comment]
I have assigned @nickiredescent @ophelieh and Bryant to complete this ticket by Monday. They will do an excellent job 💃

**Comment by rsgonzal** [comment]
Scoring for both divisions
- Ideation should say 20 not 15 points inside parentheses
- Technical should say 20 not 10 inside parentheses   
<img width="410" alt="Screen Shot 2020-01-24 at 2 27 23 PM" src="https://user-images.githubusercontent.com/22801026/73109266-89cbe600-3eb7-11ea-9f4c-540ccd210b75.png">
![unnamed](https://user-images.githubusercontent.com/22801026/73109289-994b2f00-3eb7-11ea-9d26-06c3a8a9c020.png)
 
- Technical point # 3 change from "All team members appear to have contributed to coding." to "**All team members appear to have gained technical knowledge and contributed to coding**."
- Pitch should say 10 not 20 in parentheses
![unnamed (1)](https://user-images.githubusercontent.com/22801026/73109360-bda70b80-3eb7-11ea-86c2-6911abe2c66b.png)

- Pitch point #1 can we adjust from "This is an urgent problem and I believe this team has an effective solution." to "**The pitch makes me believe that this is an urgent problem and that the team has an effective solution**."
- Pitch point #2 can we adjust from "I believe the team learned from challenges and each girl persevered to learn new skills." to "**The pitch makes me believe that the team learned from challenges and each girl persevered to learn new skills**."
- Overall Impression number in parentheses change to 10 instead of 25 
![unnamed (2)](https://user-images.githubusercontent.com/22801026/73109416-e0d1bb00-3eb7-11ea-9ebf-7259bc969396.png)

**Comment by stenington** [comment]
This should be ready for re-test when the deployment goes through.

**Comment by rsgonzal** [comment]
- it tells me to open up the presentation slides, but nothing is linked - is that just because a presentation wasn't added? (i think yes)
- can we hyperlink the pieces of the rubric in the opening sentence?

**Comment by ophelieh** [comment]
Does this still need to be tested?

**Comment by rsgonzal** [comment]
@ophelieh i think this one is good, i sent you another to take a look at but I think there's a lot in that thread. Let me know if you want me to send again!

**Comment by stenington** [comment]
@rsgonzal It looks like the pitch presentation link shows if the team is in a live event, it doesn't look like it checks if they actually uploaded a pitch presentation at all, so yeah that's probably why that link didn't open anything for you. Is it okay to assume that all teams in live events will have uploaded something to avoid an actual judge having the same problem you did?

**Comment by stenington** [comment]
Ok, @rsgonzal you can re-test that rubric links open in new tabs.

**Comment by rsgonzal** [comment]
@stenington yup, i think that's a fair assumption! Or they're actually scoring in person and just uploading their scores. So I think this is ok.

rubric links look good!

Rebecca also gave it another look and said all looks well 👍
