### ISSUE TITLE
Update buttons, header and footer on TC wordpress

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#2277]
Make the following changes to the TC WordPress to match the mockups: https://www.dropbox.com/sh/mxuemjr05p7dc9m/AABkDhuL1s-B1PYJLbllEY98a

- Buttons should be square, not rounded
- Update styling of footer
- Update styling of header

**Comment by Allicolyer** [comment]
@mjaris I see square buttons in the mock-ups. Is that correct?
![uploads/8684290a-8e61-4776-ad60-c05a7ed65fd1/Screen Shot 2019-10-16 at 5.37.46 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8684290a-8e61-4776-ad60-c05a7ed65fd1%2FScreen+Shot+2019-10-16+at+5.37.46+PM.png)

**Comment by Allicolyer** [comment]
Also @mjaris I can't find these tags. Are they available through page builder?

![uploads/b555b3a2-20ca-4bb3-a633-27247e8ae665/Screen Shot 2019-10-16 at 5.42.04 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb555b3a2-20ca-4bb3-a633-27247e8ae665%2FScreen+Shot+2019-10-16+at+5.42.04+PM.png)

**Comment by mjaris** [comment]
Hey Alli!

The tags are available through the page builder in a module called "Tagged Boxes" (we're not using them on the homepage currently because we couldn't verify updated versions of the stats).

Square buttons would be great as they match the branding on technovation.org, but if it's a lot of extra work it's not necessary.
