### ISSUE TITLE
Ongoing Support [8,8,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2381]
Placeholder ticket for ongoing miscellaneous support for active season, or other issues. Also handle triaging issues that arise in here.

**Comment by stenington** [comment]
Carrying over from https://github.com/Iridescent-CM/technovation-app/issues/2369#issuecomment-586367458:

We agreed that taking some time here to build a rake task to identify and fix onboarding students who should be considered onboarded, and calling it once a day on production, is a good step forward.

**Comment by rsgonzal** [comment]
#2359 describes an RA that is trying to complete her mentor training but the platform won't mark as complete.

Taking option 2: Mark this RAs training as complete and let her move on

I'll send her email on slack

**Comment by stenington** [comment]
@rsgonzal When I try to mark that RA/mentor as complete on her mentor training, I get an error that her bio is too short (minimum is 100 characters). So I think if she writes a long enough bio, she'll then be able to complete her training.

**Comment by rsgonzal** [comment]
WOW. Thanks! I will let Ophelie know.

**Comment by stenington** [comment]
Yeah, clearly the UI is not showing that particular problem correctly, but it does look like her bio is only 98 characters. 🙄 We can maybe cook up a better solution in #2359 sometime.

**Comment by rsgonzal** [comment]
Assessment team would like to look at the responses from the feedback question on the lessons.

I think this dataclip might be pulling them as comments? https://data.heroku.com/dataclips/nijeeevxjdqzsliyhddqbhaaovnl

Some of these comments have the role listed as feedback: https://www.curiositymachine.org/admin/lessons/comment/

Can we pull out just the feedback responses or the progresses with them?

**Comment by stenington** [comment]
@rsgonzal So what would be most useful here? Dataclip with username, lesson title, feedback text, and date the feedback was left? You're talking about this section, right?

![Screen Shot 2020-02-19 at 11 30 47 AM](https://user-images.githubusercontent.com/55319/74853032-5a1fca80-530b-11ea-8559-4a1706c053ba.png)

**Comment by stenington** [comment]
@rsgonzal Here's a dataclip as a starting point. Let me know if I need to change the share settings, I can't remember if the people who want to see it can see it by default: https://data.heroku.com/dataclips/wnmsvnrpstlwckkajrzpynesunmo

**Comment by rsgonzal** [comment]
Thanks, @stenington ! It's perfect. Shared with Rebecca and it's what she needs.

**Comment by shaunxp20** [comment]
Thanks for taking care of this, @stenington! 🙇

**Comment by rsgonzal** [comment]
I opened #2395 from a bug that came up. I didn't think it was that serious, but if you need something to take a look at!

**Comment by rsgonzal** [comment]
@shaunxp20 @stenington there are a group of TG girls that can no longer access their old accounts. Their schools only allows them to use their school email, but they don't have access to the actual inbox. They participated last year and can not remember their password. They asked if we could do a temporary password for their accounts so that they can get in. Second option is to delete their old accounts, so they can sign up again with the same email. 

Other thought was if we change their email address, could they then go through the password reset steps? But they may not want to use other email addresses. @ophelieh is waiting for a response.

I sent an email with their account info

**Comment by shaunxp20** [comment]
> They asked if we could do a temporary password for their accounts so that they can get in. Second option is to delete their old accounts, so they can sign up again with the same email.

I tested this locally and it looks like we can do a password reset and then grab the `password_reset_token` from the database, then we can construct and give them the password reset link/URL. The link is only valid for two hours though. We could also use the link and set a new password on their behalf and then send them the new password.

It looks like deleting the accounts would require some database surgery. The delete functionality through the admin will just soft delete them (mark them deleted as opposed to actually deleting the records).

> Other thought was if we change their email address, could they then go through the password reset steps? But they may not want to use other email addresses.

I think we could update their email addresses via the admin, and then use the normal reset password flow if we wanted to go w/ this option (I would just want to verify this first though).

Any thoughts/corrections/clarifications on this @stenington? 🤔 😀

**Comment by stenington** [comment]
Yeah, we can actually pull up the content of the sent email in Mandrill to get the link as well (avoids the construction by hand, if that's tedious), but the two hour window still applies.

I think deleting, even though it only soft deletes, does allow reuse of the same email address. Not 100% sure, but it should. But I like that idea a lot less anyway.

My preferences in order are
1. coordinate to get them the password reset links and have them use them within the two hour window
2. use the password reset links to set temporary passwords for them, email them the temporary passwords, then have them go to **My profile > Change password** and set new passwords of their choosing

I like the second option less because emailing passwords around in plain text basically means they aren't secure, and I'm guessing people generally won't bother changing it to something they choose. But it's still a better option than deleting their old accounts I think.

**Comment by ophelieh** [comment]
Hi all! Thank you for your help with this. I am trying to coordinate with the RA in Spain to work within the 2-hour window. I will let you know as soon as I hear back.

**Comment by shaunxp20** [comment]
Btw, I created a dataclip for password reset URLs. We basically just need to request new passwords for each account, and then run the dataclip. I tested the password reset URL (in the dataclip) on prod w/ a test account, and it worked as expected. So, I think we're all set for Monday, but if things go off the rails, I think @stenington said he would be there too! 😄
