### ISSUE TITLE
Allow Admin to know when an event has been created by an RA (by 3/21) [5,5,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2391]
Program team wants to know when an RA created an event.

They are giving the RAs a specified time frame for when their events can be created, but nothing prohibits them from creating an event after March 22nd.

The current plan is to download all of the events on the 22nd, and mark and events that show up after that as unofficial. 

It would be helpful to either have a time stamp of when the event was created on the event page or to prohibit the RAs from creating events after a specific date (3/22).

## QA steps
1. log in as an RA
2. create an event
3. log in as an admin
4. go to **Events**
5. add **Created at** and **Last updated at** as "More columns", and search
6. confirm the new event has the expected timestamps, and is unofficial by default
7. view that event
8. confirm that you see the timestamps here too

**Comment by hellafitz** [comment]
Other options: 
- hide the 'create new event' button. That'd mean even admins couldn't create one. 
- also validate the date on the backend

Showing timestamps option is easy but requires the program team to monitor it (which they do say they're prepared to do). Hide the button option(s) are more robust but would need additional definition. 

Q: What happens if we do want to create an event after the deadline, as a special case (which no one says will happen until it does)?

Decision: Given the timeline, we should show the timestamps on the event page and as an optional column on the list of events page, and have program team monitor the numbers of late and 'exception' events

**Comment by stenington** [comment]
I worked ahead on this one a bit, and have a potential PR. I'm not pulling it into the iteration yet though.

**Comment by stenington** [comment]
So the base change here is just showing admins the creation date (and latest update date, because that's already there as well) of events. I think another easy thing would be to default all new events to being unofficial. That way our team doesn't have to patrol for new events and mark them as unofficial after the date, they'll automatically be unofficial and only the exceptions need to get marked as official.

**Comment by nickiredescent** [comment]
Tested.
Can confirm that the time stamps are available at all the stated places and that the time columns are appearing as expected.

**Comment by rsgonzal** [comment]
Wooo. Looks good. Ophelie is still taking a look.

Question @stenington, so all events are no unofficial by default? No matter what the RPE officiality date is set to?

**Comment by stenington** [comment]
@rsgonzal I'm not 100% sure what you're asking, but here's how it works. It used to be that all events defaulted to being official, and an admin would have to change them to be unofficial. Now they're going to default to being unofficial, and an admin will have to change them to be official.

The officiality date isn't really controlling whether events are official or unofficial, they're still designated one way or the other behind the scenes. The officiality date just controls when we actually show our user which status has been set.

So in the past, if an RA created an event after the date when we asked them not to, it would be an official event by default, and our admins would have to take action to change that. With this change, an RA coming in and creating an event after the deadline will create an unofficial event by default, and our admins no longer have to patrol for that (although they still might want to check just to know that RAs are creating events late in the game, but it won't mess with scoring).

Does that make sense?

**Comment by ophelieh** [comment]
Hi all! 

Everything worked as expected. I do have a question about events automatically being marked as unofficial though. Will that happen through event creation or just for events created after March 22nd? 

Thanks!

**Comment by rsgonzal** [comment]
Awesome, thanks @stenington !

I think @ophelieh is asking the same question, so events will be unofficial throughout event creation. So when you and Nick go in on the 21st or 22nd, you will be marking appropriate events official instead of unofficial.

**Comment by ophelieh** [comment]
Ok thanks. One note is that we have way more official events (about 95% of them will be official) so we would spend a lot more time converting events to official than the other way around. But with the coronavirus who knows if there even will be events... 🤒

**Comment by stenington** [comment]
Sorry @ophelieh, didn't mean to make more work for you! If it's going to be too many events to deal with, let us know and we'll come up with something to make it manageable. It's safer to do it this way rather than letting RAs create official events by default, since that has big implications for the scores for the teams in the event.
