### ISSUE TITLE
Edit error messages for email address changes [5,5,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2406]
After #2347 -The error messages that pop up when entering personal and parent emails are a little wonky.

The multiple messages when changing the personal email are aggressive:
![Screen Shot 2020-02-28 at 2 05 02 PM](https://user-images.githubusercontent.com/22801026/75594152-a28e6500-5a3c-11ea-8cd9-4644373a7b84.png)
Trim the multiple identical error messages down to one.

The first screen that prompts you to change the parent email talks about another student account:
![Screen Shot 2020-02-28 at 2 48 44 PM](https://user-images.githubusercontent.com/22801026/75594178-b934bc00-5a3c-11ea-8b97-b5a5fada5f3c.png)
Instead it should say "cannot match your (or any other student's) email"

## QA STEPS
 * Login or impersonate a student

#### Part 1
 * Navigate to My Profile -> Change email
 * Update the email address without providing a password
 * Submit the form
 * Verify you only see one error message (not three!)

#### Part 2
 * Navigate to Parent Consent, and click Edit email address
 * Change the email address to the student's email address, or another student's email address
 * Verify the new error message reads: "cannot match your (or any other student's) email"

**Comment by stenington** [comment]
I don't have my head totally wrapped around this, but here's what I've found so far. These profile editing forms are a little complicated in that they combine fields on both the profile model and the Account model. 

When you're editing your profile (My Profile > Change your basic profile details), errors are displayed once, below the input field. 
<img width="1280" alt="Screen Shot 2020-03-20 at 5 00 26 PM" src="https://user-images.githubusercontent.com/55319/77205942-5202a880-6acc-11ea-8cac-fa9698de7438.png">

When you edit your email, errors are displayed on the label, on the field, and again below the field as shown in the original ticket. Note that it's not specific to the parental email error though. Inputting the wrong password will also give you triple error messages about that.
<img width="1280" alt="Screen Shot 2020-03-20 at 5 02 37 PM" src="https://user-images.githubusercontent.com/55319/77206120-a017ac00-6acc-11ea-9d84-b91979a9367c.png">

The main difference I see behind these two pages is that the profile page uses `simple_form_for` whereas the email page uses `form_with`. Switching the email page to use `simple_form_for` and then e.g. `a.input :email` instead of separate label, field, and errors does seem to bring the validations back in line with other pages. 

I guess the piece I don't understand is if `form_with` is supposed to add error messages everywhere so aggressively, or whether that's an indication of another underlying problem that switching to `simple_form_for` wouldn't address that we should be trying to fix here.

**Comment by shaunxp20** [comment]
This one is on the QA site, and QA steps have been added as well. 😃 👍 🌞

**Comment by rsgonzal** [comment]
I don't think this one has been updated?

![Screen Shot 2020-05-18 at 11 44 10 AM](https://user-images.githubusercontent.com/22801026/82248394-eaff4580-98fc-11ea-96fc-d30ded5902c3.png)
![Screen Shot 2020-05-18 at 11 41 24 AM](https://user-images.githubusercontent.com/22801026/82248406-ee92cc80-98fc-11ea-8ff1-ef096c03a075.png)

**Comment by shaunxp20** [comment]
> I don't think this one has been updated?

You're right! Doh! 🤦 It wasn't on QA, but it should be now! 😄

**Comment by rsgonzal** [comment]
Error messages look great! I am not being attacked anymore.

**Comment by shaunxp20** [comment]
This has been deployed to production. 😄 🤓 👍
