### ISSUE TITLE
Bug: Filtering by state(?) does not give you expected results [?,13-20,?]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2453]
**Describe the bug**
"When searching for numbers of participants in Telangana, India, it shows 0. But if I search by student name I can find the students and it shows the right location - Hyderabad, Telangana, India"

**To Reproduce**
1. Log in as admin
2. Go to participants
3. Enter India for country and Telangana for state
4. Press search

**Expected behavior**
Since there are students in this state, I would expect them to show up in the admin. 

**Additional context**
Unclear how big this problem is. Does any filtering by state work? Is it just India?

**Comment by stenington** [comment]
As a starting point, I see [this set of classes](https://github.com/Iridescent-CM/technovation-app/blob/qa/app/models/state.rb) which has a mapping for Telangana, among other places, and is used by the datagrid filtering functionality from what I can tell. In the database itself, I see Telangana as both "Telangana" and as "TG", which is probably part of the problem.

**Comment by rsgonzal** [comment]
from Ophelie: I don't think I have noticed that anywhere else, but I also haven't really used the state filter for anywhere other than India and the US

**Comment by hellafitz** [comment]
Next stepss: 
- Build a more complete description of what's happening with those classes. Figure out exactly what they're doing (normalizing going in? normalizing going out?) 
- then figure out what a solution might look like.

**Comment by stenington** [comment]
In the admin, on the **Participants** screen, when you search for a country, we're pulling the list of countries from a package called `country_state_select`, which is relying on a package called `city-state`, which in turn is getting its data about locations in the world from a company called MaxMind. 

In our database, we don't always talk about locations in the world using the same conventions as the MaxMind data, and that's where these classes come in. If you select "Spain", and then "Valencia" as State/province, then `city-state` thinks we should search the database for **state_province equal to VC**. 

The combo of `StateClauses` and `State` classes (the same set of classes mentioned earlier in this ticket) will intercept this and say instead that the database should search for **state_province equal to comunidad de valencia**.

I think the problem is much worse though, because a peek in the database shows the following:

| state_province | country |
|----------------|---------|
| Comunidad Valenciana | ES |
| Comunitat Valenciana | ES | 
| Valencia | ES |
| Valenciana | ES |
| Valencian Community | ES |
| VC | ES | 
| VC - Valenciana, Comunidad / Valenciana, Comunitat | ES |

Granted, this is not filtering down by the current season, but even doing so I see 4 different ways of expressing Valencia. 

So that's my take on what's going on here, or at least part of the picture. We're not using a single unified way of looking at the world when we're letting data in to the database, and then we're trying to query data back out assuming it will all more or less line up with MaxMind's way of expressing things. Then where it doesn't match, we have some of these types of band-aids in place, but even they aren't accounting for all the variation, and they're also never going to let us be fully on top of the issue. We will just have to keep layering more and more band-aids as more and more problems arise, many of which we may never even know about.

**Comment by hellafitz** [comment]
To tackle the root cause of our location problems, first step:
- review how we collect location data into the app in the first place, including how we deal with disputed names/locations. Goal: feed in consistent location data and reduce unneeded variation. 
- preliminary thought is be more like TF, providing a drop down for user plus options to add locations not on the list (although we're not sure what we'd do if someone provided one)

theory: move the normalization upfront, remove the normalization in the middle, get better dashboard accuracy at the end as a result. 

additional context: 
- for KPI and reporting reasons, location classification should be the same across both TF and TG
