### ISSUE TITLE
Spike: Understand what certificate templates are needed & how to set them up [8,13,0.62]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2470]
Marketing team has provided some certificates, but they are not all of the certificates the platform distributes. Also, Mike tried to input one of the certificates locally and it was not able to be generated `RuntimeError (PDF is not editable)`

The different certificates the app generates are here: https://github.com/Iridescent-CM/technovation-app/tree/qa/lib/certs/2020

Some documentation of certificates here: https://docs.google.com/document/d/12DZ5R1l2DiruHpWelABJfU_0Luroz0yatSGKgYfE4ms/edit

Deliverables for this ticket:
- Figure out what kind of templates we need from the marketing team
- Provide them with fields the certificates can be populated with or ask for them to be exactly the same as last year
- Communicate with team if this is doable
- Identify any changes that need to be made 

## QA

**For student certificates**
1. Log in as an admin
2. Search for **Profile type: Students**, **Team Matching: Matched with a team**
3. Choose any student from the results and view
4. Generate one each of the available certificates: participation, completion, and semifinalist
5. Use the "See certificate" links that appear under **Current certificates** to view the actual certificate for each (you may need to refresh the page to see them all)
6. Confirm each certificate is correct, visually and information-wise

**For mentor certificate**
1. Log in as an admin
2. Search for **Profile type: Mentors**, **Team Matching: Matched with a team**
3. Choose any mentor from the results and view
4. Generate one or more mentor appreciation certificate(s) for the mentor
5. Use the "See certificate" link(s) that appear under **Current certificates** to view the actual certificate(s) (you may need to refresh the page to see them all)
6. Confirm each certificate is correct, visually and information-wise

**For judge certificates**
1. Log in as an admin
2. Search for **Profile type: Judges**
3. Choose any judge from the results and view
4. Generate one each of the available certificates: judge advisor, head judge, and certified judge
5. Use the "See certificate" links that appear under **Current certificates** to view the actual certificate for each (you may need to refresh the page to see them all)
6. Confirm each certificate is correct, visually and information-wise

**Comment by stenington** [comment]
8 may end up being a bit small for all of this, but it gets us started.

**Comment by stenington** [comment]
My ideal outcome for this ticket would be updating [this certificate documentation](https://docs.google.com/document/d/12DZ5R1l2DiruHpWelABJfU_0Luroz0yatSGKgYfE4ms/edit) with info on how to update the certificate templates from year to year in a way that delineates developer and non-developer pieces clearly. Off the top of my head, that would need to address:

* the structure and requirements of the `lib/certs/` directory (this year I think I just duplicated the 2019 directory as 2020 at the season switchover, because nobody wanted to think about actually updating the templates at that time)
* how to create a new certificate template
    * what do you have to do to make it editable?
    * how do you put fillable fields into it? how are they named?
* how the `full_text` method factors in to things ([see here](https://github.com/Iridescent-CM/technovation-app/blob/qa/lib/fill_pdfs/completion.rb) for an example)
    * (I assume interpolating the content that way has to do with sizing the text to fit the available space, but I'm not certain of that.)
* what creative flexibility does a designer have when making a new template? When do they need to coordinate with a developer on changes, or what can they change in a template without it mattering to us?

I would prefer to do away with [this kind of thing](https://github.com/Iridescent-CM/technovation-app/blob/qa/lib/fill_pdfs.rb#L102) that we're doing currently to clean up messy data, and rely instead on agreed upon naming conventions between the designer of the pdf and us as well.

**Comment by stenington** [comment]
@rsgonzal how fast can we get mockups for all 7 types of certificates, so we know exactly what we're dealing with in terms of the data that needs to be filled in?

**Comment by stenington** [comment]
@rsgonzal Here's a document that shows each 2019 template, the size of the fillable areas, and the content that will go in there based on the current code: https://docs.google.com/document/d/1UpqRnLtqef11zq4FvqEt9gG0U-n_jonMOyrpNA8Zj3E/edit#

**Comment by rsgonzal** [comment]
Thanks, mike! sent this over to the team to gather their thoughts.

**Comment by rsgonzal** [comment]
here are new templates: https://www.dropbox.com/sh/a3ubttjvx5oh64o/AAC8VLn3KF7bJqNbm172Ry7xa?dl=0

Notes:
- semifinalist certficate needs to be updated, there was some confusion
- fonts have changed
-placements have changed

**Comment by stenington** [comment]
It looks like fonts aren't being embedded into the pdfs in a usable way. 

The problem might be that fonts are getting embedded as subsets, which means literally only the characters being used in the template get embedded. Because these are fillable pdfs, we would need the full font embedded, if that's possible.

Another possibility is just that embedding fonts is flaky and won't work for us. I can open the same template in three different programs on my computer and have the fonts handled in three different ways:
* in Preview they disappear from fillable fields immediately
* in PDFpen they disappear on save
* in Adobe Reader they stay (but it's read-only software)

@rsgonzal If possible can we get at least one of the templates with the full fonts embedded to see if that works?

**Comment by rsgonzal** [comment]
@stenington i'll share this with audra and see what she says!

**Comment by rsgonzal** [comment]
> pulled up the font properties on the files - I'm pretty sure the entire fonts are embedded for fields which are fillable. For example, on the Certificate of Completion, font subsets (just the characters used) are embedded for areas that are not fillable, but the entire TrueType font appears to be embedded for the fillable fields:
full_name -> RubikMonoOne (Embedded) TrueType 
full_text -> Poppins-Bold (Embedded OpenType)
I've dropped a screenshot of what I'm seeing below, but let me know if this doesn't make sense. I can say that these are prepared the same way as all variable data templates that I've had sent to vendors for nametags and certificates in the past, as well as the Technovation platform, but perhaps something has changed with the software, or I missed something.

<img width="1172" alt="Screenshot 2020-04-16 19 54 36" src="https://user-images.githubusercontent.com/22801026/79780238-72eb3300-82f0-11ea-9fac-9713497d0cdd.png">

**Comment by rsgonzal** [comment]
not sure if this helps:
> That's weird about the fonts not being fully embedded in certain programs. Adobe Reader should be able to edit these - they have Reader extended tools enabled including form fill in & save.

**Comment by stenington** [comment]
Ok, so let's just put on staging what I have, and get a temperature check on how good/bad it currently looks. It's not using the intended fonts in the fillable fields, but we may just have to accept that limitation.

**Comment by stenington** [comment]
Actually, @rsgonzal let me first try putting the new templates directly on staging without opening them in Preview first. They don't work on my computer, but maybe they will actually work on staging. If not, then I'll put the versions up the way I fixed them locally.

**Comment by rsgonzal** [comment]
Ok, cool. Should we generate certificates tomorrow then? Is there any reason the templates would work differently? Wondering if we should test all the different certificates or if testing just the student one would be fine.

I'll need to set up some judges tomorrow if we test them all.

**Comment by stenington** [comment]
Yeah we'll want to generate all the certificates. I added QA steps in the ticket description above for how I would do that.

**Comment by stenington** [comment]
This work can be continued in #2482
