### ISSUE TITLE
Use Dotenv to require certain configuration settings [13,5,?]

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#2502]
Background: the library we're using for our configuration settings is called [Dotenv](https://github.com/bkeepers/dotenv).

To ensure our configuration settings are setup correctly we can use Dotenv's built-in functionality to require certain configuration settings, from the [Dotenv GitHub page](https://github.com/bkeepers/dotenv#required-keys):
```
# config/initializers/dotenv.rb

Dotenv.require_keys("SERVICE_APP_ID", "SERVICE_KEY", "SERVICE_SECRET")
```

In #2394, I was able to prove out that the CirceCI build/deploy will fail if a required configuration setting is missing, and that QA/staging will still work as expected. I also proved out locally that we can raise an exception for missing configuration **values**, with something like:
```
if Dotenv.parse("SOME_CONFIGURATION").empty?
  raise "MISSING CONFIG!"
end
```
One note/potential gotcha about requiring and checking values for `ENABLE_*` configuration settings is that these configuration settings could be missing and it would be okay, because missing would be the same as disabled/off/false in this case.

As far which configuration settings are required. I did a quick assessment:
 * there are about 130 settings that are the same on both Prod and QA
 * there are about 20 that are on Prod and not on QA
 * there are about 15 that are on QA and not on Prod

Some of them are expected, like `HEROKU_*` ones, but for others it's not so clear as to why there's a discrepancy.

Some thoughts on deliverables that ideally we'd figure out before working on this one:

One approach forward/deliverable for this ticket would be to just use the list of ~130 settings. And then we could adjust our local `.env` file locally. And we could use #2399 to remove unnecessary settings, and also use it to address the discrepancies too, or perhaps that should be another ticket? Seems like a blocker for this one if we try to incorporate it here.

**Comment by hellafitz** [comment]
blocked until #2509 is complete (assessing the current environment variables)

**Comment by stenington** [comment]
A bunch of this was said in planning last time, but jotting it down:

To me there are two main benefits to this kind of config validation:
1. if we're careful about it, it could help catch the "added new required config and forgot to set it in production before deploying" type of bug we've seen now and again
2. it could help someone setting up the project for the first time figure out what they need in their .env (or just help them realize they should ask another dev for their .env)

To that end, I don't think it's appropriate to use the 130 variables common to QA and prod, because that would include config like keys for add-ons that only make sense in a Heroku environment, but not locally.

We also have config variables that already have defaults, like `WEB_CONCURRENCY` or `ACTIVE_JOB_BACKEND`. I'm personally fine leaving that kind of thing out of an initializer since the app does not require it to be specified to run (although we could debate whether we have sensible defaults in place for some of them). 

And then finally we have plenty of unused config that we're trying to deal with in #2509, but I don't think we should be adding anything as required config in an initializer without knowing what it does. I think that will set a precedent of "when in doubt, pretend it's required" rather than a precedent of "when in doubt, stop and figure out what the config does". This seems like a "[if it hurts, do it more often](https://martinfowler.com/bliki/FrequencyReducesDifficulty.html)" type of thing to me. Reviewing our config for relevance hurts, so we should probably be doing it more frequently so it starts hurting less.

**Comment by hellafitz** [comment]
Added 'off-season' tag to reflect expected timing for #2509, which this issue is dependent on

**Comment by stenington** [comment]
QA here is basically just making sure it deploys correctly, and the new environment checks don't blow up on staging or production. It was okay on staging.
