### ISSUE TITLE
Spike: Bring back the demo video for for submission and judging [13,8,1.63]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2605]
Team ranked the demo video as a high priority for the next year. 

- Research how to add it back on submission screens
- Figure out how to add it back to judging screens
- What are the data implications
- surface implications and key decisions that need to be made by PT/CET

**Comment by shaunxp20** [comment]
To prove out I was able to bring back the demo video, I basically had to do it. 😅 I have a WIP/spike PR (#2609) that has what I have done so far.

In order to get the demo video back, I just reverted the commits in these PRs:
#2256 demo video clearout
#2253 remove demo video from admin/ra UI
#2255 Remove demo video from judge screens
#2254 remove demo video from student/mentor UI

It was a little tricky to figure out which parts of each PR were necessary b/c it looks like there were quite a few unrelated changes, like all these files were removed but they don't seem to be related to the demo video?:
```
app/views/student/team_submissions/_affirm_integrity_form.html.erb
app/views/student/team_submissions/_app_description_form.html.erb
app/views/student/team_submissions/_form.html.erb
app/views/student/team_submissions/_progress.en.html.erb
app/views/student/team_submissions/_progress_bar.en.html.erb
app/views/judge/submission_scores/_entrepreneurship.en.html.erb
app/views/judge/submission_scores/_ideation.en.html.erb
app/views/judge/submission_scores/_overall_impression.en.html.erb
app/views/judge/submission_scores/_pitch.en.html.erb
app/views/judge/submission_scores/new.en.html.erb
```

It seems there are about half a dozen ways the demo video shows up, I tested a few of them locally and haven't run into any issues.

Here's what it looks like from a student's perspective:
<img width="1324" alt="Screen Shot 2020-08-20 at 1 48 22 PM" src="https://user-images.githubusercontent.com/58957909/90828140-0418f780-e32d-11ea-86e1-73315f5882d9.png">

From a judge's perspective:
<img width="1321" alt="Screen Shot 2020-08-20 at 3 27 10 PM" src="https://user-images.githubusercontent.com/58957909/90828380-6d990600-e32d-11ea-8c06-fe7782df9791.png">

From the admin:
<img width="1292" alt="Screen Shot 2020-08-20 at 2 35 55 PM" src="https://user-images.githubusercontent.com/58957909/90828235-3591c300-e32d-11ea-8d7b-e8f89abec5ca.png">

I'm about 75-80% confident w/ the spike PR, given I haven't tested everything, I don't know what it looked like before, and I had to handpick which files/changes to bring back which means I might have missed something. 😃 

Anywho, for the purpose of this spike: - yes, it's possible! But needs more testing to make sure it's all working correctly.
Data implications:
there was only one database change I made - the `demo_video_link` had to be added back to the `team_submissions` table
Implications and key decisions that need to be made by PT/CET:
I see a PR, "#2252 make demo video an optional part of submissions", which implies the demo video was required before and then it was optional. Anywho, we could verify if it should be optional or required. And maybe just verify the ordering/wording around the demo video. Other than that, I'm not really sure. 🤔

**Comment by stenington** [comment]
I would propose that PT/CET also needs to decide whether or not to delete old submissions. If the demo video is optional, it will just look like nobody in 2020 chose to submit one to a naive viewer, which maybe isn't a huge deal, but if it's required someone without context might wonder how all of our 2020 participants managed to get away without any demo videos if they were trying to look backwards and figure out something about the past.

**Comment by hellafitz** [comment]
Reportback for PT:
- Yes, it's possible
- Decision needed on whether or not it should be a required part of submissions
- Decision needed on whether or not to delete old submissions (especially if Demo Video will be required for 20/21)

**Comment by rsgonzal** [comment]
Opened #2739 for implementation
