### ISSUE TITLE
Remove Judge and Chapter Ambassador sign up options from Content & Settings [5,5,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2615]
It is confusing to see the options to turn on judge & CA registrations in content & setting. Checking these boxes does not do anything. Checking the box for judge and nothing else actually leaves registration open for students and mentors.

Remove these two options from this view.
![Screen Shot 2020-08-27 at 9 33 13 AM](https://user-images.githubusercontent.com/22801026/91469568-664f8c00-e848-11ea-8dc2-707cc16b9a7f.png)

## QA STEPS

* Ensure Judges and Chapter Ambassadors are no longer displayed in the User Registrations section

**Comment by hellafitz** [comment]
Create new ticket for any substantial follow-on work resulting from this removal

**Comment by shaunxp20** [comment]
I started to remove the code outside of the admin, but I was spending too much time on it and felt the scope was getting too big for this ticket. Also, I think there will be more testing effort involved when we remove the remaining code.

Anyhow, the new ticket to remove the outstanding code is #2627.

**Also, important note:** since we're removing these options, and there will still be code (not in the admin) that references these options, the last value that is set will still be referenced/used. Supposedly this code doesn't do anything, so just more of an FYI. 😃

**Comment by shaunxp20** [comment]
This one is on the QA site, and some basic QA steps have been added as well. 😄 👍

**Comment by ophelieh** [comment]
<img width="1440" alt="Screen Shot 2020-09-10 at 8 17 54 AM" src="https://user-images.githubusercontent.com/32206421/92734409-22777f00-f33e-11ea-80af-a81368acbe6a.png">
Hi all! This works great. As an admin, I no longer see Judges or Chapter Ambassadors on the registration tab.

**Comment by shaunxp20** [comment]
Thanks for looking at this, @ophelieh! 😄 🎊

**Comment by ksrebecca** [comment]
same, looks good!

**Comment by shaunxp20** [comment]
Great! Thanks for looking at this @ksrebecca! 🎉 😄 🌞
