### ISSUE TITLE
Update Parental Consent form on TG [40,13,3.1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2640]
Update parent consent form on TG for 2021

- Replace the version that gets signed electronically
- Replace the version that gets downloaded

New form: https://docs.google.com/document/d/1c_H7TJn_KSgU9v5VaioXOS_VcTwNYHsxxz-tvj1slUs/edit?ts=5f4e623f

## QA STEPS

* Register as a new student, and then find/download the parental consent form via the link: "Download the permission form"
* And then verify the content changes including the pre-filled sections (for student name, etc.) at the bottom of the form

Also, here are the changes I made for the parental consent form, maybe it'll help for verifying the content changes 🤷 😃 :
https://github.com/Iridescent-CM/technovation-app/pull/2703/files

**Comment by rsgonzal** [comment]
@shaunxp20 this one is ready

**Comment by shaunxp20** [comment]
This one is on QA, some basic QA steps have been added as well. 😃 🌞

**Comment by ksrebecca** [comment]
QA - verifying that the updated form is the one available, and that the correct student name and email address populate in the form. But it looks like when making this version maybe the text is a bigger size or the margins got enlarged, so the text falls strangely on them notably in 2 places:

1. The signature of "Technovation Staff" falls on the 2nd page instead of the first - is there a way to reduce font size or decrease margins so that is not the case?
<img width="716" alt="Screen Shot 2020-10-01 at 9 31 11 AM" src="https://user-images.githubusercontent.com/43972336/94830570-f1ccb780-03c8-11eb-8509-e78400493bf6.png">

2. The last page where the parent signs is cut off from the all caps "I agree" section. Ideally, this could be on the same page. But the bare minimum would be to have the fields with student name and email, parent name, parent signature all on the same page.
<img width="736" alt="Screen Shot 2020-10-01 at 9 27 52 AM" src="https://user-images.githubusercontent.com/43972336/94830754-22145600-03c9-11eb-8b54-9333c21a00c7.png">

**Comment by kate-technovation** [comment]
Sorry it took me so long to test! 

1. I created an account. Unlike past recent times creating an account, I was _not_ prompted to enter my parent's name and email address during sign up.

2. Instead, after creating my password, I jumped straight to my student dashboard. While there was a message stating I needed parental screen on the screen, there were no directions as to where to find that information:
<img width="892" alt="Screen Shot 2020-10-02 at 6 07 04 PM" src="https://user-images.githubusercontent.com/57409606/94973719-66dbe200-04da-11eb-9a58-adba0c6fd6d0.png">

3. Navigating based on what I can remember (not on what I read on the platform) I went to my profile to find the Parental Consent section, and clicked to download the form:
<img width="905" alt="Screen Shot 2020-10-02 at 6 07 12 PM" src="https://user-images.githubusercontent.com/57409606/94973720-680d0f00-04da-11eb-9117-fc7cfbac024b.png">

4. After downloading the form, I was able to view it, and see that my student name and email address were pre-populated on the second to last page:
First page of form:
<img width="899" alt="Screen Shot 2020-10-02 at 6 07 24 PM" src="https://user-images.githubusercontent.com/57409606/94973723-680d0f00-04da-11eb-8cd9-3c5119ef986b.png">

Second to last page of form:
<img width="888" alt="Screen Shot 2020-10-02 at 6 07 33 PM" src="https://user-images.githubusercontent.com/57409606/94973725-693e3c00-04da-11eb-9439-db9e70aaf9fb.png">

I'm not sure if I missed an earlier conversation, but did you guys purposely change the step in sign up where a student enters their parent's name and email address? If so, why?

**Comment by shaunxp20** [comment]
> 1. The signature of "Technovation Staff" falls on the 2nd page instead of the first - is there a way to reduce font size or decrease margins so that is not the case?

Thanks for the thorough review Rebecca! 😃 🙌 I'm working on a change now that will reduce the font size just slightly to make the "Technovation Staff" line appear on the first page. And then we'll force a hard break to make the next section always appear on a new page.

> 2. The last page where the parent signs is cut off from the all caps "I agree" section. Ideally, this could be on the same page. But the bare minimum would be to have the fields with student name and email, parent name, parent signature all on the same page.

Similarly, we'll force a hard break so that the: "BY SIGNING, I ACKNOWLEDGE THAT I HAVE READ AND UNDERSTOOD..." section and the signature lines will always appear on a new/the same page. I'll let you know when it's back on QA/staging. 😄 🌞 🌻

**Comment by shaunxp20** [comment]
Thanks for taking a look at this Kate, I appreciate it! 😄 🙇 🍰 🎉 

> I'm not sure if I missed an earlier conversation, but did you guys purposely change the step in sign up where a student enters their parent's name and email address? If so, why?

It looks like the "Scores & Certificates Accessible" setting is enabled on QA, I think that's why the flow is a little different regarding the parental consent form. I just turned the setting off, so I think it should be good/have the normal flow now. 😄 🤔

**Comment by shaunxp20** [comment]
This one has finally made it back to QA, it's ready for another looksie. 😄

**Comment by ksrebecca** [comment]
Yay! I just checked and it's looking great 🎉 Thanks for those changes!

**Comment by shaunxp20** [comment]
> Yay! I just checked and it's looking great 🎉 Thanks for those changes!

No problem, glad it looks okay! 👍 🙌 🎉

**Comment by rsgonzal** [comment]
I  checked the electronic version as well and it also looks to be updated!

**Comment by shaunxp20** [comment]
> I checked the electronic version as well and it also looks to be updated!

Awesome, thank you! 👍 😄 🎊
