### ISSUE TITLE
Epic: Update judging rubric content [40,3,13.3]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2657]
Point allocations are remaining the same, but the descriptions of each category criteria are updated. 

Mock ups: https://projects.invisionapp.com/freehand/document/LhQkl9QW3

### Deliverables
- Update judging rubric: https://docs.google.com/spreadsheets/d/1DW5TJO3kaGum6ntFEIzpy--NLlQjEQ1wu2aspiUts_4/edit#gid=0

## QA STEPS
- Turn on judging in the admin
- Login/impersonate a judge, then start judging a submission, make sure the questions/content look good!

**Comment by stenington** [comment]
How does the table referenced map to our judging screens? Remember, they look like this:

![Screen Shot 2020-09-17 at 2 55 55 PM](https://user-images.githubusercontent.com/55319/93515054-ff2c7100-f8f5-11ea-8c29-8359c3a01dfa.png)

Are we replacing the current descriptions with the leftmost column of the doc? So e.g. "The team has a strategy to bring the app to market." becomes "Feasible Marketing Plan"?

**Comment by hellafitz** [comment]
Part of this is replacing the pdf links to the rubric - and finding where those are (if anywhere other than the drop down resources menu). 

The other part is the issue Mike raised above. @bagomer @ksrebecca we need replacement text for what the Judges see, aligned with the new rubric.

**Comment by ksrebecca** [comment]
Correct. Judy is going to be leading this but we're not planning on working on this particular piece until November since it doesn't need to go live until January. See current line 49 [here](https://docs.google.com/spreadsheets/d/1zG8tlBQ_M1hAFEkMnVmS8sBFqCisAaKTsn9IH1NMO4U/edit?ts=5f6b7229#gid=90169811).

**Comment by rsgonzal** [comment]
https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-20210-Judging-Rubric.pdf

**Comment by hellafitz** [comment]
Here are the proposed text updates from the PT https://docs.google.com/spreadsheets/d/1DW5TJO3kaGum6ntFEIzpy--NLlQjEQ1wu2aspiUts_4/edit#gid=0

I mocked up what the new text for the Entrepreneurship section would look like. @ksrebecca please confirm this is the right track.

**Comment by ksrebecca** [comment]
Confirming! Correct vision

**Comment by hellafitz** [comment]
We should build in some extra QA time since I strongly suspect that seeing the longer text on the judging screens will result in revisions.

**Comment by hellafitz** [comment]
Once it's on the actual site for QA I suspect the way forward will present itself. Mystical, I know...

**Comment by shaunxp20** [comment]
This one is on QA, some QA steps have been added too! 👍 😄

**Comment by rsgonzal** [comment]
@shaunxp20 I think this sentence is meant to be the help text throughout the sections

"To determine if the team has built a solution that will positively impact them and their community, refer to all submission materials and the rubric."

I'll let someone from the team confirm

**Comment by rsgonzal** [comment]
notes from @Judith-Ahumada 
- judy is checking in on the help text language from above
- she likes how the old sentences include only pieces of the rubric (going to see who can get image links from tc.org)
- In the judging rubric, pitch comes before technical - is that a complicated ask to switch those two in the view? (not a confirmed direction, wondering)

**Comment by ophelieh** [comment]
The descriptions look good! 

There is an error on the "Technical" page -- the link to the rubric shows the outdated version (it said pitch video instead of demo video) 
<img width="1440" alt="Screen Shot 2021-03-22 at 8 33 59 PM" src="https://user-images.githubusercontent.com/32206421/112079313-f12e0600-8b4d-11eb-894e-c38d688e65e7.png">

Should be this instead (can be found at this link - https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Judging-Rubric-FINAL.pdf) 

![image](https://user-images.githubusercontent.com/32206421/112079566-68639a00-8b4e-11eb-8251-c99daa9866cc.png)

Same for the pitch link to the rubric. Brings you here 

<img width="1326" alt="Screen Shot 2021-03-22 at 8 39 29 PM" src="https://user-images.githubusercontent.com/32206421/112079813-cdb78b00-8b4e-11eb-8c34-a69f0ba41c4b.png">
 
But should show this or link directly to the rubric (https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Judging-Rubric-FINAL.pdf) 
<img width="1031" alt="Screen Shot 2021-03-22 at 8 39 50 PM" src="https://user-images.githubusercontent.com/32206421/112079847-df992e00-8b4e-11eb-8dfb-4c300113ab8c.png">


And for overall impression. It shows this - https://technovationchallenge.org/wp-content/uploads/2019/10/Overall-Impression.png instead of this - https://technovationchallenge.org/wp-content/uploads/2020/09/Technovation-Girls-2021-Judging-Rubric-FINAL.pdf

**Comment by shaunxp20** [comment]
>     * In the judging rubric, pitch comes before technical - is that a complicated ask to switch those two in the view? (not a confirmed direction, wondering)

Should be on the simpler side to reverse those. 😀 🤞

**Comment by rsgonzal** [comment]
thanks @ophelieh ! Judy is going to bring this up in the technovation meeting tomorrow. Do you know how to upload images on the tc.org site to get those links?

**Comment by rsgonzal** [comment]
@nickiredescent let me know when you can get us the links for the new pieces of the rubric. By Monday would be ideal.

Going to keep this sentence, but the rubric will link out to a different piece of the rubric depending on the page

"To determine if the team has built a solution that will positively impact them and their community, refer to all submission materials and the rubric."

**Comment by nickiredescent** [comment]
Here we go!

[Ideation](http://technovation.staging.wpengine.com/wp-content/uploads/2021/03/ideation.png)
[Entrepreneurship](http://technovation.staging.wpengine.com/wp-content/uploads/2021/03/Entrepreneurship.png)
[Technical](http://technovation.staging.wpengine.com/wp-content/uploads/2021/03/Technical.png)
[Pitch](http://technovation.staging.wpengine.com/wp-content/uploads/2021/03/Pitch.png)
[Overall](http://technovation.staging.wpengine.com/wp-content/uploads/2021/03/Overall.png)

**Comment by ophelieh** [comment]
Looks great!
