### ISSUE TITLE
Allow students and mentors to cancel their team join requests [20,20,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2660]
As a student, I want to be able to cancel my request to join a team so that I can move on and find another team.

Problem:
- Girls would write to us if they requested to join a team, and that team did not accept their invitation; the girls requesting to join could not ask to join other teams until the original team requested, rejected them

![Screen Shot 2020-09-16 at 5 24 21 PM](https://user-images.githubusercontent.com/22801026/93405331-879d0a00-f841-11ea-9e6a-5447f09c06a8.png)

## Suggested QA

Things to test:
1. you can cancel your request as a student
2. you can cancel your request as a mentor
3. as a team member already on the team, if you follow the link you get emailed **after** the requestor has cancelled, you see the "Sorry, but..." page
4. the "Manage my team" button works on that page as a student
5. the "Manage my team" button works on that page as a mentor

Other things to maybe think about: @rsgonzal 
6. I haven't looked at what this looks like when team building gets turned off? Do we need any special accommodation there?
- Send a request and turn off team building
- Login as the student that sent the request and go to find my team (ideally would be told they can't participate anymore)
- Login as a student that received a request. Try to accept the request from the email (request should be expired or should not be able to add to team anymore)

7. Does join requests show up somewhere else I'm not thinking of? Can you track them in the admin or anything? Does that all still work appropriately?
- After doing 1-6 above, login as admin and go to the team page and review the join requests section - did everything get recorded?

**Comment by rsgonzal** [comment]
Proposed solution:
1. Standard red button: "Cancel my request to join this team"
2. Standard pop up: "Are you sure you want to cancel this request?"
![Screen Shot 2020-09-16 at 5 54 00 PM](https://user-images.githubusercontent.com/22801026/93407566-60493b80-f847-11ea-994e-7a87ee9cceb5.png)
![Screen Shot 2020-09-16 at 5 54 13 PM](https://user-images.githubusercontent.com/22801026/93407586-69d2a380-f847-11ea-9949-36d0c5b69996.png)

@ophelieh @kate-technovation how does this look?

**Comment by ophelieh** [comment]
It looks great. Thanks @rsgonzal!

**Comment by rsgonzal** [comment]
- if they cancel, can they re-request from the same team (YES)
- if they cancel, what does the team see if they click on outdated request (Need to check email flow)

**Comment by stenington** [comment]
This one has open questions [here](https://github.com/Iridescent-CM/technovation-app/issues/2660#issuecomment-695004277) that need answers before it can be built.

**Comment by hellafitz** [comment]
On the second Q, I don't know. We still need to confirm current behavior. To the third, I'd expect that clicking the link in their email would send them to their My Team dashboard, and I think we should use the green message bar to show "This request to join your team has been withdrawn and is no longer active." (or something similar, if anyone has edits).

**Comment by rsgonzal** [comment]
> * if they cancel, what does the team see if they click on outdated request (Need to check email flow)

![screencapture-technovation-qa-herokuapp-student-join-requests-MNTHFU53txXe21Pc8xdJLx1q-2020-09-22-12_29_43 (1)](https://user-images.githubusercontent.com/22801026/94058894-823a4500-fd96-11ea-9f97-722d1fb06894.png)

**Comment by hellafitz** [comment]
Deliverables:
- Allow students to cancel their requests to join teams
- Allow mentors to cancel their requests to join mentors
- For the 'missing request' screen above, leave the text unchanged for now but add a green button that says "Manage my team" and takes you to My Team

**Comment by stenington** [comment]
The red button seemed a bit overbearing, so I'm currently following the pattern for deleting invites. But that can be changed to put the red button in if needed:

![Screen Shot 2020-09-30 at 1 02 00 PM](https://user-images.githubusercontent.com/55319/94716643-28e58f00-031d-11eb-85c4-387c562cc395.png)
<img width="1280" alt="Screen Shot 2020-09-30 at 1 00 13 PM" src="https://user-images.githubusercontent.com/55319/94716683-3569e780-031d-11eb-84cc-480985da00cd.png">

**Comment by stenington** [comment]
Draft PR is open as #2708

**Comment by rsgonzal** [comment]
I like it!

**Comment by stenington** [comment]
I started working up QA suggestions and hit a few questions. @rsgonzal I think I could use your input please.

**Comment by rsgonzal** [comment]
> * I haven't looked at what this looks like when team building gets turned off? Do we need any special accommodation there?

Do you mean like if there are pending requests and they get turned off?

**Comment by stenington** [comment]
I'm not sure what you mean by "they get turned off", but when team building is off, we certainly don't want anyone able to **accept** requests and change their team. I'm not sure it matters if a user can cancel their join requests since it won't change the members of any team to do so, but I'm just flagging that I haven't given those kinds of things a lot of thought.

**Comment by ophelieh** [comment]
**STUDENT SIDE**

* As the student Stella Noir, I canceled my requested to join a team. It worked as expected. 

* As a student from the team with the request - If I click on the email from the request that was puled. I get to the following page.

<img width="1440" alt="Screen Shot 2020-10-05 at 4 08 30 PM" src="https://user-images.githubusercontent.com/32206421/95132254-1906ea00-0725-11eb-9ad1-61ea1a3a13c2.png">

If the student sends a new request, I receive an email and am able to see her. The manage my team button works well, but I get the issue below (see side note). All my students even with complete profiles are marked as pending with no reason why. See team Cacao. 
<img width="1440" alt="Screen Shot 2020-10-05 at 4 11 18 PM" src="https://user-images.githubusercontent.com/32206421/95132449-68e5b100-0725-11eb-9ee7-b6cdcecabc47.png">


SIde note, I get the weird pending students bug with no reason for why the profile is pending. 
![Screen Shot 2020-10-05 at 4 17 07 PM](https://user-images.githubusercontent.com/32206421/95132990-37b9b080-0726-11eb-96c3-09f45dcda46b.png)



If I remove myself from the team after joining and try to use the email to log back in the team, I get the right error message. 

<img width="1440" alt="Screen Shot 2020-10-05 at 4 18 55 PM" src="https://user-images.githubusercontent.com/32206421/95133145-78b1c500-0726-11eb-9243-28c881f19517.png">

AFTER turning off the team forming option. 

* For the student with the pending request - she was no longer able to see her team request. It showed that this feature is disabled. 
* As a student from the team with the request, I clicked on the link in the email and was able to approve her. It did show me at the bottom in a very small font that I was no longer able to add other students. 
![Screen Shot 2020-10-05 at 4 29 50 PM (2)](https://user-images.githubusercontent.com/32206421/95134177-0346f400-0728-11eb-859e-ee8bd3a739fc.png)

**ADMIN SIDE**

* You cannot see pending requests unless you log in the profiles - except for mentors if you go to "Participants", "Team matching (students & mentors only)" and select "Mentors with open join requests to teams". It does seem to show mentors who have not completed training & thus cannot be added to a team. 
* I am still able to add mentors and students to team from the profile debug section - before and after closing team forming (which is ideal since we have to make some changes after those settings are closed for participants).

**Comment by nickiredescent** [comment]
Tested as both a mentor and a student (no notable difference).

Steps 1 and 2 work as expected.

Step 3
When following the email link after the request has been revoked, I see this screen:
![image](https://user-images.githubusercontent.com/45576078/95187504-17b6db00-0780-11eb-8c80-e5efea714151.png)

I do not see the "Pending Students" issue like Ophelie.

Step 4 and 5 work as expected.

Step 6
When Team Building is turned off.
The student who requested can no longer see the request in their dashboard.
The team who received the request is still able to approve/decline the request.

Outside of what Ophelie has already stated, I cannot think of another way to view/track this process as an admin.

**Comment by rsgonzal** [comment]
so it sounds like a team is still able to accept a request after team building is closed. We probably don't want to allow that @ophelieh @nickiredescent ?

But i'm also assuming this is how it currently works anyways....

**Comment by rsgonzal** [comment]
deleted requests are being recorded in the admin.

A student can still be accepted onto a team after team building is closed. Not sure if it's intended to work like that - will add to meeting notes. 

Will look into Ophelie's pending student problem and see if it's similar to what i've been experiencing.

**Comment by ophelieh** [comment]
Yes, once the team accepted, the student was then on the team. I don't think this will happen often though as we close team registration at the same time we close submissions.
