### ISSUE TITLE
X Bug: Students can request to join multiple teams or create a new team after they've already asked to join a team

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2661]
**Describe the bug**
As a student, I can ask to join multiple teams or overwrite my request by creating a new team.

**To Reproduce**
1. Go to 'participants'
2. Search for students and North Dakota
3. Login as that student
4. Go to find your team, see there are multiple requests
5. Go to create your team, you can create a team or find more teams

**Expected behavior**
This "create your team" tab should no longer be available if they have a request out already

**Screenshots**
![Screen Shot 2020-09-16 at 5 39 08 PM](https://user-images.githubusercontent.com/22801026/93406276-17dc4e80-f844-11ea-9dff-93111ee0574a.png)
![Screen Shot 2020-09-16 at 5 38 17 PM](https://user-images.githubusercontent.com/22801026/93406278-1a3ea880-f844-11ea-9ab8-03e599de1182.png)

@ophelieh @kate-technovation does this sound like the behavior we discussed?

**Comment by rsgonzal** [comment]
We want to fix this bug and do #2660 for a smoother request flow

**Comment by stenington** [comment]
I'm tripping a little bit over this being reported as a bug. I think that students being able to ask to join many teams or ultimately just create their own was the intention when the feature was built. My recollection is that we jump through some hoops in the code to make that possible, and to remove the other join requests when one of them is finally approved or the user decides just to start their own team.

It's fine that we're talking about changing this, but I would like to see a more careful consideration of the new feature before starting work.

**Comment by hellafitz** [comment]
In discussion we agreed that this isn't actually a bug, because the original intent was for students to be able to make multiple requests to join a team at the same time. 

Assuming that's settled, the one thing that jumps out at me is the issue of whether or not existing requests should be cancelled automatically when a student who has one or more requests out creates their own team. Related, should a student who has a team be able to extend requests, or do they need to remove themselves from their team first?
