### ISSUE TITLE
Add SDGs or other themes to team descriptions [13?,x,x]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2680]
When speaking to Tanya (mentor from India), she mentioned it would be helpful to know what field the team would be working on. Currently you can only put a team description, but it would be helpful to choose a topic you plan to work on.

Q: Do we still use SDGs or what is the best categorization?

![Screen Shot 2020-09-18 at 12 34 29 PM](https://user-images.githubusercontent.com/22801026/93637974-580a1100-f9ab-11ea-95cf-86df78d78362.png)
![Screen Shot 2020-09-18 at 12 40 55 PM](https://user-images.githubusercontent.com/22801026/93638488-3e1cfe00-f9ac-11ea-8df3-012af568e08e.png)

Display this followup #2681

**Comment by stenington** [comment]
So in your mockups, you're showing a form that allows you to change the team name, summary, and topic all at once, but then you're presenting two separate buttons to edit those things later. Do those two separate buttons just take you back to the same form? Or do you then have a new set of screens where those different fields are separated?

**Comment by hellafitz** [comment]
![]()

**Comment by hellafitz** [comment]
I pulled the topics we have in the [app gallery spreadsheet] (https://docs.google.com/spreadsheets/d/1qZ_1FKirNuqRmKTlRpVRNb5m7KRlBexoeXbYFPmWkc0/edit#gid=760481996) for comparison with the SDGs, in the hopes of finding our full edited list. I don't think we're there yet, since I'd assume we'd include more than is show for current teams.

**Comment by hellafitz** [comment]
Connected to #2681 (Display SDG/Theme collected from team)

**Comment by hellafitz** [comment]
@mjaris do you have an updated list of our version of the SDGs? see above. thx!

**Comment by mjaris** [comment]
Hey @hellafitz, here are the categories we used for the app gallery – but you're right that there aren't apps for each of them currently included in the App Gallery. 

Affordable and Clean Energy 
Clean Water and Sanitation 
Climate Action
Decent Work and Economic Growth 
Gender Equality
Good Health and Well-Being
Industry, Innovation, and Infrastructure 
Life Below Water
Life on Land
No Poverty
Partnerships
Peace, Justice, and Strong Institutions 
Quality Education
Reduced Inequalities
Responsible Consumption and Production 
Sustainable Cities and Communities 
Zero Hunger
Other

**Comment by hellafitz** [comment]
TF/TG: group agreed the edited list of SDGs is too long for use in student signup / profiles. Rebecca will check on what we used for TF and IdeaLab.

**Comment by mjaris** [comment]
Sorry if this isn't the right place for this since it's not an action item, but based on a decision from 2015/6 we also internally organize SDGs by major "buckets" if that's helpful to consider:

Health
Education
Equality
Peace
Environment
Poverty
Other 

**A few flags**
- These broader buckets were decided on by people no longer at the organization, so maybe they're not the right fit anymore! I'm not sure!  
- Our team would probably still have to break these out into more detailed categories at the end of the season for a deeper analysis for the app gallery/other projects 
- In recent years more teams have been solving apps that fall outside of the 6 main buckets, increasing the share of "other" so I'm not sure if that would affect how teams self-select into these categories (maybe they would try to shoehorn their app idea to conform to a category even though that's not necessary) or if it would cause concern to students if they were committed to an idea that didn't fall neatly into one of those buckets.

**Comment by hellafitz** [comment]
This is what was used in IdeaLab, plus the two additional responses at the bottom (as approved by Rebecca)
![Screen Shot 2020-10-07 at 11 21 29 PM](https://user-images.githubusercontent.com/6475595/95422342-fe36a000-08f3-11eb-8ac6-02d334d3ecbe.png)
