### ISSUE TITLE
Add 'Personal Summary' to Mentor signup and include it for confirmation in Team Building [13,13,1]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2729]
The Personal Summary (bio) appears in the Team Building section of a Mentor's workflow. 

We want to first introduce it during Mentor signup - between Skills & Interests and above 'How did you hear about Technovation?' The Personal Summary should still appear in Team Building but this time it should display any existing text response and allow that text to be edited. 

The Personal Summary should still appear as Bio on the Mentor Details page as accessed through search  results. Resolving the naming issue (personal summary vs bio) is out of scope here but deserves another ticket). Also important but out of scope, we should decide if the bio should be displayed in the abbreviated search results or only in profile details (upon click-through from initial search results display).

#### sign up as mentor
1. sign up as a mentor
2. you should not be able to complete sign up without providing 100+ characters of personal summary
3. make sure the personal summary has been saved when you finish profile creation

#### sign up as student
1. sign up as a student
2. it shouldn't require a personal summary
3. it should still work

(~10 mins)

**Comment by rsgonzal** [comment]
![Screen Shot 2020-10-08 at 10 12 11 AM](https://user-images.githubusercontent.com/22801026/95491745-e6403a00-094e-11eb-9766-3f72eb43b395.png)

**Comment by hellafitz** [comment]
Include "you can change this later" ![Screen Shot 2020-10-08 at 12 50 06 PM](https://user-images.githubusercontent.com/6475595/95506508-d6335500-0964-11eb-9fb7-35f0bf45c6a6.png)

screenshot for signup flow context:
![Screen Shot 2020-10-08 at 12 49 33 PM](https://user-images.githubusercontent.com/6475595/95506511-d6cbeb80-0964-11eb-8748-f8137ce16289.png)

**Comment by stenington** [comment]
In order to do this one, we need to talk more about what "enforced on dash" means.

Right now, the mentor bio can either be blank, or it has to be more than 100 characters worth of text. All profile editing screens enforce this, and it holds together conceptually. If you put anything, you have to put the minimum required amount, and otherwise an empty bio is just ignored when it comes to validation. That is to say that editing some other part of your profile won't result in an error that your bio is too short, it understands that a completely empty bio is allowed.

Things become more complicated when you want to accept fewer than 100 characters up front. The later editing screens suddenly start throwing errors that you haven't reached the 100 word minimum, even if you aren't there to edit the bio at all. For example, if I typed a short bio at sign up, then got to my dashboard and saw a typo, I wouldn't be able to correct that typo without now rounding the bio out to 100+ characters. 

I think if we want to accept <100 characters anywhere, we have to accept it everywhere. We can't have 100 characters as a hard requirement, but that doesn't mean we can't encourage it.

One place in particular we need to think about the right behavior is with the **Personal summary** check mark on the dashboard. Currently, a mentor is not considered onboarded until they have provided something for their bio, and we will only accept 100+ characters if we accept anything at all. In this new version, we would have to decide if <100 characters is enough to check that checkbox and consider them onboarded, or if we want to say they aren't properly onboarded until they have met the 100+ character count. That's the sort of thing I mean by "encouraging" it.

This is an invision board showing a few short flows for how things work now that might be helpful in thinking this through: https://projects.invisionapp.com/freehand/document/ht6puCxOY

**Comment by hellafitz** [comment]
Thanks, Mike. Rox and I discussed just now. Let's just enforce it on signup and keep things simple. It's not that hard to write 100 characters and if that's what discourages them from mentoring for tens of hours with kids, maybe it wasn't meant to be. Here's 104 characters for reference: "Hi, my name is Matt! I'm from Berkeley and I work at Technovation. I like mountains, puppies and pizza." 

@bagomer fyi

**Comment by rsgonzal** [comment]
This looks good to me!

So i did notice that i can go edit my bio and delete the whole thing. Seems kind of strange. Shouldn't 0 characters still be too short? I can open a separate ticket for this.

**Comment by stenington** [comment]
@rsgonzal It has to be that way, because we still have the alternate mentor sign up path where they leave the bio blank, until they're on the dashboard.

**Comment by rsgonzal** [comment]
oh ok! sounds good. thanks!

**Comment by mdancho** [comment]
Signed up as a mentor and do not see the personal summary included in the registration process. 
<img width="1305" alt="Screen Shot 2020-10-29 at 10 59 49 AM" src="https://user-images.githubusercontent.com/52216992/97613516-060ad100-19d6-11eb-91df-97d8855ba3ea.png">

**Comment by rsgonzal** [comment]
hey @mdancho are you sure you're on QA?
![Screen Shot 2020-10-29 at 11 04 02 AM](https://user-images.githubusercontent.com/22801026/97614050-b2e54e00-19d6-11eb-8736-0b1364b0674f.png)

**Comment by mdancho** [comment]
Confirmed that 'set your personal summary' is visible on the staging site. 
<img width="1071" alt="Screen Shot 2020-10-29 at 11 10 22 AM" src="https://user-images.githubusercontent.com/52216992/97620525-ed52e900-19de-11eb-85f5-273462e1372e.png">
