### ISSUE TITLE
Spike: Separate Student and Mentor signup tracks [40,20,2]

### ISSUE THREAD

**Issue by hellafitz** [Iridescent-CM/technovation-app#2730]
By separating the Student and Mentor signup tracks/flows we will be able to customize the signup experience based on user type. 

At minimum, we want to separate the tracks after the account type screen (where the platform displays whether the user's age qualifies them as a Student or Mentor). Whether we separate them earlier is an open question but if we can do it efficiently in stages we should start with everything past that existing decision point. 

Details shown in Profile Fields invision board, albeit with additional updates which would likely be dependent on this ticket's implementation (e.g. different updated response options for Students vs Mentors on 'how did you hear about technovation?'). 

![Screen Shot 2020-10-08 at 12 16 09 AM](https://user-images.githubusercontent.com/6475595/95427341-4063df80-08fc-11eb-810c-cef9eb670b7a.png)

**Comment by hellafitz** [comment]
Notes:
- This includes both dev and pm work
- Some technical investigation will lead to clarifying questions which will require input from PT and CET, which will lead to more technical investigation

Open Qs: 
- do we anticipate having additional user types go through this flow? 
- can we reasonably expect to have different signup paths that the user selects without the platform presenting options (using landing page text to get them to click the right button instead of asking their age first)?

**Comment by stenington** [comment]
Rough notes I had collected while trying to work through this: https://docs.google.com/document/d/12MOEMIAq0RcLDtU6Sq7Kodw5vrc7_RE7jt7hYKGa4SQ/edit

**Comment by stenington** [comment]
Spike summary: I don't think the registration wizard code we have is nicely modularized and ready to support independent sign up flows. 

One path forward, which I think is a reasonable option, would be to start building new flows from scratch rather than worrying too much about bending the existing code to our purposes. I would caution, however, that we already have the old one page signups still active in certain contexts, then the registration wizard active in other contexts, and adding a third flow without addressing the removal of the first two potentially just adds another layer of difficulty. 

But I would probably treat the current registration wizard code as "prototype in production", meaning the general strategy should be to replace it, not to build on it.
