### ISSUE TITLE
Make the demo video a required part of submission [40,8,5]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2803]
Teams should not be able to submit if they have not uploaded a demo video

## QA STEPS
* as a student, start a new submission, complete all of the items except for the demo video, verify the "Submit for judging" button is disabled
* then add a demo video, verify the button is enabled and you can submit

I also updated the progress bar, one way to verify this:
* in the admin, find a submission, take note of the "% completed"
* edit the submission, add a demo video, and verify the % goes up;  then remove the demo video and verify the % goes down

**Comment by hellafitz** [comment]
QA notes:
- try to submit garbage in the demo video submission field (platform should use similar validation as for the pitch video)
- as a team with an otherwise complete submission, try to submit without a demo video

**Comment by shaunxp20** [comment]
This one is on the QA site, I added QA steps for this one and #2802. 😄 🌞 🌻

**Comment by kate-technovation** [comment]
1. Started a new submission, completed all of the items except for the demo video, verify the "Submit for judging" button is disabled:

<img width="877" alt="Screen Shot 2020-12-04 at 4 44 43 PM" src="https://user-images.githubusercontent.com/57409606/101217888-1a369380-3650-11eb-95b6-2d65a1a3eba4.png">

2. Then added a demo video, and verified that the button is enabled and I could submit:
<img width="1440" alt="Screen Shot 2020-12-04 at 4 47 14 PM" src="https://user-images.githubusercontent.com/57409606/101218057-641f7980-3650-11eb-9883-1c667a9c4f5e.png">

**Comment by kate-technovation** [comment]
Testing progress bar as admin:

1. In the admin section, find a submission, and saw the "% completed" bar:

<img width="728" alt="Screen Shot 2020-12-04 at 5 02 29 PM" src="https://user-images.githubusercontent.com/57409606/101219768-7ef2ed80-3652-11eb-975f-d3e25cdeedcf.png">


2. Edited the submission, added a demo video, and verified the % went up:

<img width="731" alt="Screen Shot 2020-12-04 at 5 03 00 PM" src="https://user-images.githubusercontent.com/57409606/101219811-9205bd80-3652-11eb-91ba-97e8dca05894.png">

3. Removed the demo video and verified the % goes down:

<img width="744" alt="Screen Shot 2020-12-04 at 5 03 22 PM" src="https://user-images.githubusercontent.com/57409606/101219836-9e8a1600-3652-11eb-87f6-3d6559136f54.png">

**Comment by ksrebecca** [comment]
QA as a student:

Everything worked as expected. Submit button was greyed out, impossible to click when I had added everything except the demo video, then I could submit after I added the demo video link.

QA as an admin:

Everything worked as expected. Added the demo video and the progress bar went up then removed it and it went back down.

Yay!

RANDOM finding when I was getting my team ready for submission I wanted to approve the student fast to be part of the team so I requested to be on the team as the student, then changed my mind and went in as a Chapter Ambassador and added that same requester to the team. So that meant the student was on the team. But there was also still a pending request for the same student to join the team:
<img width="1128" alt="Screen Shot 2020-12-07 at 6 00 49 PM" src="https://user-images.githubusercontent.com/43972336/101416263-b22dba80-38a6-11eb-9bee-1458bc672db7.png">
As the same Rebequita Estudiante I approved it to see what would happen and the pending request disappeared. Totally not a big deal, and I seriously doubt this situation will occur (maybe ever??) just something to be aware of.

**Comment by shaunxp20** [comment]
Thanks for testing this, @kate-technovation @ksrebecca!!! 🙌 🍵 ☕ 🍪 🎋 

> As the same Rebequita Estudiante I approved it to see what would happen and the pending request disappeared. Totally not a big deal, and I seriously doubt this situation will occur (maybe ever??) just something to be aware of.

👍 Thanks! This is on our radar, we talked about it this morning. 😁
