### ISSUE TITLE
Location Issues are popping up

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2845]
Using this to document the different prroblems i'm seeing. These might or might not be related to charges on Google Cloud Geocoding APIs

**Comment by rsgonzal** [comment]
1. I enter my location, the system takes it and records it. When I go to my page to look at my location, it changes it.
_look at side bar_
![Screen Shot 2021-02-04 at 4 35 04 PM](https://user-images.githubusercontent.com/22801026/106973232-54331d00-6707-11eb-97b5-22d800eb1f82.png)
![Screen Shot 2021-02-04 at 4 35 52 PM](https://user-images.githubusercontent.com/22801026/106973256-61500c00-6707-11eb-8a2f-eb5517e3d453.png)

**Comment by rsgonzal** [comment]
2. I enter Tashkent, Uzbekistan and it gives me an error. I try to click it on the list it spits out and it still won't accept it. I can click on another city, but i don't live there...
![Screen Shot 2021-02-04 at 4 41 47 PM](https://user-images.githubusercontent.com/22801026/106973649-20a4c280-6708-11eb-8002-5fa1528efe8d.png)

I type, "tosh" and it gives me what i want..
![Screen Shot 2021-02-04 at 4 43 44 PM](https://user-images.githubusercontent.com/22801026/106973688-331efc00-6708-11eb-84d0-b1e307d960e5.png)

**Comment by rsgonzal** [comment]
3. I type in Los Angeles, and again I get an error. I click Bellflower from the list and I get another error
![Screen Shot 2021-02-04 at 4 44 39 PM](https://user-images.githubusercontent.com/22801026/106973770-63669a80-6708-11eb-9da8-375cb474a343.png)
![Screen Shot 2021-02-04 at 4 44 53 PM](https://user-images.githubusercontent.com/22801026/106973780-6792b800-6708-11eb-8b0d-85263f7326e4.png)

**Comment by shaunxp20** [comment]
I have a fix for the locations that come back w/ multiple suggestions, which is on QA now. It appears to be a bug - an inputted location is searched via geocoder and then comes back w. multiple results, we display those results which are selectable, when one is selected and the "Next" button is clicked, we search again, which will of course return multiple results... and then those get displayed, and then this behavior just repeats. So, I just made it so that when a suggested location is clicked/selected, it will get saved and move to the next page.

I tested it w/ a few locations and it seems to work. It needs more testing, and sign off on if this fix is what we want to go with.

This was a quick fix from the front-end (that will hopefully get some people unstuck), I'm still digging through the back-end (which has a lot of nooks and crannies). Still need to figure out why it's not using Google all of the time.

**Comment by rsgonzal** [comment]
1. I can now sign up as Bethlehem, Palestine and it is properly recorded
2. I can now pick Tashkent, Uzbekistan
3. Picking Los Angeles worked! (tested this before the latest deploy)

**Comment by shaunxp20** [comment]
Here's a brief recap of what happened.

Last Monday (Feb 1) we did a deployment, in this deployment we upgraded the `geocoder` library (to address a security vulnerability) which helps w/ our location data. With this upgrade (which I didn't know at the time), **the default location provider changed from Google to Nominatim**. There are 11 places where make a call using `geocoder` to get location data; only 5 of these calls explicitly use Google or Bing, for the rest of them they were using the default location provider. 

Registration is one of the places that uses the default location provider, this surfaced an issue, where using Google (prior to the upgrade) would return one result, Nominatim would return multiple results/suggestions; you would pick one of these suggestions and submit, but then it would come back w/ the same results/suggestions, and this would create an endless loop. This has been fixed, a few more details of this are here: https://github.com/Iridescent-CM/technovation-app/issues/2845#issuecomment-773763692

We ended up reverting the `geocoder` library on Friday to get the old behavior back (defaulting to Google). We'll still need to upgrade the library at some point, which I'll create another ticket for.
