### ISSUE TITLE
BUG: Mentor options to be shown in search results are not working [13,5,2.6]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2849]
I found a mentor who should be shown in results but isn't for some reason

![Screen Shot 2021-02-19 at 10 44 00 AM](https://user-images.githubusercontent.com/22801026/108548356-941a0880-72a0-11eb-8b55-fa650f3f1235.png)
![Screen Shot 2021-02-19 at 10 42 38 AM](https://user-images.githubusercontent.com/22801026/108548368-98debc80-72a0-11eb-9a7b-1b7d3fd3f00d.png)

**Comment by rsgonzal** [comment]
I just updated my profile settings, didn't check or uncheck these boxes, and now it shows correctly on the admin

**Comment by rsgonzal** [comment]
i tried to uncheck and it was updated properly and then checked them again and it worked. Not sure why it was stuck the first time..

**Comment by rsgonzal** [comment]
Is there a way to see how mis-matches there are?

**Comment by rsgonzal** [comment]
Thoughts from shaun- maybe check marks don't work until fully onboarded. need to investigate

**Comment by shaunxp20** [comment]
From what I'm seeing, mentors aren't searchable until they have been fully onboarded (which controls a main/higher-ranking (also hidden) "searchability" flag). Basically those checkboxes won't do anything until onboarding has been completed; which I think is fine since you can't (or should be able to) get to those checkboxes until onboarding has been completed. Hopefully that makes sense! 😅 

it sounds like there might be a bug/edge case where those checkboxes are viewable/editable without being fully onboarded, which causes this bug where those checkboxes won't do anything. I think we need more details about how this is happening.

> Is there a way to see how mis-matches there are? Are there any mentors in production who think they are visible but are not?

Hmm, I think this would be tricky without knowing how this is happening since those checkboxes are enabled by default, and this main "searchability" flag is off by default (which is happening in this case, and it would also be the case for all new mentors (which would be false-positives)). I'll have to think more about how to do this. 🤔 

> I just updated my profile settings, didn't check or uncheck these boxes, and now it shows correctly on the admin

When a mentor profile is updated, it will check to see if the main "searchability" flag can be enabled (and enable it if fully onboarded), I'm guessing that's what happened.

Also, just fyi... it's easy to miss, but in the admin you can tell if the "searchable" checkboxes are active or not, there are two different "no" possibilities.

If they are **not** fully onboarded (i.e. the main "searchability" flag is off/false) it will display "no" with:
> Mentors can change this setting themselves when they finish onboarding

If they are onboarded (i.e. the master "searchability flag is on/true), it will show "no" or "yes" (based on the checkbox) with:
> To change this, mentors should toggle "xyz" on their profile page

More just fyi, but here are the things a mentor needs to be fully onboarded:
- email confirmed
- bio present (doesn't have any length requirements here)
- mentor type provided
- consent signed
- training complete (if required)
- background check (if required)

🤸 🏋️ 🪂 💦 😅 ☺️ 😁

**Comment by rsgonzal** [comment]
Ah thanks, @shaunxp20 !!!

>Also, just fyi... it's easy to miss, but in the admin you can tell if the "searchable" checkboxes are active or not, there are two different "no" possibilities.

I clearly see this in the screenshots above. My mentor must not have been fully onboarded. Thank you for checking! I think we can be done with this ticket for now since we haven't seen it in production.
