### ISSUE TITLE
Make finished scores on judge dashboard more visible [5,3,1.67]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2855]
Not a lot of emphasis is given on 'finished scores' and it's kind of confusing to know that is a button.

Team suggestion is to just keep that section expanded

![Screen Shot 2021-03-03 at 9 18 13 AM](https://user-images.githubusercontent.com/22801026/109845119-a5003d80-7c01-11eb-8ba0-b5619644dcd9.png)
![Screen Shot 2021-03-03 at 9 18 24 AM](https://user-images.githubusercontent.com/22801026/109845152-aa5d8800-7c01-11eb-9482-613404d3ea73.png)

### QA
- Score a few submissions
- Go to the dashboard and view

**Comment by rsgonzal** [comment]
This looks good! i know you said this one was a bit more complicated, anything else to look out for? @shaunxp20

**Comment by shaunxp20** [comment]
> This looks good! i know you said this one was a bit more complicated, anything else to look out for? @shaunxp20

I made the live event scores expanded too (and assigned scores related to live events), I guess that would be the thing to be aware of, or test now as well.

**Comment by rsgonzal** [comment]
hmm, there was an event there and i tested it. Is this how it should be viewed. i already score it but it's still under start scoring

![Screen Shot 2021-03-22 at 7.27.14 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/7cd9ecce-d220-47f6-9e3a-2b0881f8147c)

**Comment by shaunxp20** [comment]
> hmm, there was an event there and i tested it. Is this how it should be viewed. i already scored it but it's still under start scoring

Good question! Before this change there would have been two links - "Assigned submissions" and "Finished scores", each link would have expanded their related sections. I just removed the links and made these two sections already expanded.

I looked at the "assigned submissions" section, and the text "Start scoring your assigned submissions" is a part of that section. I didn't make any changes to what (scores/submissions) appears under this section, so that's just how it was built. We can update/change any of these of course. 😄

**Comment by mdancho** [comment]
Looks great for expanded finished scores and glad to see that assigned scores will look the same! Let me know if that needs to be tested. 
<img width="1231" alt="Screen Shot 2021-03-26 at 10 40 31 AM" src="https://user-images.githubusercontent.com/52216992/112671866-fcb85000-8e1f-11eb-9274-3ef2dc0241ca.png">
