### ISSUE TITLE
Require completion of post survey before viewing certificates by  mentor[8,8,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2898]
Make buttons gray, disable and add a message on top of the button

message: Before you can view your certificate, please complete the post-survey.

Message would go away after the complete post survey

![Screen Shot 2021-05-27 at 10.55.52 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/0fedfa96-9be5-482e-afc5-63a9a08c9f73)

**Comment by viviancan** [comment]
The 2021 directory and certificates are missing right now from `lib >certs > <directory_here>`

Without the certificates, this is the error I received.

![Screen Shot 2021-04-15 at 11.15.59 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/91904ec9-a90e-4819-8899-b9bf2fb65a5e)

In order to generate a mentor certificate, I copy and pasted the 2020 certificates as a placeholder locally inside of the 2021 directory. I was only able to create a mentor certificate if the mentor was assigned to a team. If the mentor is not assigned to a team, the option to generate a certificate still exists, however, a certificate will not be generated.

**Comment by viviancan** [comment]
![Screen Shot 2021-06-07 at 1.28.29 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/d2eb18a3-dfd2-4e12-b3ed-94d9402d7f49)

![Screen Shot 2021-06-07 at 1.29.09 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/16334ded-c4ef-41a5-a5e8-7c64b4953a04)

**Comment by rsgonzal** [comment]
can we actually link the post-survey there? same link that we have in the helpful link dropdown

**Comment by viviancan** [comment]
Post survey is linked and this is now on QA

![Screen Shot 2021-06-11 at 9.59.50 AM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/094a61c9-ff93-4fe6-88f7-83b2744badc5)

**Comment by viviancan** [comment]
## QA STEPS
#### Checking a mentor who has already taken the survey
1. Login as a mentor who has already taken the survey 
    - Roxana Mail (roxana+mail2@technovation.org)
2. You should see a green button that says "Open your certificate" under each of the teams

#### Checking a mentor who has not taken the survey but has been awarded a certificate already
1. Login as a mentor who has not taken the survey. Here are a few accounts. *Note - not every team 
    - Mal Ware (kate+mentor1@technovation.org)
    - Tessa Tester(roxana+m722@technovation.org)

2. You should see the certificate button disabled. Above the button you should see this text "Before you can view your certificate, please complete the post survey" The words "post survey" should link to the placeholder survey on survey monkey

**Comment by rsgonzal** [comment]
This looks good to me! We can have the rest of the team check when the student version is up as well.
