### ISSUE TITLE
Spike: Review the way we generate certificates and decide if it should stay the same or change [8,8,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2916]
It's been noted that the way we generate certificates is clunky. 

We currently auto fill PDFs for consent forms and this may be a solution for certificates, but the templates will need to be in html.

To do:
- Look at the way we currently generate certificates
- Look at potential solutions outlined in #2501
- Decide whether we should switch for this season

**Comment by viviancan** [comment]
After reviewing previous comments regarding certificate technology, we have a few options moving forward
* Update certificate library
* Update the way certificates are generated by dev team
* Fix any bugs with the current process - certain characters not being generated properly

Next steps include:
- Identifying the pain points of the current process
    -  Which may be primarily around the way we generate certificates
    -  Bulk process
    -  Time intensive 
    -  Issues with specific characters
- As a team, decide if the library change should happen this season or if we should shift focus to how we generate certificates and bug fixes
- Potential Update - Instead of all certificates being generated ahead of time by dev team, create functionality for participant's to generate certificate through platform
