### ISSUE TITLE
BUG: Opening video link in new tab starts a new submission

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2945]
**Describe the bug**
When a judge starts a new submission and tries to open video links in a new tab, a new submission is started instead of going directly to the video

**To Reproduce**
1. Login as a judge with no submissions started
2. Start a new submission
3. Instead of clicking on the video link, right click and select open in a new tab
4. See that a new submission opens up
5. Go to dashboard and see that you now have multiple submissions

**Expected behavior**
The video should open directly on youtube or vimeo

**Screenshots**
![Screen Shot 2021-05-13 at 1.57.01 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/967009d6-56cf-423b-8d8e-74103a20a0f8)
![Screen Shot 2021-05-13 at 1.57.17 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/4eaf2f2f-9639-4921-b876-35d4f49b7238)
![Screen Shot 2021-05-13 at 1.57.39 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/cb1ec69d-2f85-4a79-b47b-3eca437cab3d)
![Screen Shot 2021-05-13 at 1.57.48 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/9c9ae910-16c6-481a-8408-5f17c7721124)
![Screen Shot 2021-05-13 at 1.57.59 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/b870f972-a79b-436c-970f-a2ba767f68ea)

**Additional context**
- This only happens on a new score. If you 'Resume' a score from your dashboard, the bug no longer occurs
- There are currently about 130 judges with more than one incomplete score

**Deployment notes**
Do not deploy

**Comment by rsgonzal** [comment]
### QA Steps
Do these 1. After signing up as a new judge & 2. As an existing judge
- Follow steps to reproduce
- Verify you get the expected outcome and you do not get assigned a new submission
- Very your dashboard doesn't have more than one submission
- Finish scoring the submission and start a new score
- Verify the correct score is being counted

**Comment by kate-technovation** [comment]
1. Logged in as a judge with no submissions started:
<img width="1240" alt="Screen Shot 2021-05-14 at 1 50 01 PM" src="https://user-images.githubusercontent.com/57409606/118309449-48e84e00-b4bb-11eb-9191-b5efa59e89eb.png">

2. Started a new submission:
<img width="1215" alt="Screen Shot 2021-05-14 at 1 50 42 PM" src="https://user-images.githubusercontent.com/57409606/118309534-60bfd200-b4bb-11eb-86d5-f88a771b3524.png">

3. Instead of clicking on the video link, right clicked and selected open in a new tab:
<img width="1093" alt="Screen Shot 2021-05-14 at 1 51 33 PM" src="https://user-images.githubusercontent.com/57409606/118309615-7f25cd80-b4bb-11eb-942b-b64f62a626ee.png">

<img width="1116" alt="Screen Shot 2021-05-14 at 1 59 23 PM" src="https://user-images.githubusercontent.com/57409606/118310430-9913e000-b4bc-11eb-9005-4d94d417656d.png">

4. Went to dashboard but did NOT see multiple submissions (not sure if I did something wrong):
<img width="1232" alt="Screen Shot 2021-05-14 at 2 00 11 PM" src="https://user-images.githubusercontent.com/57409606/118310495-b3e65480-b4bc-11eb-9f3b-af967de58f9c.png">

**Comment by mdancho** [comment]
1. Started a new submission with no pending submissions 
<img width="1262" alt="Screen Shot 2021-05-14 at 12 24 03 PM" src="https://user-images.githubusercontent.com/52216992/118313238-5562ab80-b4a7-11eb-8ab7-e881a47e7e42.png">

2. From the submission main page and from each of the scoring sections I clicked open pitch video and demo video in another tab and got the correct pitch and demo videos.  
<img width="901" alt="Screen Shot 2021-05-14 at 12 24 42 PM" src="https://user-images.githubusercontent.com/52216992/118313286-64e1f480-b4a7-11eb-80e9-d9bf28198512.png">
<img width="747" alt="Screen Shot 2021-05-14 at 12 28 10 PM" src="https://user-images.githubusercontent.com/52216992/118313389-86db7700-b4a7-11eb-8749-44b1d0b568c2.png">

3. No new scores were automatically started from the above actions

**Comment by rsgonzal** [comment]
overall looks good! The only think i noticed is that our ability to track if the links are clicked on does not work if you open in a new tab. It doesn't recognize that as a click. I'll create a ticket to see if it's possible to include that in the clicks
