### ISSUE TITLE
Create rake task to soft delete scores by judge profile id

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#2956]

**Comment by rsgonzal** [comment]
Judge with lots of incomplete: roxana+j514@technovation.org

I suspended the judge because this is how it is set up in production right now with problem judge.

I was thinking this problem i created might make this difficult to test. Here are the submissions that were under that judge i deleted. I'm missing one more complete one, all of these are currently unviewable under score details.. :(

![Screen Shot 2021-05-20 at 11.48.53 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/3c983d0e-5003-4d8b-8b4e-33a5384a84fc)

**Comment by rsgonzal** [comment]
Did another check by signing up as a judge, recusing and scoring 👌👌
