### ISSUE TITLE
Flash Message on My Profile section for students

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3072]
From #3035

**Comment by rsgonzal** [comment]
You must complete the following before accessing your dashboard:
      Have your parent sign the consent form
      Fill out your location

![Screen Shot 2021-11-17 at 9.27.28 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/bf60e56c-6a56-41f8-8697-834abcea3c6d)

**Comment by shaunxp20** [comment]
I added the required steps (using some stuff from Tailwind UI), I also added a very basic/placeholder welcome message for students, since this will be the first thing they see when they login. We can edit this of course, I just thought it was better than just having a "do this!!!" message. 😁  Anywho, this new notification message w/ the required steps will be shown until the required steps are completed. 👋 📜 ✅ ✅ ➡️ 🥳 🎈

**Comment by dboyer** [comment]
Let's change the text from "We need a few more details in order to get started. Parental consent is required to participate, and your location is needed to assign you a chapter ambassador and used for team building."

Instead use:

"We need a few more details in order to get started. Please complete the parental consent and media consent forms, and add your location so you can build a Technovation team."

**Comment by shaunxp20** [comment]
> Let's change the text from "We need a few more details in order to get started. Parental consent is required to participate, and your location is needed to assign you a chapter ambassador and used for team building."
> 
> Instead use:
> 
> "We need a few more details in order to get started. Please complete the parental consent and media consent forms, and add your location so you can build a Technovation team."

Forgot to mention, this change is on QA (and making it only visible if onboarding steps are missing). Btw, I like the "so you can build a Technovation team" part! Improving our onboarding flow, ftw! 🙌 🥳
