### ISSUE TITLE
Allow students to set the location in the my profile section

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3092]
- Hookup front-end to back-end in the my profile section
- Complete the flow to set location 
- Remove the "force location" step for students that prevents them from accessing the dashboard

**Comment by shaunxp20** [comment]
On the old/existing student profile section there is no form to update your location, there's just a button that takes you to a form - coincidentally this is the same form used for the "force location" functionality, this is also a Vue component. The student profile (new and old one) is just HTML, not in Vue.

Adding this form would be new functionality and a lot of work, imho, which I think drifts us into "refactoring locations" territory (b/c it's adding yet another way to add a location). Which I don't think we should prioritize yet, since there's still work to be done - on the new registration flow, rebranding, team matching, consent form bugs, etc. etc. etc. 😂

I propose, even though I just removed it, to re-enable the "force location" step for students which keeps us from deviating from the existing flow, which keeps us from doing more work. And then on the student profile page, we just use the existing functionality (which would display the current location info, and a button to change it). This would allow us to keep moving forward w/ team building and everything else. And then as more things fall into place, we can revisit this.

If we decide to do this, we could make some tweaks to the existing Vue component (which is pretty gnarly, 500+ lines of code!) - like rebranding it for students, adding a message like, "we need a location to find you a chapter ambassador" or some friendly text.

Anywho, some food for thought! 😄

**Comment by shaunxp20** [comment]
I did some minor clean up for the location stuff in the my profile section. I also restored the "force location" functionality for students, just temporarily for now, I'll see if I can make it better (remove it) while I am working on some of these other tickets. 🙂

**Comment by shaunxp20** [comment]
This one is pretty much as good as it's going to get for now (functionality wise). The force location setting has been removed (again, just for students), and there is a button on the "My Profile -> Location" page that goes to the existing "set location" form/functionality. So, location functionality will be there, we'll just need to make some UI adjustments. 👨‍🎨 🎨 🌐 🖌️ 👩‍🎨
