### ISSUE TITLE
Allow an email used to create a beginner account to be used as a parent email for another student

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3165]
There are a lot of things going on with emails but in an idea world...

When a parent signs up their 8-12 year old, they may also have other students in other divisions. PT would like them to use their same email as the parent email for those accounts

**Comment by rsgonzal** [comment]
I think this is causing a bug.

Can't update a student's profile if the parent email has been used as the account email for a beginner account. Example in [spreadsheet](https://docs.google.com/spreadsheets/d/1TJTGU8RQzSlwyzES0G7cO__sI1EpofIkyG5RK3hO1ws/edit?usp=sharing). (locked to anyone not in Technovation)

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3165?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by devkonrad** [comment]
I created a beginner account and then i used the email as a parents email for another beginner and it works fine. Son i am investigate to see if there is some side effect, but until now looks like everything is ok. @dboyer will take a look on this one. ;)

**Comment by dboyer** [comment]
I was able to reproduce this problem with the following steps:

1. Created an account in the beginner division (user has a birthdate that makes her 8-12 years old) with the email deb+parent0812...
2. Started to create an account in the junior division (user has a birthdate that makes her 13-15 years old) with the email account deb+student0812
3. In the parent/guardian information section of the form, I put deb+parent0812... as the parent email address

<img width="649" alt="Screen Shot 2022-08-12 at 12 31 33 PM" src="https://user-images.githubusercontent.com/516764/184403195-7215957d-cbc3-4de5-b12f-36fa4f4c6ec2.png">

4. When I tried to create the account, I got the message that the account couldn't be created because the parent guardian email can't match any other email.

<img width="746" alt="Screen Shot 2022-08-12 at 12 33 45 PM" src="https://user-images.githubusercontent.com/516764/184403517-74cf001c-f2d8-40ac-868f-dd9ab4a17e10.png">

**Comment by devkonrad** [comment]
> I was able to reproduce this problem with the following steps:
> 
> 1. Created an account in the beginner division (user has a birthdate that makes her 8-12 years old) with the email deb+parent0812...
> 2. Started to create an account in the junior division (user has a birthdate that makes her 13-15 years old) with the email account deb+student0812
> 3. In the parent/guardian information section of the form, I put deb+parent0812... as the parent email address
> 
> <img alt="Screen Shot 2022-08-12 at 12 31 33 PM" width="649" src="https://user-images.githubusercontent.com/516764/184403195-7215957d-cbc3-4de5-b12f-36fa4f4c6ec2.png">
> 
> 4. When I tried to create the account, I got the message that the account couldn't be created because the parent guardian email can't match any other email.
> 
> <img alt="Screen Shot 2022-08-12 at 12 33 45 PM" width="746" src="https://user-images.githubusercontent.com/516764/184403517-74cf001c-f2d8-40ac-868f-dd9ab4a17e10.png">

Thanks, @dboyer! I will do that locally o tackle the problem! ;)

**Comment by devkonrad** [comment]
@dboyer Do we need to allow a "beginner" account to have another "beginner account email" as parent/guardian email? (i am checking the valid scenarios)

**Comment by dboyer** [comment]
Apologies for missing this question! We do not need to allow a beginner account to have another beginner account email. The email used for a beginner account is the parent/guardian email since parents have to sign up kids ages 8-12. We don't want to allow the same email address to be used to create two accounts.

**Comment by dboyer** [comment]
Working as expected! Tested these scenarios on QA:

- Registered as a beginner with the email deb+parent0920@
- Used deb+parent0920 as the contact for the parent email for a new junior account
- Used deb+parent0920 as the contact for the parent email for a new senior account
- Changed an existing junior account to send a parental consent email to deb+parent0920 
- Tried to sign up for a junior account with deb+parent0920 and received message that email was already in use
- Tried to sign up for a beginner account with deb+parent0920 and received message that email was already in use
