### ISSUE TITLE
Add identity to Heap

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3171]
https://developers.heap.io/reference/identify

**Comment by shaunxp20** [comment]
I picked this one up so it can go out w/ the deploy today. That way we have more time to see if it's working correctly (instead of being in scramble mode next week!). Also, something I didn't consider is that we don't want to identify accounts that are being impersonated. I think I got the right incantation to make that happen! 🤞 😅

**Comment by dboyer** [comment]
Oh good call on the timing! I actually just realized this morning that we can't set up the Mailchimp integration with Heap until identify calls are in place so this PR helps with that too.

Fingers crossed, I think I can otherwise take care of the Mailchimp integration and won't need you to add anything. Maybe....

**Comment by dboyer** [comment]
We need to use the process for email described in adding user properties - https://developers.heap.io/reference/adduserproperties

Likely heap.addUserProperties({"email": "user@example.com"}); but more info is on that page

**Comment by shaunxp20** [comment]
Okay, this update is on it's way to QA; of course it needs to be on production to verify, but after QA is doing building I'll deploy it to production. I updated it to this, hopefully this will work:
https://github.com/Iridescent-CM/technovation-app/blob/9156ea36bb354f6c4d20fd17f47d11404e843ddc/app/views/layouts/application_rebrand.html.erb#L42-L43
