### ISSUE TITLE
Skills and interests not saving correctly to mentor profile during account creation

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3186]
If registering with a mentor account on production, selecting certain options in the skills and interests section will not allow registration. The user can complete all fields but clicking the "Submit this form" button on the last page will not do anything and the person isn't registered. 

Tested in Chrome on a Macbook.

Cannot register if selected:

- coding
- project management
- coding and/or project management and any other option

Can register if selected:
- experience with Java
- experience with Swift
- business / entrepreneurship
- marketing

## QA STEPS
For reference: the mentor skills and interests list is now dynamic - when the registration form is loaded, we're making a call in the background to get this list of values from the database.

To QA, register as a mentor and pick some skills and interests - then after registration verify those same skills and interests are selected in the mentor profile section.

We'll also want to check this on production after it's deployed since that's where the issue was.

**Comment by dboyer** [comment]
The interests added in the registration process do not match the interests shown on the mentor profile:

- Checked design during registration and it showed as coding on the mentor profile when logged in
- Checked marketing during registration and it showed as design on the mentor profile when logged in

**Comment by shaunxp20** [comment]
This one is on its way to QA, I wrote up some basic QA notes/steps too. 😄

**Comment by rsgonzal** [comment]
This is working correctly for me!! updating in my profile and on the dashboard also works

**Comment by dboyer** [comment]
Also worked for me on QA

**Comment by shaunxp20** [comment]
Awesome! Thanks for QA'ing this! I just have one small tweak coming to QA soon - and that's changing where/when we're making this call to load the skills & interests - instead of loading them when the main form loads, we only load them for the mentor profile section (that way we don't make an unnecessarily call for students).

**Comment by shaunxp20** [comment]
This one has been deployed to production!

**Comment by shaunxp20** [comment]
Also, a random note I wanted to document - b/c this list is dynamic now - we're making this background call to the server to get this list, there's a chance there could be an error w/ this call (that would be very unexpected!); if that happens the "Skills & Interests" section will be hidden/missing - I decided to hide this section instead of displaying an error (or something else), since it's not critical/required, and this shouldn't happen, but if for some reason it does and we see/hear about a missing "Skills & Interests" section, that is why. We'll also get an Airbrake alert. Anyhwo, probably nothing here more than just an FYI. 😃
