### ISSUE TITLE
Rebrand team search page for students

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3203]
Currently everything goes down to the bottom

Either 
- move results up or
- use new mockups

![screencapture-technovation-qa-herokuapp-student-team-searches-new-2022-03-02-09_23_28 (1).png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/09d9a8a3-2cc4-4527-ab6f-0bd16baff745)
![screencapture-technovation-qa-herokuapp-student-mentor-searches-new-2022-03-02-09_24_34.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/fcb31517-2968-4cf4-af3c-f99cd7ce600e)
![Screen Shot 2022-03-02 at 9.21.49 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/1e907807-0347-4f69-8e63-26e3a1e536d3)![Screen Shot 2022-03-02 at 9.21.56 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/f64b90d7-23fd-4a8d-bc4f-8852ae65c334)

**Comment by dboyer** [comment]
This issue will cover rebranding the team search page for students. Rebranding the mentor search page will happen as part of #3482 .

Currently the team search page looks like this:
![Team search](https://user-images.githubusercontent.com/516764/173846278-c9ecd6b4-19ae-4c4c-b916-dfd98a262079.png)

We need to implement this rebranded page:
![StuDash-TeamSearch (1)](https://user-images.githubusercontent.com/516764/173846551-bf9b0a67-5506-4248-b9ec-aafa392c6062.png)

Specific tasks include:

- [ ] Move search results into a separate box next to the left search sidebar
- [ ] Update the containers for the search sidebar and team results to match the branding in the wireframe. This layout/code has already been implemented on the "My Profile" tab for students so the conventions on that tab can be followed here.
- [ ] Update layout of the team cards to match what is in the wireframe
- [ ] Adjust the button and check box colors in search sidebar to reflect new branding

Whenever possible, we should use existing components or follow the implementation on other pages in order to have continuity in the UI across the whole student dashboard experience.

**Comment by devkonrad** [comment]
Implements the rebrand for _Students Team Search_: https://github.com/Iridescent-CM/technovation-app/pull/3503

**Comment by devkonrad** [comment]
I pick the Card Component issue #3504 to do, before finalize this on, once this issue will need the Card Component.

**Comment by devkonrad** [comment]
PR https://github.com/Iridescent-CM/technovation-app/pull/3503 avaiable for Code Review

**Comment by dboyer** [comment]
Confirming that a functionality review looked good. 

One note that the left column is narrower than the left column on the My Profile page. That narrow width allows three search results to be returned in a row on the right side. If it looks too narrow, though, we can talk about widening the search filters and only returning two results.

**Comment by devkonrad** [comment]
This issue was tackled on PR: https://github.com/Iridescent-CM/technovation-app/pull/3536

**Comment by dboyer** [comment]
Confirming this is on QA and functionality is working as expected. I think there will be some UI tweaks based on feedback from the program team, but I'll add those as a new issue.
