### ISSUE TITLE
Change App to Product

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3232]
We use "App" in various places in the front end and back end. Now that we accept AI projects, We need to change this to "Product"

This should be changes in the backend as well

![Screen Shot 2022-01-19 at 12.26.50 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/8cfd03a3-9517-408e-a15a-f1b6be8b6b6e)

**Comment by dboyer** [comment]
I found a few other places where we use app. These are all in the text rather than a header or sidebar so might not be as important to change. 

- [ ] We use app instead of product in the right sidebar text

<img width="341" alt="Screen Shot 2022-03-08 at 3 35 22 PM" src="https://user-images.githubusercontent.com/516764/157320419-781527b6-9d9d-4e26-bcae-8eb21b572327.png">

- [ ] In the help text at the bottom of the subscription page

<img width="628" alt="Screen Shot 2022-03-08 at 3 41 11 PM" src="https://user-images.githubusercontent.com/516764/157321349-c61bfab3-af75-475f-b773-64df6ce8dedd.png">

**Comment by dboyer** [comment]
Confirmed that the help text is updated on QA
