### ISSUE TITLE
Division filter bug

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3239]
A ChA ChA wrote in about a discrepancy with a student showing up in one division on the platform and on another division when pulling data from the platform.

I did a search for students NOT matched with a team, because the added column mentions it is a "team division." So I thought maybe being on a team was causing this discrepancy. I am still finding users in the wrong division

## DEPLOY NOTES

Run this script on production to update accounts that are currently in the wrong division:
```
heroku run bundle exec rake update_division_assignments --app technovation
```

![screencapture-technovation-qa-herokuapp-admin-participants-2022-01-20-00_10_05.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/e8bd7303-30ef-4e43-9193-e1a11af3836e)![screencapture-technovation-qa-herokuapp-admin-participants-2022-01-20-00_10_30.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/5ef862cc-7ab6-4262-9f10-25d7eedfd813)

**Comment by shaunxp20** [comment]
There are a few things going on here...

The division field in the database seems to be static, we set it, and then it seems it never gets updated. I made these two changes to address this:
- when a student's DOB is changed their division will get updated
- for returning students, their division will get updated when they register for the current season

Another issue, which I didn't address is that In the admin, the "Team Division" column is dynamic, it gets generated on the fly, so it is current/live, which is why there are some discrepancies showing up - in the database someone could be listed as X division (it remains static in the database before these changes), but when it gets displayed it would be listed as Y (b/c the division gets dynamically generated for the "Team Division" column). For these discrepancies, after this fix goes live, we can just update their DOB (to something else and then set it back) and that should trigger a division re-assignment. If there are a lot of them, we can write a rake task or something to update them all.

I also added the division when viewing an individual student in the admin, this is static (showing whatever is in the database, i.e. doesn't get generated on the fly like the "Team Division" column).

😅 😃

**Comment by rsgonzal** [comment]
I am seeing about [200](https://docs.google.com/spreadsheets/d/1YZx7udSKVNomJodj3xsJL9N56v8hIp8-dvcdsNu1rYY/edit#gid=1822854188) of these on production. And weirdly only when I pull juniors

**Comment by rsgonzal** [comment]
maybe only about 120 (second tab) if we take away students matched with teams. That may or may not have a division because of that

**Comment by shaunxp20** [comment]
> I am seeing about [200](https://docs.google.com/spreadsheets/d/1YZx7udSKVNomJodj3xsJL9N56v8hIp8-dvcdsNu1rYY/edit#gid=1822854188) of these on production. And weirdly only when I pull juniors

I think that makes sense - it's unlikely anyone will change their DOB, so likely these are all returning students, and beginners didn't exist last season, and seniors returning would still be seniors; so it would just be juniors who are returning as seniors. 🤔

**Comment by shaunxp20** [comment]
Ok, so sounds like we'll want to write a script to update these accounts then. I'll just need a list of account ids - we'll just update/refresh each account's division.

**Comment by rsgonzal** [comment]
[Here](https://docs.google.com/spreadsheets/d/1CWkwD8lNMNSmvL-P77L8q_yu_ONHEX0ykDhTR2vmCXA/edit?usp=sharing) is the spreadsheet with account IDs

**Comment by shaunxp20** [comment]
I wrote a rake task to update the accounts listed in that spreadsheet. I pulled down the production database and tested it against that, and it seems to be working as expected - the first group of accounts (top half-ish of the list) gets updated from junior to senior and the second/bottom group of accounts gets updated from junior to beginner.

There won't be anything to QA for this, and the accounts will only get fixed on production after we do a deploy (to get this script there) and run it there. 👍 😄

**Comment by rsgonzal** [comment]
woo thanks, shaun!

**Comment by shaunxp20** [comment]
Actually, thinking about this again, re: the accounts that go from junior to beginner, is that okay? It's sort of creating a side door into the beginners division, whereas all the current beginner division students go through the front door w/ their parents registering via the registration flow. 🤔

**Comment by rsgonzal** [comment]
yeah i think we knew this was a thing for returning students and were ok with it. They technically are beginners when matching and everything anyways!

**Comment by shaunxp20** [comment]
This script has been run on production! 👍 😄

**Comment by rsgonzal** [comment]
The script worked! There is only one student not in the right division but I think that is because of #3165
