### ISSUE TITLE
Update judge my profile with new styles

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3289]

**Comment by dboyer** [comment]
One tiny tiny thing. For consistency, we should capitalize Profile in the dropdown menu so that it matches the other capitalization patterns.

<img width="486" alt="Screen Shot 2022-03-23 at 12 08 50 PM" src="https://user-images.githubusercontent.com/516764/159744503-66b0833b-85df-4115-93b4-3b0c545fe2b9.png">

**Comment by rsgonzal** [comment]
cleaned up with #3313
