### ISSUE TITLE
Create new rebranded components for judge scoring

### ISSUE THREAD

**Issue by shaunxp20** [Iridescent-CM/technovation-app#3294]
This ticket is more of a placeholder for now b/c a lot of these things could be split off into separate tickets with more details.

A rough list of the new rebranded components for the new judge scoring experience:
- Score overview sidebar
- App header/overview - photo, name, location, submission type (that's reused on every page)
- Submission summary page
- energetic blue sidebar container, and main container

And two ideas/approaches for the different sections:

a. Rebrand existing components and new components for the new sections:
  - Project Name & Description
  - Learning Journey

b. Create a new generic component that can be reused for all the old and new sections

Related to #3270

**Comment by rsgonzal** [comment]
[Mural Boards](https://app.mural.co/t/technovationgirls4378/m/technovationgirls4378/1646352662018/f183eb79e96e3a67b4f64d52b5c664159f12ebe9?sender=u9adab98cc36af2c4665e9477)

**Comment by viviancan** [comment]
Update 4/7/22
Basic foundational work is complete! The score sidebar, app header/team info and energetic blue container are complete.

We need to decide which "path" to take. There is a proof of concept for both paths. As Shaun mentioned in his original comment, we can rebrand the existing components and add in the additional sections OR use a generic container for all the sections. The proof of concept can be seen in the Ideation component `app/javascript/judge/scores/sections/Ideation.vue`. The commented out code is approach 1 with rebranding the existing components and the non commented code is using a generic container. 

Using the generic container (approach 2) development was much quicker and would also allow us to keep the judging flow DRYish. One main concern I have is if we go with this approach it *could* affect the way things are currently wired up in terms of the judging logic. I say *could* because I have not spent enough time with this part of the app to know for sure 👀🤔

We can discuss this further tomorrow! Also, this might be a good point where @shaunxp20 could split up the remaining work. Whichever path we decide on, maybe Shaun can look at wiring up the routes/score stepper with the new screens and I can continue with the additional rebranding. Just a thought! I think right now 3 additional tickets should be made - complete the rebranding of judge screens, create/wireup the new judge screens, & complete rebrand of sidenav score stepper.

![Screen Shot 2022-04-07 at 10.27.09 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/88519109-2e07-426c-ab5a-13b905a730b2)

Also, would this value of `submission_type - dev_platform` underneath the division be acceptable? It is a little different compared to the original mockup. There is a set of logic that combines the values. We are able to split the values, but right now this is the default bc this is how the value is being returned from the backend @dboyer 
![Screen Shot 2022-04-07 at 10.40.53 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/440c9446-4700-4314-944e-21c7033b1f6a)

**Comment by dboyer** [comment]
Super exciting!!! Thanks for all the work on this! I'm fine with displaying the values as they are returned from the backend. I don't think it's a big change from the mockups and not worth the time to adjust how the backend works.

**Comment by viviancan** [comment]
Update 4/12/22
We are going with approach B - the generic container
@shaunxp20 and I have split up the remaining work. Shaun will be tackling the score stepper (#3342) and I will continue tackling the rebrand (#3343). This issue will hang out in the "in progress" until the remaining rebrand is complete
