### ISSUE TITLE
Update main navbar to be mobile responsive

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3355]

**Comment by viviancan** [comment]
![IMG_1ECFD6F943D9-1.jpeg](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/a18c38fa-b59a-4df2-abc9-1f91c5b9e63a)

**Comment by dboyer** [comment]
@devkonrad This could be a good task for you to dig a bit more into Tailwind and some front-end work. 

As shown in the screenshot, the main navbar looks off on https://my.technovationchallenge.org/signup#/ and other pages where there are many buttons at the top. We need to adjust the styling so that the Donate button isn't appearing over other text.

**Comment by devkonrad** [comment]
As discussed with @dboyer, we need to:
 - [ ] Adjust the bugs that remain open the burger menu itens on resize
 - [ ] Confirm if we will leave visible the donate for small sizes screen

**Comment by dboyer** [comment]
We do not need to have the Donate button visible. It is fine to put all items behind the hamburger menu on small screens.

**Comment by devkonrad** [comment]
> We do not need to have the Donate button visible. It is fine to put all items behind the hamburger menu on small screens.

Thanks, @dboyer! So i will wait for the code review :)

**Comment by dboyer** [comment]
Confirmed on QA that this switches to the hamburger menu at small screen sizes
