### ISSUE TITLE
Lingering message regarding data exports from admin pages

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3400]
Several admin users are reporting a lingering message on the admin pages indicating that an export is in progress. Kicking off a new export will result in that CSV downloading but then the same message returns.

<img width="724" alt="Screen Shot 2022-05-04 at 11 03 03 AM" src="https://user-images.githubusercontent.com/516764/166710857-f575ef52-e22e-42ee-bf6f-3fdca380afad.png">

**Comment by viviancan** [comment]
Update 5/4/22: 

[PR Here](https://github.com/Iridescent-CM/technovation-app/pull/3402)

Created this rake task to address the issue where queued export jobs in the admin profile are causing the "export" popup in the admin profile to be stuck in a sort of infinite loop. There is currently no way to "force end" these jobs as they do not show up in Sidekiq. We believe this issue is happening due to a previous deployment that introduced an export bug on production. While that issue has been resolved, there are a few pending jobs that somehow got out of sync. This rake task will address these issues.

**Comment by viviancan** [comment]
Verifying the expected output on QA. Ready for prod
