### ISSUE TITLE
Add energetic container and left sidebar to mentor search page for students

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3482]
Split off from #3203 

Once students are on a team, they have the option to search for a mentor at /student/mentor_searches/new. Currently, the mentor search looks like this:

![image](https://user-images.githubusercontent.com/516764/173844436-e4b48f8d-95f5-45af-a55d-18128900f90c.png)

We need to implement the rebranded mentor search page. 
![StuTeam-MentorSearch](https://user-images.githubusercontent.com/516764/173852000-c6c867fc-fd9f-4d5e-bca3-7ee00538bca7.png)

Specific tasks include:

- [ ] Implement energetic container. A component exists for this and can be viewed at https://github.com/Iridescent-CM/technovation-app/pull/3478
- [ ] Implement side bar. A component exists for this and can be viewed at https://github.com/Iridescent-CM/technovation-app/pull/3478

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3482?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Just left a comment on the PR! After testing this locally, I had a few points of feedback.

**DESKTOP VIEW**
- Images/cards are very large. I think there should be a fixed height/width on the image and card which will also help with some of the cards being different sizes.
-  When a mentor has multiple expertise tags, they cover the image
- Is there a placeholder image

- ![CleanShot 2022-07-19 at 10.55.30@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/5ed82c32-4b2f-44d3-8799-6aa1abcf6ffe)ESK

**MOBILE/TABLET VIEW**
- Cards do not change responsively to this view - See all of the mentor details on the cards. This could be fixed if there is only 1 (or 2 max) card per row when in tablet/mobile view
- Expertise tags are hidden when there are multiple
- Suggest changing 1 card (or maybe 2) to span entire width of container when in tablet or mobile
- Cards are different sizes ( I think due to different image sizes)
![CleanShot 2022-07-19 at 11.09.02@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/53d35db0-6320-421a-bf53-4aa1b1e743ca)

**Comment by dboyer** [comment]
Thanks for reviewing this @viviancan.

- I agree that we should implement a fixed height/width in order to not have different size cards.
- I don't see a placeholder image but will work on getting one.
- My preference is for one card per row of results when in mobile view.

**Comment by devkonrad** [comment]
> Thanks for reviewing this @viviancan.
> 
> * I agree that we should implement a fixed height/width in order to not have different size cards.
> * I don't see a placeholder image but will work on getting one.
> * My preference is for one card per row of results when in mobile view.

Thanks @viviancan and @dboyer for the feedback. I am working on the feedback poins to to improve our card. :)

**Comment by devkonrad** [comment]
This PR contains the updated version of the rebrand work (for mentor search and team search) with the latest version of Result card Component: https://github.com/Iridescent-CM/technovation-app/pull/3536

**Comment by viviancan** [comment]
Hey Alex! Thanks for addressing those early changes!

I'm still seeing some issues with the responsiveness of the result cards.
- The heights of the cards still vary depending on what information is available for the team. For example, in the following screenshot, the location data is missing so that card is shorter.
- There are still 3 cards per row in tablet/mobile view. There should only be 1 card per row in mobile/tablet. I saw the use of grid in that section, maybe a flexbox approach could be helpful there!

![CleanShot 2022-07-22 at 14 05 47](https://user-images.githubusercontent.com/29210380/180510658-f5117dc7-f11e-42b2-bb64-d8cdc6a6dace.png)

![CleanShot 2022-07-22 at 14 08 07](https://user-images.githubusercontent.com/29210380/180511430-994ec1d9-0166-4d05-85be-ff86c8bdf370.png)

**Comment by devkonrad** [comment]
> Hey Alex! Thanks for addressing those early changes!
> 
> I'm still seeing some issues with the responsiveness of the result cards.
> 
> * The heights of the cards still vary depending on what information is available for the team. For example, in the following screenshot, the location data is missing so that card is shorter.
> * There are still 3 cards per row in tablet/mobile view. There should only be 1 card per row in mobile/tablet. I saw the use of grid in that section, maybe a flexbox approach could be helpful there!
> 
> ![CleanShot 2022-07-22 at 14 05 47](https://user-images.githubusercontent.com/29210380/180510658-f5117dc7-f11e-42b2-bb64-d8cdc6a6dace.png)
> 
> ![CleanShot 2022-07-22 at 14 08 07](https://user-images.githubusercontent.com/29210380/180511430-994ec1d9-0166-4d05-85be-ff86c8bdf370.png)

Hi, @viviancan. Wich width are you using for mobile, tablet and desktop? 
- Here more tan 1024px is considered Desktop
- Between 1023px and 750px is conidered Tablet
- Less than 750px is considered Mobile

Just asking to make de adjustments properly, because de resposivity is working here for me ;)
(we can do a call monday about it, what you think?)

Thanks!

**Comment by dboyer** [comment]
I agree with Vivian's suggestions from a general design perspective. Could we include these changes:

-  All cards should be the same height, which is the height needed if all pieces of information (team name, division, location, and photo) are available. If a card doesn't have all the info, that card can just have a bit more white space but remain the same height
- Images should fill the whole top part of the card (i.e. the whole container) without white space on the sides (see screenshot)
<img width="312" alt="Screen Shot 2022-07-27 at 9 17 36 AM" src="https://user-images.githubusercontent.com/516764/181273613-a06a2f6c-9409-4e61-89ab-e76b1bb9b55b.png">

- One card per row when viewing search results on mobile

**Comment by devkonrad** [comment]
Great, @dboyer. I will implement this improvements.

**Comment by devkonrad** [comment]
This issue was tacled on PR: https://github.com/Iridescent-CM/technovation-app/pull/3536
