### ISSUE TITLE
Action buttons greyed out after Tailwind v3 upgrade

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3538]
Split off of #3468 

- [ ] While logged in as a student on QA, I clicked "find a team," ran a search and then clicked "view more details" for a team. The button to request to join the team is only visible when you hover over it.

[JoinTeamButtonIssue.webm](https://user-images.githubusercontent.com/516764/176224098-5f75e5e6-68b2-4531-b269-965715600aea.webm)

- [ ] Nick found the action button to create a team was greyed out until hovered over.

https://drive.google.com/file/d/1t3MgyAmwAKUotWuT-dviSMaadH9ZlB-8/view

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3538?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Verified on QA this behavior happened w/ Tailwind v3 upgrade.

**Comment by viviancan** [comment]
Confirming that this is no longer an issue - I think because these pages were recently rebranded! Checked on QA and locally. ![Screen Shot 2022-07-27 at 2.58.09 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/27b144b9-e45d-43d9-a0f0-5935fa3e50fe)
![Screen Shot 2022-07-27 at 2.57.56 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/b376675c-8d1c-418e-871f-0a62c862036e)

**Comment by dboyer** [comment]
I'm also no longer seeing the issue!
