### ISSUE TITLE
Post-season support

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3567]

**Comment by shaunxp20** [comment]
Just noting that Vivian and I spent quite a bit of time (separately and together) dealing w/ failing tests that were breaking the CircleCI build.

There is a PR #3618 to handle the failing tests, which basically sets CircleCI to the next season.

Apparently we had to update CircleCI dates last year too: https://github.com/Iridescent-CM/technovation-app/commit/637aac57585e684b5d5117dbc0895babbfb0b672

To better handle this in the future, we'd have to dive deeper into the failing tests, make them more robust and imho, not depend on the ENV dates (either local or CircleCI), but rather the tests would set the dates, that way the tests run in a more controlled environment.

**Comment by viviancan** [comment]
9/22/22 Noting that we received a question regarding a past ChA account. Ophelie was unable to change their status from approved to another status. After further investigation, it appears that this specific user has an invalid account due to password validation. We have suggested for the user to update their pw and the issue would most likely be resolved.

I am however logging an additional ticket to add an appropriate error message in the admin portal bc when the status was updated, Ophelie did receive a success green message that the account had been updated.
