### ISSUE TITLE
Upgrade to Ruby 3

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3575]
While starting the Heroku upgrade as part of #3491, we discovered that the oldest available Ruby version for Heroku-22 i Ruby 3.1.0

We are currently on Ruby 2.x so ideally we will upgrade Ruby in order to complete the Heroku upgrade the a version with long term support. This issue covers researching the tasks and needed time to complete the Ruby upgrade.

## Running list of known issues w/ the upgrade
- Image uploads aren't working

**Comment by shaunxp20** [comment]
In order to upgrade to the latest Ruby version, CircleCI also had to be updated, here is an overview of the CircleCI upgrade.

We are currently using CircleCI's legacy images which don't offer a Ruby 3.1 image:
https://hub.docker.com/r/circleci/ruby/tags/?page=1

CircleCI had to be updated to the "next-generation convenience images" which has a Ruby 3.1 image.

A [snippet](https://circleci.com/docs/circleci-images) about legacy images:
> Legacy images with the prefix “circleci/” were deprecated on December 31, 2021. For faster builds, upgrade your projects with next-generation convenience images.

Here's where we specify which image we're using (which shows that we're using the legacy images):
https://github.com/Iridescent-CM/technovation-app/blob/7ae686832b92fba5e4516b72f245f4a33b7a27e3/circle.yml#L7

With the new image upgrade (side note: the old image was Debian, and the new one is Ubuntu), two of our software packages also needed to be updated:
- PostgreSQL
- wkhtmltopdf
  - This one might have some fallout work, related to configuration

A note about the old vs new image, the old image was using the "node-browsers" variant, but this isn't explicitly available for the new images, but the "browers" variant includes Node.js, a blurb mentioning this is here (under "Variants", under "Browsers"):
https://hub.docker.com/r/cimg/ruby

The new image we'll be using is "cimg/ruby:3.1.2-browsers". 👍 😅 😃

**Comment by shaunxp20** [comment]
A few more notes regarding CircleCI.

I updated our CircleCI configuration to install browser tools, basically just following the quick start guide here:
https://circleci.com/developer/orbs/orb/circleci/browser-tools

I had already updated our Ruby image to use a next-generation convenience image, but I also updated our PostgeSQL image to use one too. This will address the CircleCI warning we get in each build:

> You’re using a deprecated Docker convenience image. Upgrade to a next-gen Docker convenience image.

**Comment by shaunxp20** [comment]
One of the bigger, more noteworthy changes I ran into doing the Ruby upgrade was regarding the separation of positional and keyword arguments:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

I fixed all of the cases our tests caught, but there could be more cases, it usually surfaces with an error like "ArgumentError (wrong number of arguments (given X, expected Y))" - so if we run into that it's likely to be related to the Ruby upgrade, just something to be aware of. 😃

**Comment by shaunxp20** [comment]
Another thing to note, one test was commented out related to one of our PDF libraries:
`spec/requests/student/downloadable_parental_consent_spec.rb`

**Comment by shaunxp20** [comment]
Unfortunately, the Ruby upgrade can't be tested on Heroku Review Apps. There have been a few issues regarding Review Apps:
- Redis configuration (this has been resolved)
- Not being able to load CSS/JS files (this hasn't been resolved)

Originally I thought it was something to do with the upgrade as to why Review Apps wasn't working, but I checked another branch and I was running into the same issues, so it's something to do with Review Apps - there could still be issues with the Ruby upgrade, but trying to find them via Review Apps isn't going to be viable until we iron out the kinks for Review Apps. In order for the Ruby upgrade to be truly be tested it will have to be deployed to QA (after code review of course). 😃

**Comment by shaunxp20** [comment]
This one has landed on QA! 🙌 😅 There is a known issue regarding image uploads, those don't work. Also, there might be an issue w/ PDF generation, regarding parental consents (a test regarding this was commented out). Anywho, it's ready for some additional 👀 ! 😃

**Comment by dboyer** [comment]
I'm guessing this is the issue with PDF generation. On the parental consent tab of the student profile, there is an option to download a permission form so parents can sign a paper copy. Clicking that link (/student/downloadable_parental_consent.pdf) generates an error page. Clicking the media consent form on the same page does not cause the error.

<img width="1119" alt="Screen Shot 2022-09-01 at 2 58 04 PM" src="https://user-images.githubusercontent.com/516764/187991691-45361405-9d0d-494a-a25f-264db8016442.png">

**Comment by dboyer** [comment]
Confirmed that image uploads are not working in these places:

- Profile photo upload
- Team photo upload
- Submission image upload

**Comment by shaunxp20** [comment]
> I'm guessing this is the issue with PDF generation. On the parental consent tab of the student profile, there is an option to download a permission form so parents can sign a paper copy. Clicking that link (/student/downloadable_parental_consent.pdf) generates an error page.

I updated the `wkhtmltopdf-heroku` gem on QA and that fixed this issue! We'll still have to investigate why the related test is failing on CircleCI though.
