### ISSUE TITLE
Integrate Filestack on a branch

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3594]
Depends on outcome of questions from #3501.

- [x] Install gem

- [x]  Get picker working in student profile (or one area where photo uploads are) so that a photo can be uploaded by filestack (not saved to the DB)

- [x] Decide if Filestack is handling S3 link or if we will use current system of how we use S3

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3594?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by viviancan** [comment]
Confirming I was able to install filestack gem and integrate the filepicker widget on the student profile. I am able to upload/search/transform an image. This has not been set up to save the image yet. I will need to investigate the S3/filestack/rails workflow more. 
![filestack-student-profile.gif](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/8ecb753c-9daa-4334-8482-0a2a5c398c16)

**Comment by viviancan** [comment]
The filestack engineering account has been configured and connected to AWS S3. A new IAM user was created with specific properties. The policy also allows for filestack to connect to multiple buckets which is necessary for us since we have different environments. This has been verified through a basic proof of concept. The flow is very streamlined and is almost instant. I have also verified the images are in the correct s3 buckets. Filestack returns a reference URL that points to the s3 image URL. 

I am confident in closing this ticket and adding an additional ticket to handle the fallout tasks.

Here are some resources that were helpful while integrating this feature. 

- [Filestack s3 buckets](https://www.filestack.com/docs/uploads/storage/#amazon-s3)
- [StoreOptions](https://www.filestack.com/docs/uploads/pickers/web/#store-options)
- [PickerStoreOptions Docs](https://filestack.github.io/filestack-js/interfaces/pickerstoreoptions.html)
- [Filestack-Rails gem](https://github.com/filestack/filestack-rails)

**Comment by viviancan** [comment]
Just wanted to give an update on this one! I realized this morning that the images from my local computer were not saving to the s3 bucket. It was interesting because the "web search" feature would upload properly and save to the correct s3 bucket. After troubleshooting, I learned that the local computer upload uses a multipart upload flow for filestack compared to the direct upload for the web search. Ultimately I needed to add the region as one of the request parameters. I spent the rest of the day trying to get the form to work with the account model to save the filestack ref to the profile_image column. 

These are the remaining steps (I think)
- [ ]  Finalize the flow for saving the profile image to the DB
- [ ] Display the image on front end
- [ ] Finalize the env variables for the different buckets/regions

**Comment by viviancan** [comment]
The first part of this series of filestack tickets is about to be on QA and is on [PR 3615](https://github.com/Iridescent-CM/technovation-app/pull/3615). This PR is only the initial configuration and there won't be anything really to QA for it.
