### ISSUE TITLE
Integrate filestack into photo submission upload for students

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3692]

**Comment by viviancan** [comment]
Verifying this is on QA. I have a follow-up PR ([PR #3702](https://github.com/Iridescent-CM/technovation-app/pull/3702)) that will fix the photo grid styling in some of the other places where screenshots are viewed.

**Comment by dboyer** [comment]
Testing on QA and it's looking good. I love the process of selecting multiple images and then having an option to edit each - so smooth. A couple things:

- I see that only uploading from the computer is possible and not the web cam or link to a URL options that are available for profile pics. I think that makes sense but wanted to confirm that was an intentional choice.

- When uploading three or more images, the image extends beyond the container. I don't think this is a huge deal but a heads up in case it is specifically not supposed to do that.
<img width="720" alt="Screen Shot 2022-11-09 at 11 11 46 AM" src="https://user-images.githubusercontent.com/516764/200881880-79cab3e2-3d13-4928-8aa8-feceb5ebcd57.png">

**Comment by dboyer** [comment]
Three people on PT and I ran through photo submissions again as both a student and mentor and did not find any issues with the photo upload process. We're good to deploy this!

**Comment by viviancan** [comment]
Re: images extending the container. I could not reproduce this locally! I can try another solution using flexbox. I do not think this is a blocker though! Another ticket will be created so I can investigate further.
