### ISSUE TITLE
Fix broken View Details link on judge RPE dashboard

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3695]
"View Details" button on judge dashboard currently directs to a broken consent waiver page and instead should go to the new consent page (if judge needs to give consent) or just to the details of the submissions.

Note: the invite system for RPEs worked as expected. As a ChA, I sent an invite to a judge and as that judge, I received the email and was able to log-in to see this page.

**Comment by dboyer** [comment]
The screen recording below if for my deb+mentor0310@technovation.org account.

https://drive.google.com/file/d/17lAkCBpBK5msNBj2Uep2ea8YvG3FC8nq/view?usp=drivesdk

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3695?planning-poker) with Zenhub @shaunxp20 @viviancan

**Comment by dboyer** [comment]
One update: We may remove this button if it just links to a page with a few more details about the event and instead put all the details on the first page on the judge dashboard. So fixing this button is not a huge priority. However, I would like to know where it is supposed to go in case that is some other page we weren't expecting and not just the event details.

**Comment by viviancan** [comment]
![CleanShot 2023-01-13 at 08.03.45@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/0ff988eb-315f-4652-9547-1727b691b276)
![CleanShot 2023-01-13 at 08.04.03@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/8ad5e015-fd86-486c-9c2f-0f2662a9eff5)

After researching this issue, I discovered that this link did lead to the event details. This was changed in 2021 by the contractors as part of [this commit](https://github.com/Iridescent-CM/technovation-app/commit/70ba70bbee6b5dbd0e45e56d6de3a8890c1206d9). The path was changed from `event_path` to `consent_waiver_path` which is why the consent waiver details were displayed. The reason it was a random consent waiver is due to the event id parameter, which in this case was event id 143 😱 I have made the appropriate fix for now. I will work on removing it as part of #3766. I would still like to get this on QA for additional feedback in the case where a judge may be part of many RPEs (not sure if that is possible).

**Comment by dboyer** [comment]
Program Team confirmed that it is possible for judges to potentially be part of more than one RPE so we should assume that may happen, even if it's not a common use case.

**Comment by viviancan** [comment]
Verifying this is on QA

**Comment by dboyer** [comment]
Confirmed that the button is working correctly on QA. This is what the judge dashboard looks like with two events:

![image](https://user-images.githubusercontent.com/516764/212415549-8c8615bd-59e2-420d-bb63-310b914234d1.png)
