### ISSUE TITLE
Write and run task to remove any judges from being fully onboarded to 2023 season

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3696]
After #3670 is deployed, write and then run a rake task so that any judges who already completed training and are fully onboarded to the 2023 season are no longer onboarded. They need to complete the new training that will be ready in the spring.

To run this rake task on QA:
`$ heroku run bundle exec rake reset_judge_training --app technovation-qa`

and for Production:
`$ heroku run bundle exec rake reset_judge_training --app technovation`

**Comment by dboyer** [comment]
Likely reset the "training completed at" column in the judge profile table. May also need to adjust the judge onboarding column.

**Comment by shaunxp20** [comment]
Re: production - I wrote a dataclip (it's in Heroku) and it shows 23 judges who already completed judge training, I tested the rake task by using production data locally and it updated/reset 23 judge trainings. (I have since removed production data locally.)

Re: QA - I see 3 existing judges that we can use to test the rake task (we can also add a fresh judge to test w/ too), the 3 existing judges are:
- Deb Mentor
- Deb Judge0329
- Deb Judge0523
 
Once the rake task gets on QA, we can run it and if it's working correctly, those judges should no longer have their judge training completed.

**Comment by dboyer** [comment]
I'm good with running the rake task on QA to see if it correctly removes those three judges as fully onboarded.

**Comment by shaunxp20** [comment]
> I'm good with running the rake task on QA to see if it correctly removes those three judges as fully onboarded.

I ran the rake task for QA, 3 judges were updated:
- Deb Mentor
- Deb Judge0329
- Deb Judge0523

**Comment by dboyer** [comment]
Confirmed on QA that those three fully onboarded accounts are no longer onboarded. Please feel free to run the rake task on prod when you're ready!

**Comment by shaunxp20** [comment]
This has been run on production, I'll leave a comment in Slack with which judges were updated.

**Comment by dboyer** [comment]
Confirming that I see zero fully onboarded judges on production
