### ISSUE TITLE
Polymorphic route issues for mentors when viewing RPE details

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3740]

**Comment by dboyer** [comment]
@shaunxp20 I'm getting an error when I got to /mentor/regional_pitch_events_team_list and this message is in the airbrake channel:

ActionView::Template::Error: undefined method `mentor_team_event_path(team.event, team_id: team.id)' for #<ActionView::Base:0x0000000003fae8>

Should I be able to see this page because of the fix covered in this issue?

**Comment by shaunxp20** [comment]
> ActionView::Template::Error: undefined method `mentor_team_event_path(team.event, team_id: team.id)' for #ActionView::Base:0x0000000003fae8
> 
> Should I be able to see this page because of the fix covered in this issue?

The polymorphic link I fixed before (on 12/8) was one on a mentor's dashboard. This one^ should be fixed now too, it's on QA now. 🤞 😃

**Comment by dboyer** [comment]
It's like whack-a-mole! Knock out one incorrect link and another appears!

Confirming I can now see both /mentor/regional_pitch_events_team_list#/ and the page for a specific event on QA.
