### ISSUE TITLE
Spike: Explore how to add submissions to score grid for all judges (not just RPE judges)

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3799]
- Currently when a judge is manually assigned a submission it populates in the "scores in progress" table. If it has been manually assigned it should display in the submissions to score table 

Goal of this ticket is to explore how judge assignments work for online judging and how to integrate assignment functionality into the new "submissions to score" grid.

**Comment by viviancan** [comment]
Also refs #3789 - Update the judging format column in the "submissions to score" grid to be dynamic. May be helpful to review `app/controllers/judge/assigned_submissions_controller.rb`

**Comment by shaunxp20** [comment]
A brief recap after looking at this...

We have two types of judge assignments:
 - One for ChAs/RPEs, this will assign teams to judges
 - One for admins, this will create a new, blank score for a judge (that will put it in their judging queue)

I don't think it's going to be easy to consolidate these two different judge assignments into one, the ChA one is pretty intertwined with RPEs.

Which leaves us with keeping two separate ways of doing judging assignments, but figuring out how to get the scores into the correct tables "Submissions to Score" or "Scores in Progress".

When a judge assignment is done via the admin, the `created_at` and `updated_at` fields for that score will be the same in the database. Once a judge has starting scoring the submission, the `updated_at` field will get updated. (I said this morning that the "Start Score" button will not update the `update_at` field, but I looked/tried again, and it looks like it will actually update that field.)

I think we can use this, so that when `created_at` is the same as `updated_at`, those will go in the "Submissions to Score" table, and when they're different they will go into the "Scores in Progress" table. I think this will be the easier option vs reconfiguring/consolidating our judge assignment functionality.

**Comment by shaunxp20** [comment]
I added #3869 to work on the changes/updates. 👍
