### ISSUE TITLE
Only display highest awarded certificate for students for current season

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#3976]
If more than one certificate is awarded to a student for the current season, they will both be displayed, potentially with a broken layout (w/ a smaller screen size). We should only display the highest awarded certificate.

<img src="https://user-images.githubusercontent.com/58957909/236522359-5a279c76-aef1-4341-80b3-6f24a767640a.png" width="500">

**Comment by viviancan** [comment]
Confirming this is on QA. Can be tested for [participant 1270](https://technovation-qa.herokuapp.com/admin/participants/1270#/)

This participant was awarded a QF and SF certificate manually. When logged in as this participant only the semifinalist certificate is displayed

**Comment by dboyer** [comment]
Confirming I see only the semifinalist certificate for participant 1270.

It does say on the scores page that they were a quarterfinalist. I'm assuming that is because the semis certificate was manually awarded. But logging it here in case it matters.

<img width="695" alt="Screen Shot 2023-05-18 at 1 38 41 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/8d57746c-3df3-4383-a419-a0b14294dc04">

**Comment by viviancan** [comment]
Confirming that once I set this team as a QF The correct text displayed.![Screen Shot 2023-05-24 at 3.02.24 PM.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/627f90e2-8231-4491-a82a-71132263afa9)
