### ISSUE TITLE
Test run of international mentor background check

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4133]
Make a test run for a mentor in India or Canada and walk through the process from the mentor's point of view. Specifically:

- Where do they add needed info/documents?
- How are they updated on background check status?
- How do we as Technovation HQ know who is being checked and if they have passed?

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4133?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by viviancan** [comment]
I sent a support request to Checkr

From my understanding to create an invitation for international candidates, steps are the following: 
1. Create the candidate passing the work_locations attribute with the country 2 letter code
2. Get the candidate ID from the response 
3. Create an invitation through the invitations resource using the candidate ID and the package slug. 

The issue I am having is passing the work_locations attribute. I can see the request in the dashboard logs, but still getting an error

`resp = Checkr.request(:post, "/v1/candidates", {email: @email, first_name: "Test", work_locations: [{country: "IN"}]})
`

I receive the following error - **_Checkr::APIError (routed to incorrect data center)_**

If I remove the work locations attribute or change it to US I am able to successfully create a candidate. However since they are not international I cannot create an international invitation for this candidate. If I try to create an international invitation, I get this error 
**_Checkr::InvalidRequestError (international package cannot be used):_** 

I believe this issue is occurring because I am not able to add the international location initially when creating the candidate.

Just waiting for a reply!

**Comment by viviancan** [comment]
Latest message from Checkr support

`I have looped in our product engineers to assist. I don't believe we have an issue with the routing, but I am going to have them help me investigate and follow up as soon as possible! The screenshots and examples are perfect so this should help speed up the troubleshooting on our end.
`

**Comment by viviancan** [comment]
I received a response today and am able to create an international candidate using postman. I can create an international candidate from app using the Faraday gem. I **cannot** create an international candidate using the official-checkr (v1.7.1) gem. I cannot create an international invitation using the checkr gem either. Based on all of these points, I think there may be something up with the gem + international candidates. Either way, I replied and will be waiting for a response.

**Comment by viviancan** [comment]
Latest reply

> I have found that Checkr Ruby Gem does not support international checks so this was a good find. Our engineering team is going to treat this as an enhancement request and see what work needs to be done to update it. I do not have an ETA on completion for this unfortunately. Is there anything else I can assist with on this case?

It looks like we won't be able to use the checkr gem for international candidates. I will continue to work through this using an alternative approach
