### ISSUE TITLE
Pre-populate invited email address during registration

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4201]
When an admin invites someone to register, the invited email address should be pre-populated on the registration form..

**Comment by dboyer** [comment]
The invited email address should also be read only on the registration form so that the user cannot edit it to use a different email. We discovered that an invited ChA had forwarded the invite to someone else who changed the email address and the first email address could then no longer be used for a new invite. [Details here](https://iridescentlearning.slack.com/archives/C02J1GU8VRA/p1725562451448039).

**Comment by viviancan** [comment]
@shaun-technovation I can't move this card into code review! It won't save - but there is a PR open now for it! Ty!

**Comment by viviancan** [comment]
This is on QA

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- I was not able to edit the email address when I was sent a ChA invite
- I was able to edit the email address on my profile tab after I completed registration
- I invited a mentor and the address was pre-filled but editable in the registration flow
- I invited a judge and the address was pre-filled but editable in the registration flow
- I invited a student and the address was pre-filled but editable in the registration flow
