### ISSUE TITLE
Add name field to admin invites

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4216]
The invites table currently has a `name` field already, add this field (as an optional field) to the admin invites, when the invite is saved, the name field should be saved to the database.

**Notes**
The name field will be used in #4200.

**Comment by shaun-technovation** [comment]
I added the name field in #4242. One thing to note is that I ran into "null" names, like in the email (Dear null), in the admin, the judges table for an event that a ChA sees; I think I addressed all of them, but something to keep an eye out for in case I missed some.

**Comment by shaun-technovation** [comment]
This one is on QA and as mentioned above, keep an eye out for "null" names. :smiley:

**Comment by dboyer** [comment]
Tested on QA, and I see:

- When I add a name, it appears in the greeting of the email the person receives
- When I did not add a name, the email greeting just said "hello"
- When I included a name, it displayed it in the "invitee" column on the admin invites page

@shaun-technovation A few things:

- [ ] Is it correct that the name should not be auto-filled in the actual registration form? I assume this is intentional since we also do not fill in the email field with the email included in the invite. 

- [ ] Could we include some more help text on the admin page? Perhaps it could read: Option to include the invitee's name

<img width="465" alt="Screen Shot 2023-10-16 at 10 42 27 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/213f0688-39f4-49a9-a2b3-e16dfd2b31c4">

- [ ] I don't see how I can set the judge's name when I'm a ChA inviting a new judge to register on the platform. I see the name field before the email but I don't know how to add a name. I tried just typing a name and then leaving a space before the email address but the system won't allow that.

<img width="944" alt="Screen Shot 2023-10-16 at 10 54 27 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/f1d63400-4bce-485c-bbf6-5f65b598e42f">

- [ ] As a ChA adding a judge to an event, when I click on the name to remove the judge and not send an invite, I see the "null" mentioned.

<img width="598" alt="Screen Shot 2023-10-16 at 10 55 02 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/ef638b89-191c-4257-9a7c-8fd7b438f88b">

**Comment by shaun-technovation** [comment]
> * [ ] Is it correct that the name should not be auto-filled in the actual registration form? I assume this is intentional since we also do not fill in the email field with the email included in the invite.

The name currently doesn't auto-fill on the registration form. That would be a little tricky to do since the admin "name" field is one field, and the registration form has both first name and last name fields. Right now, the "name" is only being used in the invite email. We could add another issue for this, if it's something we wanted.

>  * [ ] Could we include some more help text on the admin page? Perhaps it could read: Option to include the invitee's name

Yup, good call, I'll add some help text in #4241. 👍 

> * [ ] I don't see how I can set the judge's name when I'm a ChA inviting a new judge to register on the platform. I see the name field before the email but I don't know how to add a name. I tried just typing a name and then leaving a space before the email address but the system won't allow that.

Chapter ambassadors currently don't have a way of setting the invitee's name. We definitely could add that feature via another issue though. 🤔 

> * [ ] As a ChA adding a judge to an event, when I click on the name to remove the judge and not send an invite, I see the "null" mentioned.

Good catch! I'll look at this in #4241. 👍

**Comment by dboyer** [comment]
Confirmed on QA that the additional help text on the name field is visible and the mention of "null" in the name of for an RPE judge is gone. I also see the name field for an RPE judge who hasn't registered says "Invited Judge" which works well to reduce confusion about whether the ChA is supposed to add a name.

No need to auto-fill the judge's name on the registration form.
