### ISSUE TITLE
Spike: Research and select cookie management option

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4278]
Split off from #3606

Two tasks:

- [ ] Determine if use of cookies on TG is at all inherited from permissions set by users to the Wordpress platforms (i.e. if you select only strictly necessary cookies on technovation.org and then click to my.technovationchallenge.org, is the cookie permission maintained between platforms). I doubt it but it's good to confirm.

- [ ] Research a cookie management option. The WordPress sites use CookieYes, but from their website, it might just be a plugin for CMS's and not useful for us.

**Comment by shaun-technovation** [comment]
Here's what a potential cookie consent banner would look like (out of the box):

<img src="https://github.com/Iridescent-CM/technovation-app/assets/58957909/fd38fc41-137f-4c0a-a5ea-08ccfa5bd24b" width="600">

This is using the [IMMO SQUARE Cookies Consent Banner](https://github.com/IMMOSQUARE/immosquare-cookies), which probably isn't what we want, because I can't find a way to opt in/out of different types of cookies.

Despite that and despite which library we end up using, here's some of the work we will potentially have to do:
- Stylize the consent banner
- Update consent banner verbiage

And when we implement the opt in/out functionality, I've identified the areas where we'll need to conditionally set cookies:
- Places where we need to conditionally opt in/out of Google Analytics:
  - `app/views/layouts/chapter_ambassador.html.erb`
  - `app/views/layouts/new_registration.html.erb`
  - `app/views/layouts/public_team_submissions.html.erb`
  - `app/views/layouts/application.html.erb`
  - `app/views/layouts/submissions.html.erb`
  - `app/views/layouts/application_rebrand.html.erb`

- Rails cookies are set via `set_cookie`, places where they need to be conditionally set:
  - `app/controllers/concerns/team_submission_section_controller.rb`
  - `app/controllers/mentor/cookies_controller.rb`
  - `app/controllers/admin/signups_controller.rb`
  - `app/controllers/admin/participant_sessions_controller.rb`
  - `app/controllers/student/cookies_controller.rb`
  - `app/controllers/chapter_ambassador/participant_sessions_controller.rb`
  - `app/controllers/application_controller.rb`
  - `app/models/store_location/location_storage.rb`
  - `app/technovation/sign_in.rb`

**Comment by shaun-technovation** [comment]
This is from [GDPR.EU about cookies](https://gdpr.eu/cookies/):

> Cookie compliance
> 
> To comply with the regulations governing cookies under the GDPR and the ePrivacy Directive you must:
> 
> - Receive users’ consent before you use any cookies except strictly necessary cookies.
> - Provide accurate and specific information about the data each cookie tracks and its purpose in plain language before consent is received.
> - Document and store consent received from users.
> - Allow users to access your service even if they refuse to allow the use of certain cookies
> - Make it as easy for users to withdraw their consent as it was for them to give their consent in the first place.

Regarding my comment about:

> ... which probably isn't what we want, because I can't find a way to opt in/out of different types of cookies

If I'm reading the compliance correctly^, people don't need a way to opt out of "strictly necessary cookies" so I think we would only need one opt-in/out option/button, which would just be for Google Analytics (and any future services).

> - Document and store consent received from users.
> - Make it as easy for users to withdraw their consent as it was for them to give their consent in the first place.

We'll have to think about how to address these two bullet points too. 🤔

**Comment by shaun-technovation** [comment]
> Determine if use of cookies on TG is at all inherited from permissions set by users to the Wordpress platforms (i.e. if you select only strictly necessary cookies on technovation.org and then click to my.technovationchallenge.org, is the cookie permission maintained between platforms). I doubt it but it's good to confirm.

Since they're separate domains, the cookies wouldn't be shared. I think there's a way to set that up though, but that still wouldn't 100% solve the issue on the TG platform though since not everyone would be coming from the WordPress site.

**Comment by dboyer** [comment]
Checked with MT and they're still happy with CookieYes. It looks like there's lots of options for use on non-wordpress sites too. https://www.cookieyes.com/developer-use-cases/

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- When I went to QA, I see the cookies banner on the bottom of the page
- I accepted all cookies
- I looked at the page source and I see the Google snippet
- I deleted the cookie and reloaded the page
- I went to QA again and chose only essential cookies
- I checked the developer tools and did not see anything for Google Analytics

**Comment by dboyer** [comment]
Confirming that I now see the cookie banner on production.
