### ISSUE TITLE
Spike: Research Salesforce integration with platform

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4321]
Currently, we're using Mailchimp for sending newsletters and we integrate the platform with Mailchimp. We're planning to switch to Salesforce in the next few months (exact timeline TBD) and need to consider how to integrate the platform with the available SF APIs. This task covers:

- Meeting with PT/MT/VET to determine what info needs to be sent to Salesforce
- Reviewing [existing SF APIs](https://developer.salesforce.com/docs/apis) to see which we can use
- Understanding the current integration with Mailchimp and if we need to change anything or can just change the API endpoint from Mailchimp to SF

We will have access to a sandbox SF instance for testing.

**Comment by dboyer** [comment]
Met with Sasha on Nov 22 to discuss Salesforce work. Next steps:

- Sasha will provide a list of the current data fields sent from the platform to Mailchimp, changes to that list of fields (subtractions and additions) that will need to go to Salesforce instead, the names of the fields in Salesforce that the platform data will map to, and which field updates need to trigger updating that data in SF
- Based on that list, dev team should identify Salesforce APIs that can be integrated into the platform

**Comment by shaun-technovation** [comment]
> * Reviewing [existing SF APIs](https://developer.salesforce.com/docs/apis) to see which we can use

The API we need to use is the "REST API" one, there is a gem called [Restforce](https://github.com/restforce/restforce) that creates a nice wrapper/interface for using this. I chatted with Vivian yesterday, we're okay moving forward with this gem.

> * Understanding the current integration with Mailchimp and if we need to change anything or can just change the API endpoint from Mailchimp to SF

There really isn't anything that can be reused from the Mailchimp integration since Salesforce is an entirely new and different integration.

One of the main differences I'm seeing with the Mailchimp integration is that when someone updates their info, we update their corresponding Mailchimp entry by looking them up by email address (by their old email address if it was changed). With Salesforce, the API updates someone by ID. When a new contact is created in Salesforce we get back an ID, so we'll want to save that and update them by their Salesforce ID.

**Comment by shaun-technovation** [comment]
Right now, I'm working on cleaning up the spike I did, to create the foundation for the Salesforce integration and making it production-ready. Some of the things I'm working on:
- making the Salesforce configuration dynamic
  - the URL, auth token, and API version
- adding an enable/disable feature
  -  similar to how Mailchimp works, so it can be disabled on QA or locally
- error handling/logging
- adding basic functionality to create a new contact in Salesforce
  - just adding name and email for now, other fields can be added later

One thing we'll need to address (most likely in another ticket) is getting an auth token for a generic login account on Salesforce, `services@...` or something (right now I'm just using my personal auth token). And automatically refreshing and caching the auth token for when it expires.

**Comment by shaun-technovation** [comment]
The basic groundwork is done for the integration.

Additional work that will be needed:
- Auth token caching (#4361)
  - this will finish the groundwork
- Deleting Salesforce contact (#4371)
- Adding additional fields (no issues for this yet)
  - Each field will need to be sent in the add and update calls
  - Each field will need to get updated in Salesforce when the values on the platform are updated

Issues to discuss:
- Salesforce Ids for existing accounts
- Unsubscribing from our newsletters (unsubscribing from Salesforce)
- Parent accounts
  - Share a contact in Salesforce with the student? Separate contact in Salesforce?
