### ISSUE TITLE
Research into chapter assignment

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4367]
Dig into the code to understand the answers to these questions:

1. How is a chapter ambassador associated with a geographic region? 

2. How are students and mentors initially assigned to a chapter? Assuming it is location based but we know they are not necessarily assigned to the geographically nearest chapter?

3. How in the database are students and mentors then associated with a chapter long-term?

**Comment by dboyer** [comment]
Eventual long-term goals:

1. Students and mentors can choose and/or be assigned by an admin or ChA to a chapter
2. Students can view a list of nearby chapters
3. Searching for teams based on chapter

**Comment by shaun-technovation** [comment]
I dug into this one a little bit. I think the noteworthy things are:
- Chapter ambassadors are assigned dynamically
  - The assignment is not saved to the database
  - The chapter ambassador lookup happens every time someone logs in

The basic assignment is as follows:
- Try to find a chapter ambassador in the same state as the current account
- If that fails, try to find one in the same country

I'm not sure I want to spend much more time on this research task. I remember we did a bunch of research and looking into how things work for the geocoder stuff and things never went anywhere with it. I think the way forward with this issue is to explore the recent idea of chapters being separate from chapter ambassadors, or just use what we have, but I think we need to decide if we're assigning everyone to chapters or chapter ambassadors first, and then we can save that assignment to the database and update it later. There's more to it, but ultimately, I think we need to iron some things out and then add some implementation tickets vs spending more time on this research task, IMHO.

**Comment by dboyer** [comment]
Any follow-up to this will be handled as part of implementing ChA onboarding and chapters as a specific entity in the database.
