### ISSUE TITLE
Make ChA side nav checklist dynamic

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4466]
We need to make the checklist on the new chapter ambassador dynamic, so the checkboxes appear checked after the step has been completed.

**Comment by shaun-technovation** [comment]
At planning we talked about making the sidenav visible for all the onboarding steps (starting w/ background checks). I have most of this roughed out for the background check steps, but there's quite a bit to it, so I created #4495 for this.

**Comment by shaun-technovation** [comment]
The new/dynamic sidenav is on Preview now.

**Comment by dboyer** [comment]
Testing on Preview, I see the side nav and the background check one shows as completed if the check passes.

@shaun-technovation Nothing happens when I click on the training tab even if I have completed the background check. I'm assuming that's due to additional work needed on the side nav.

<img width="743" alt="Screen Shot 2024-02-20 at 9 13 23 PM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/36f8f213-4b48-4114-b54c-558666830e55">
