### ISSUE TITLE
BUG: Student's parental consent status discrepency

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4492]
A student on production has two parental consent forms, one is signed, one is pending, more info in [Slack](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1707351133989509). The participant's datagrid shows the pending parental consent and the "profile debugging" section on the student's profile page shows the signed parental consent form.

**Comment by shaun-technovation** [comment]
The fix for this is now on QA. To test this on QA, I manually (via the Rails console) created a second parental consent (so one is signed and one is pending) for the student "Medium Swimmer". I verified the datagrid and admin student profile debugging sections are showing that the parental consent has been signed, and I verified that they are onboarded. I'm not sure how else to test this, basically there should be no pending/signed discrepancies.

To fix this, I made it so that the code looks for any signed parental consent for a season, this fix is being used by the datagrid, admin student profile debugging section, and onboarding step. Really, there should only be one parental consent per season, I'm not sure why there are multiples; I briefly looked, but that's really what's at the root of this issue. If we can determine how multiple parental consents are getting created and stop that from happening, that would be ideal.

Also, here is a snippet that show the two parental consents (one signed, one pending) for Medium Swimmer:

```
[#<ParentalConsent:0x00007f69497afa58
  id: 935,
  electronic_signature: "ON FILE",
  student_profile_id: 752,
  created_at: Fri, 11 Aug 2023 06:12:21.460737000 PDT -07:00,
  updated_at: Wed, 13 Mar 2024 06:08:36.557822000 PDT -07:00,
  newsletter_opt_in: nil,
  seasons: ["2024"],
  status: "signed",
  uploaded_consent_form: "PXL_20230712_222204681.jpg",
  uploaded_at: Sun, 13 Aug 2023 08:49:48.979805000 PDT -07:00,
  upload_approval_status: "approved",
  upload_approved_at: Wed, 13 Mar 2024 06:08:36.554917000 PDT -07:00,
  upload_rejected_at: nil>,
 #<ParentalConsent:0x00007f69497af8f0
  id: 1092,
  electronic_signature: nil,
  student_profile_id: 752,
  created_at: Wed, 13 Mar 2024 06:07:50.930546000 PDT -07:00,
  updated_at: Wed, 13 Mar 2024 06:07:50.930546000 PDT -07:00,
  newsletter_opt_in: nil,
  seasons: ["2024"],
  status: "pending",
  uploaded_consent_form: nil,
  uploaded_at: nil,
  upload_approval_status: "pending",
  upload_approved_at: nil,
  upload_rejected_at: nil>]
```

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- I could request a new consent form sent to a parent and received the email and could sign the forms
- I was able to upload a parental consent form

In terms of there being multiple consents, I tried a scenario where I uploaded a parental consent form. Then before an admin reviewed it, I sent an email to the parent and signed the forms digitally. The student dashboard and the participant admin page both said they had consent. The paper form was still listed on the admin page to review parental consent. I rejected the  uploaded form and received an email saying it was rejected. The student dashboard and the participant admin page both still said the consent was approved, which I'm assuming is due to the approved online forms.

I did get an email with a copy of the signed participation consent form for the Medium Swimmer account today at 9:08am. Does that match with the testing you did on QA @shaun-technovation ?
