### ISSUE TITLE
Research spike on Google Forms for ChA training quiz

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4513]

**Comment by shaun-technovation** [comment]
This spike is almost as far along as the SurveyMonkey spike. Creating the form/survey via Google Forms was easy, but I'm running into some embedding issues:

> [Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.
> [Error] Unrecognized Content-Security-Policy directive 'worker-src'.
> Refused to display 'https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSeOPjA6NJYDeLXaj9aYLB0oOixeJun4bUxTjOE3PcTURgfn4A%2Fviewform%3Fembedded%3Dtrue&followup=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSeOPjA6NJYDeLXaj9aYLB0oOixeJun4bUxTjOE3PcTURgfn4A%2Fviewform%3Fembedded%3Dtrue&ifkv=ATuJsjzo3RP2v0V-g8LYi1i4iwRaRGdCKztMIZUcfE5k1NjqpRTKtbjOA00nMXu55oHvqVrsVPGjMA&ltmpl=forms&osid=1&passive=1209600&service=wise&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-1223855274%3A1710280026867316&theme=mn' in a frame because it set 'X-Frame-Options' to 'DENY'.

From what I'm seeing, I think we need to update our `Content-Security-Policy`; I think at this point if we decide to go w/ Google Forms, we can spend more time looking at this.

Google Forms and SurveyMonkey are pretty similar in that you can create a form and embed them.

- Both of them have an API (I haven't looked too closely at either):
  - https://developers.google.com/forms/api/guides
  - https://surveymonkey.com/developer/api/v3/#overview

If we want to know who took the quiz on the Google Forms side or the SurveyMonkey side:
- For both of them, the quiz can be sent via email and then we would know who took the quiz
- If we embed the quiz on our platform:
  - SurveyMonkey allows for custom fields, we can fill in these custom fields and send the values to SurveyMonkey (all behind the scenes, I proved this out in the other spike)
  - Google Forms doesn't have custom fields, but you can add an extra email address field that can be used (potentially we could prefill the value)
 
For both options, we'd need to work on what happens when the quiz is completed:
- Getting their result
- How to move to the next step or display other content
- Saving the result (pass/fail, % correct?) on our end

Also, randomly and interestingly, the footer of this site has some more alternatives (and alternatives to DocuSign):
- https://paperform.co/
