### ISSUE TITLE
BUG: ChA viewing their own profile in Chapter Admin Activity

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4957]
If a chapter ambassador views their own profile under Chapter Admin Activity it causes an error.

```
ActionView::Template::Error: Missing partial chapter_ambassador/participants/_chapter_ambassador_onboarding, chapter_ambassador/_chapter_ambassador_onboarding, application/_chapter_ambassador_onboarding with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby]}. Searched in:   * "/app/app/views"   * "/app/vendor/bundle/ruby/3.1.0/gems/datagrid-1.6.3/app/views"   * "/app/vendor/bundle/ruby/3.1.0/gems/actiontext-6.1.7.7/app/views"   * "/app/vendor/bundle/ruby/3.1.0/gems/actionmailbox-6.1.7.7/app/views"
```

**Comment by dboyer** [comment]
Confirming on QA that when I access the admin activity as a ChA I could view the ChA's profile via the participants page and there was no error. The onboarding tasks and ability to update their status is gone.

I think ChAs should show in their own participant list since a chapter can have multiple ChAs. There may be a reason that a ChA would need to view the profiles of the other ChAs in their chapter.

Confirmed that as an admin, I still see the onboarding steps for a ChA but no longer see the ChA status box (pending, active, declined, spam). I'll double check with PT but I think that is fine. If we don't want a ChA to onboard, we can just unassign them from a chapter.

**Comment by dboyer** [comment]
Logged in as a ChA on production and confirmed that I could view my own profile on the chapter admin activity participants tab.
