### ISSUE TITLE
Don't register students to a new season if the are 18

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4961]
If a student signs-in to a new season and they are older than 18:

- Do not send the student program participant record to Salesforce
   - This causes the error `[SALESFORCE] undefined method parent_guardian_name' for nil:NilClass`
- Do not register them to the current season as a student

**Comment by dboyer** [comment]
Tested on QA:

- Logged in directly (not impersonating) with two students (/admin/participants/1129#/ and /admin/participants/1262#/) who are now over 18
- The platform gave me the warning message that I was over 18 and could not participate
- At this point, I checked with Sasha who confirmed that the students were not listed in the sandbox Salesforce site
- I think clicked the button to become a mentor and then completed the consent waiver so that I had done at least one action on my dashboard
- The admin pages for both accounts now say former student and returning mentor
- Checked with Sasha and she still did not see either account in the SF sandbox. We waited 30 minutes and neither account appeared.

@shaun-technovation Based on the description above, I think those accounts should now be logged as mentors. Is that correct?

**Comment by dboyer** [comment]
@shaun-technovation I did not receive a mentor welcome email for the previous accounts I tested. I just tried again with this account (/admin/participants/970#/) and they are now listed in the platform as a mentor but I never got a welcome email.

**Comment by dboyer** [comment]
Tested on QA:

- Logged in with a student now over 18
- Selected to become a mentor
- Received a mentor welcome email
- Confirmed with Sasha that the participant was listed as a mentor in Salesforce
- On the admin side, the participant record is flagged as a mentor for the 2025 season
